//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitMEPAddinApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitMEPAddinApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダクト/配管
        ///段差入力.
        /// </summary>
        internal static string BTN_EDIT_LEVEL {
            get {
                return ResourceManager.GetString("BTN_EDIT_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付属品の移動.
        /// </summary>
        internal static string BTN_MOVE_CONNECTOR {
            get {
                return ResourceManager.GetString("BTN_MOVE_CONNECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付属品の回転.
        /// </summary>
        internal static string BTN_ROTATE_TEES {
            get {
                return ResourceManager.GetString("BTN_ROTATE_TEES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回避対象なし.
        /// </summary>
        internal static string P_BTN_2PICK {
            get {
                return ResourceManager.GetString("P_BTN_2PICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回避対象あり.
        /// </summary>
        internal static string P_BTN_3PICK {
            get {
                return ResourceManager.GetString("P_BTN_3PICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回避対象あり(リンク).
        /// </summary>
        internal static string P_BTN_3PICK_Linkd {
            get {
                return ResourceManager.GetString("P_BTN_3PICK_Linkd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集.
        /// </summary>
        internal static string PLN_EDIT {
            get {
                return ResourceManager.GetString("PLN_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配管・ダクトの付属物を移動します。.
        /// </summary>
        internal static string T_TIP_BTN_MOVE_CONNECTOR {
            get {
                return ResourceManager.GetString("T_TIP_BTN_MOVE_CONNECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配管・ダクトの付属物を回転します。.
        /// </summary>
        internal static string T_TIP_BTN_ROTATE_TEES {
            get {
                return ResourceManager.GetString("T_TIP_BTN_ROTATE_TEES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダクト/配管の選択区間を指定の高さへ移動します。.
        /// </summary>
        internal static string T_TIP_P_BTN_2PICK {
            get {
                return ResourceManager.GetString("T_TIP_P_BTN_2PICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回避対象物(一般 モデル)を選択することで、回避対象物が避けられる高さにダクト/配管の選択区間を移動します。.
        /// </summary>
        internal static string T_TIP_P_BTN_3PICK {
            get {
                return ResourceManager.GetString("T_TIP_P_BTN_3PICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回避対象物(リンク モデル)を選択することで、回避対象物が避けられる高さにダクト/配管の選択区間を移動します。.
        /// </summary>
        internal static string T_TIP_P_BTN_3PICK_Linkd {
            get {
                return ResourceManager.GetString("T_TIP_P_BTN_3PICK_Linkd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダクト/配管の選択区間を指定の高さへ移動します。高さの指定方法により、[回避対象なし][回避対象あり][回避対象あり(リンク)]コマンドのいずれかを選択してください。.
        /// </summary>
        internal static string T_TIP_PD_BTN {
            get {
                return ResourceManager.GetString("T_TIP_PD_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REXJ.
        /// </summary>
        internal static string TAB_MEP_ADDIN {
            get {
                return ResourceManager.GetString("TAB_MEP_ADDIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JP設備.
        /// </summary>
        internal static string TAB_MEP_ADDIN_OLD {
            get {
                return ResourceManager.GetString("TAB_MEP_ADDIN_OLD", resourceCulture);
            }
        }
    }
}
