//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.JExtRAC.AutoLayoutTag.Resources {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADSK.JExtRAC.AutoLayoutTag.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string IDS_ERR_COMMAND { get { return ResourceManager.GetString("IDS_ERR_COMMAND", resourceCulture); } }
        internal static string IDS_ERR_NO_CHECKBOX { get { return ResourceManager.GetString("IDS_ERR_NO_CHECKBOX", resourceCulture); } }
        internal static string IDS_ERR_NO_ELEMENT { get { return ResourceManager.GetString("IDS_ERR_NO_ELEMENT", resourceCulture); } }
        internal static string IDS_ERR_NO_SELECT_OBJECT { get { return ResourceManager.GetString("IDS_ERR_NO_SELECT_OBJECT", resourceCulture); } }
        internal static string IDS_ERR_NO_SPECCIFY_PLACE_TAG { get { return ResourceManager.GetString("IDS_ERR_NO_SPECCIFY_PLACE_TAG", resourceCulture); } }
        internal static string IDS_ERR_OPENVIEWPLAN { get { return ResourceManager.GetString("IDS_ERR_OPENVIEWPLAN", resourceCulture); } }
        internal static string IDS_ERR_PARAMDEF { get { return ResourceManager.GetString("IDS_ERR_PARAMDEF", resourceCulture); } }
        internal static string IDS_FILE_ITEMS { get { return ResourceManager.GetString("IDS_FILE_ITEMS", resourceCulture); } }
        internal static string IDS_SHPARAM_DEF_CMD_AUTOMATIC_TAG { get { return ResourceManager.GetString("IDS_SHPARAM_DEF_CMD_AUTOMATIC_TAG", resourceCulture); } }
        internal static string IDS_SHPARAM_FILE { get { return ResourceManager.GetString("IDS_SHPARAM_FILE", resourceCulture); } }
        internal static string IDS_SHPARAM_GROUP { get { return ResourceManager.GetString("IDS_SHPARAM_GROUP", resourceCulture); } }
        internal static string IDS_TXT_ALL_CATEGORY { get { return ResourceManager.GetString("IDS_TXT_ALL_CATEGORY", resourceCulture); } }
        internal static string IDS_TXT_AREA_PREMISES { get { return ResourceManager.GetString("IDS_TXT_AREA_PREMISES", resourceCulture); } }
        internal static string IDS_TXT_AUTOMATIC_TAG { get { return ResourceManager.GetString("IDS_TXT_AUTOMATIC_TAG", resourceCulture); } }
        internal static string IDS_TXT_AUTO_JUDGMENT { get { return ResourceManager.GetString("IDS_TXT_AUTO_JUDGMENT", resourceCulture); } }
        internal static string IDS_TXT_CANCEL { get { return ResourceManager.GetString("IDS_TXT_CANCEL", resourceCulture); } }
        internal static string IDS_TXT_CATEGORY { get { return ResourceManager.GetString("IDS_TXT_CATEGORY", resourceCulture); } }
        internal static string IDS_TXT_CLOSELOG { get { return ResourceManager.GetString("IDS_TXT_CLOSELOG", resourceCulture); } }
        internal static string IDS_TXT_ERROR { get { return ResourceManager.GetString("IDS_TXT_ERROR", resourceCulture); } }
        internal static string IDS_TXT_EXTENSIBLE_STORAGE_NAME { get { return ResourceManager.GetString("IDS_TXT_EXTENSIBLE_STORAGE_NAME", resourceCulture); } }
        internal static string IDS_TXT_FIELD_SETTING { get { return ResourceManager.GetString("IDS_TXT_FIELD_SETTING", resourceCulture); } }
        internal static string IDS_TXT_GUID { get { return ResourceManager.GetString("IDS_TXT_GUID", resourceCulture); } }
        internal static string IDS_TXT_HAND_PRESET_TAG { get { return ResourceManager.GetString("IDS_TXT_HAND_PRESET_TAG", resourceCulture); } }
        internal static string IDS_TXT_HAS_LEADER { get { return ResourceManager.GetString("IDS_TXT_HAS_LEADER", resourceCulture); } }
        internal static string IDS_TXT_INFORMATION { get { return ResourceManager.GetString("IDS_TXT_INFORMATION", resourceCulture); } }
        internal static string IDS_TXT_LEADER { get { return ResourceManager.GetString("IDS_TXT_LEADER", resourceCulture); } }
        internal static string IDS_TXT_LEFT_RIGHT { get { return ResourceManager.GetString("IDS_TXT_LEFT_RIGHT", resourceCulture); } }
        internal static string IDS_TXT_LOG { get { return ResourceManager.GetString("IDS_TXT_LOG", resourceCulture); } }
        internal static string IDS_TXT_NONE { get { return ResourceManager.GetString("IDS_TXT_NONE", resourceCulture); } }
        internal static string IDS_TXT_NO_LEADER { get { return ResourceManager.GetString("IDS_TXT_NO_LEADER", resourceCulture); } }
        internal static string IDS_TXT_OBJECT { get { return ResourceManager.GetString("IDS_TXT_OBJECT", resourceCulture); } }
        internal static string IDS_TXT_ODER_MORE { get { return ResourceManager.GetString("IDS_TXT_ODER_MORE", resourceCulture); } }
        internal static string IDS_TXT_OK { get { return ResourceManager.GetString("IDS_TXT_OK", resourceCulture); } }
        internal static string IDS_TXT_ONLY_NEW_TAG { get { return ResourceManager.GetString("IDS_TXT_ONLY_NEW_TAG", resourceCulture); } }
        internal static string IDS_TXT_OUTSIDE_CROP_VIEW { get { return ResourceManager.GetString("IDS_TXT_OUTSIDE_CROP_VIEW", resourceCulture); } }
        internal static string IDS_TXT_PARAMETER { get { return ResourceManager.GetString("IDS_TXT_PARAMETER", resourceCulture); } }
        internal static string IDS_TXT_PICK_AREA { get { return ResourceManager.GetString("IDS_TXT_PICK_AREA", resourceCulture); } }
        internal static string IDS_TXT_PICK_OBJECTS { get { return ResourceManager.GetString("IDS_TXT_PICK_OBJECTS", resourceCulture); } }
        internal static string IDS_TXT_POSITTION_TAG { get { return ResourceManager.GetString("IDS_TXT_POSITTION_TAG", resourceCulture); } }
        internal static string IDS_TXT_RESET { get { return ResourceManager.GetString("IDS_TXT_RESET", resourceCulture); } }
        internal static string IDS_TXT_SAVELOG { get { return ResourceManager.GetString("IDS_TXT_SAVELOG", resourceCulture); } }
        internal static string IDS_TXT_SAVE_SETTING { get { return ResourceManager.GetString("IDS_TXT_SAVE_SETTING", resourceCulture); } }
        internal static string IDS_TXT_SCHEMA_NAME { get { return ResourceManager.GetString("IDS_TXT_SCHEMA_NAME", resourceCulture); } }
        internal static string IDS_TXT_SELECT { get { return ResourceManager.GetString("IDS_TXT_SELECT", resourceCulture); } }
        internal static string IDS_TXT_SELECTION_NUMBER { get { return ResourceManager.GetString("IDS_TXT_SELECTION_NUMBER", resourceCulture); } }
        internal static string IDS_TXT_SELECT_OBJECT { get { return ResourceManager.GetString("IDS_TXT_SELECT_OBJECT", resourceCulture); } }
        internal static string IDS_TXT_SETTING_CONDITION { get { return ResourceManager.GetString("IDS_TXT_SETTING_CONDITION", resourceCulture); } }
        internal static string IDS_TXT_SETTING_TAG { get { return ResourceManager.GetString("IDS_TXT_SETTING_TAG", resourceCulture); } }
        internal static string IDS_TXT_SET_AREA { get { return ResourceManager.GetString("IDS_TXT_SET_AREA", resourceCulture); } }
        internal static string IDS_TXT_SET_BY_HAND { get { return ResourceManager.GetString("IDS_TXT_SET_BY_HAND", resourceCulture); } }
        internal static string IDS_TXT_SET_TAG { get { return ResourceManager.GetString("IDS_TXT_SET_TAG", resourceCulture); } }
        internal static string IDS_TXT_TAG { get { return ResourceManager.GetString("IDS_TXT_TAG", resourceCulture); } }
        internal static string IDS_TXT_TOP_BOTTOM { get { return ResourceManager.GetString("IDS_TXT_TOP_BOTTOM", resourceCulture); } }
        internal static string IDS_TXT_VENDOR_ID { get { return ResourceManager.GetString("IDS_TXT_VENDOR_ID", resourceCulture); } }
        internal static string IDS_TXT_VIEW_TEMPLATE { get { return ResourceManager.GetString("IDS_TXT_VIEW_TEMPLATE", resourceCulture); } }
        internal static string IDS_TXT_XXX { get { return ResourceManager.GetString("IDS_TXT_XXX", resourceCulture); } }
    }
}
