<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Configuration Condition="'$(Configuration)' == ''">Debug 2027</Configuration>
    <Platform Condition="'$(Platform)' == ''">x64</Platform>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>ADSK.JExtRAC.AveSiteLevelHeightCalc</RootNamespace>
    <AssemblyName>ADSK.JExtRAC.AveSiteLevelHeightCalc</AssemblyName>
    <UseWpf>true</UseWpf>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <SatelliteResourceLanguages>ja;en</SatelliteResourceLanguages>
    <NeutralLanguage>ja</NeutralLanguage>
    <Configurations>Debug 2027;Release 2027</Configurations>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);NU1510</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug 2027|x64'">
    <DebugSymbols>true</DebugSymbols>
    <DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
    <DebugType>embedded</DebugType>
    <ErrorReport>prompt</ErrorReport>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release 2027|x64'">
    <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <ErrorReport>prompt</ErrorReport>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>C:\Program Files\Autodesk\Revit 2027\RevitAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>C:\Program Files\Autodesk\Revit 2027\RevitAPIUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Text.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Text.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Image.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Image.resx</DependentUpon>
    </Compile>
    <Compile Update="Create\FormCalcDraw.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Create\FormCalcDraw.Designer.cs">
      <DependentUpon>FormCalcDraw.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Image.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Image.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Text.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Text.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Text.en.resx" />
    <EmbeddedResource Update="Create\FormCalcDraw.resx">
      <DependentUpon>FormCalcDraw.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Content Include="rfa2027\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\IDI_SUBS_ICON.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Include="2_ADSK.JExtRAC.AveSiteLevelHeightCalc.addin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Images\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
