//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmdDuctSlopeChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmdDuctSlopeChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose one of the following actions..
        /// </summary>
        internal static string DLG_MAINCONTENT {
            get {
                return ResourceManager.GetString("DLG_MAINCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duct slope monitor.
        /// </summary>
        internal static string DLGTITLE_DUCT_SLOPED {
            get {
                return ResourceManager.GetString("DLGTITLE_DUCT_SLOPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【ヘルプ】ダクト勾配監視.pdf.
        /// </summary>
        internal static string FILE_HELP {
            get {
                return ResourceManager.GetString("FILE_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 691E5825-93DC-4f5c-9290-8072A4B631BC.
        /// </summary>
        internal static string ID_FAILUREDEFINITION {
            get {
                return ResourceManager.GetString("ID_FAILUREDEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_DUCT_SLOPEING.
        /// </summary>
        internal static string ID_TSKDIALOG {
            get {
                return ResourceManager.GetString("ID_TSKDIALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks for duct slope when the slope angle is less than 15°..
        /// </summary>
        internal static string MSG_ADDITIONALINFOMATION {
            get {
                return ResourceManager.GetString("MSG_ADDITIONALINFOMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the current operation..
        /// </summary>
        internal static string MSG_CANCEL {
            get {
                return ResourceManager.GetString("MSG_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue the current operation..
        /// </summary>
        internal static string MSG_CONTINUE {
            get {
                return ResourceManager.GetString("MSG_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duct has a slope applied..
        /// </summary>
        internal static string MSG_DUCT_SLOPING {
            get {
                return ResourceManager.GetString("MSG_DUCT_SLOPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When this toggle is on, Revit warns you while editing if a duct gets a slope with 0°&lt; slope angle &lt; 15°..
        /// </summary>
        internal static string MSG_TOOLTIP {
            get {
                return ResourceManager.GetString("MSG_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duct monitor.
        /// </summary>
        internal static string TITLE_RIBBON_PANEL {
            get {
                return ResourceManager.GetString("TITLE_RIBBON_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REXJ Standalone.
        /// </summary>
        internal static string TITLE_RIBBON_TAB {
            get {
                return ResourceManager.GetString("TITLE_RIBBON_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REXJ Standalone.
        /// </summary>
        internal static string TITLE_RIBBON_TAB_OLD {
            get {
                return ResourceManager.GetString("TITLE_RIBBON_TAB_OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duct slope.
        /// </summary>
        internal static string TITLE_TOGGLE_BTN1 {
            get {
                return ResourceManager.GetString("TITLE_TOGGLE_BTN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        internal static string TITLE_TOGGLE_BTN2 {
            get {
                return ResourceManager.GetString("TITLE_TOGGLE_BTN2", resourceCulture);
            }
        }
    }
}
