// ToDo: リソース読み込みできなくなったので暫定的にリソース読み込みの自動生成をやめ手動で対応。

//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using SectionListRC.Utils ;

namespace SectionListRC.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Image {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Image() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SectionListRC.Resources.Image", typeof(Image).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap GapSetting_Beam {
            get {
                // object obj = ResourceManager.GetObject("GapSetting_Beam", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.GapSetting_Beam.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap GapSetting_Column {
            get {
                // object obj = ResourceManager.GetObject("GapSetting_Column", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.GapSetting_Column.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap help_24x24 {
            get {
                // object obj = ResourceManager.GetObject("help_24x24", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.help_24x24.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Hint_Dimension {
            get {
                // object obj = ResourceManager.GetObject("Hint_Dimension", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.Hint_Dimension.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Hint_PositionFrame {
            get {
                // object obj = ResourceManager.GetObject("Hint_PositionFrame", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.Hint_PositionFrame.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Hint_Rebar {
            get {
                // object obj = ResourceManager.GetObject("Hint_Rebar", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.Hint_Rebar.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Hint_StirrupFrame_WebReinforcementFrame {
            get {
                // object obj = ResourceManager.GetObject("Hint_StirrupFrame_WebReinforcementFrame", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.Hint_StirrupFrame_WebReinforcementFrame.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_ADDPARAMETER_BEAM_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_ADDPARAMETER_BEAM_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.Hint_StirrupFrame_WebReinforcementFrame.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_ADDPARAMETER_BEAM_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_ADDPARAMETER_BEAM_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_ADDPARAMETER_BEAM_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_ADDPARAMETER_CANTIBEAM_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_ADDPARAMETER_CANTIBEAM_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_ADDPARAMETER_CANTIBEAM_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_ADDPARAMETER_CANTIBEAM_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_ADDPARAMETER_CANTIBEAM_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_ADDPARAMETER_CANTIBEAM_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_ADDPARAMETER_CIRCLE_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_ADDPARAMETER_CIRCLE_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_ADDPARAMETER_CIRCLE_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_ADDPARAMETER_CIRCLE_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_ADDPARAMETER_CIRCLE_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_ADDPARAMETER_CIRCLE_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_ADDPARAMETER_RECTANGL_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_ADDPARAMETER_RECTANGL_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_ADDPARAMETER_RECTANGL_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_ADDPARAMETER_RECTANGLE_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_ADDPARAMETER_RECTANGLE_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_ADDPARAMETER_RECTANGLE_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_BEAMLIST_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_BEAMLIST_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_BEAMLIST_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_BEAMLIST_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_BEAMLIST_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_BEAMLIST_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_BEAMLISTIMAGE_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_BEAMLISTIMAGE_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_BEAMLISTIMAGE_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_BEAMLISTIMAGE_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_BEAMLISTIMAGE_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_BEAMLISTIMAGE_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_BEAMLISTSETTING_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_BEAMLISTSETTING_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_BEAMLISTSETTING_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_BEAMLISTSETTING_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_BEAMLISTSETTING_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_BEAMLISTSETTING_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_COLUMNLIST_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_COLUMNLIST_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_COLUMNLIST_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_COLUMNLIST_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_COLUMNLIST_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_COLUMNLIST_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_COLUMNLISTIMAGE_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_COLUMNLISTIMAGE_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_COLUMNLISTIMAGE_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_COLUMNLISTIMAGE_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_COLUMNLISTIMAGE_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_COLUMNLISTIMAGE_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_COLUMNLISTSETTING_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_COLUMNLISTSETTING_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_COLUMNLISTSETTING_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_COLUMNLISTSETTING_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_COLUMNLISTSETTING_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_COLUMNLISTSETTING_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_COMMONSETTING_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_COMMONSETTING_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_COMMONSETTING_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_COMMONSETTING_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_COMMONSETTING_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_COMMONSETTING_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_EACHONEBEAMLIST_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_EACHONEBEAMLIST_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_EACHONEBEAMLIST_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_EACHONEBEAMLIST_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_EACHONEBEAMLIST_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_EACHONEBEAMLIST_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_EACHONECOLUMNLIST_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_EACHONECOLUMNLIST_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_EACHONECOLUMNLIST_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_EACHONECOLUMNLIST_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_EACHONECOLUMNLIST_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_EACHONECOLUMNLIST_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_EACHONELIST_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_EACHONELIST_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_EACHONELIST_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_LEVELSORTORDER_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_LEVELSORTORDER_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_LEVELSORTORDER_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_LEVELSORTORDER_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_LEVELSORTORDER_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_LEVELSORTORDER_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_PARAMETERMAPPING_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_PARAMETERMAPPING_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_PARAMETERMAPPING_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_PARAMETERMAPPING_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_PARAMETERMAPPING_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_PARAMETERMAPPING_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_SHOWHELP_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_SHOWHELP_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_SHOWHELP_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_SHOWHELP_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_SHOWHELP_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.IDI_BTN_SHOWHELP_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap LevelFrameSetting_InItemFrame {
            get {
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.LevelFrameSetting_InItemFrame.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap LevelFrameSetting_Show {
            get {
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.LevelFrameSetting_Show.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ParamMap_CantiGirder1 {
            get {
                // object obj = ResourceManager.GetObject("ParamMap_CantiGirder1", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.ParamMap_CantiGirder1.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ParamMap_CantiGirder2 {
            get {
                // object obj = ResourceManager.GetObject("ParamMap_CantiGirder2", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.ParamMap_CantiGirder2.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ParamMap_CircleColumn {
            get {
                // object obj = ResourceManager.GetObject("ParamMap_CircleColumn", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.ParamMap_CircleColumn.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ParamMap_Girder1 {
            get {
                // object obj = ResourceManager.GetObject("ParamMap_Girder1", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.ParamMap_Girder1.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ParamMap_Girder2 {
            get {
                // object obj = ResourceManager.GetObject("ParamMap_Girder2", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.ParamMap_Girder2.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ParamMap_RectangleColumn {
            get {
                // object obj = ResourceManager.GetObject("ParamMap_RectangleColumn", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.ParamMap_RectangleColumn.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap PositionSeparator_NoShow {
            get {
                // object obj = ResourceManager.GetObject("PositionSeparator_NoShow", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.PositionSeparator_NoShow.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap PositionSeparator_Show {
            get {
                // object obj = ResourceManager.GetObject("PositionSeparator_Show", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.PositionSeparator_Show.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
