//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.JExtRAC.ImportExcel.Resources {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADSK.JExtRAC.ImportExcel.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string IDS_ERROR_EXCEL_IS_EDITING {
            get { return ResourceManager.GetString("IDS_ERROR_EXCEL_IS_EDITING", resourceCulture); }
        }
        
        internal static string IDS_ERROR_NO_ACTIVE_SHEET {
            get { return ResourceManager.GetString("IDS_ERROR_NO_ACTIVE_SHEET", resourceCulture); }
        }
        
        internal static string IDS_ERROR_NO_ACTIVE_WORKBOOK {
            get { return ResourceManager.GetString("IDS_ERROR_NO_ACTIVE_WORKBOOK", resourceCulture); }
        }
        
        internal static string IDS_ERROR_NO_OPEN_EXCEL {
            get { return ResourceManager.GetString("IDS_ERROR_NO_OPEN_EXCEL", resourceCulture); }
        }
        
        internal static string IDS_ERROR_NO_FILE_SELECTED {
            get { return ResourceManager.GetString("IDS_ERROR_NO_FILE_SELECTED", resourceCulture); }
        }
        
        internal static string IDS_ERROR_TITLE_COLUMN {
            get { return ResourceManager.GetString("IDS_ERROR_TITLE_COLUMN", resourceCulture); }
        }
        
        internal static string IDS_INFO_IMPORT_EXCEL_SUCCESS {
            get { return ResourceManager.GetString("IDS_INFO_IMPORT_EXCEL_SUCCESS", resourceCulture); }
        }
        
        internal static string IDS_INFO_IMPORT_EXCEL_BACKGROUND_SUCCESS {
            get { return ResourceManager.GetString("IDS_INFO_IMPORT_EXCEL_BACKGROUND_SUCCESS", resourceCulture); }
        }
        
        internal static string IDS_SELECT_WORKSHEET_EXCEL {
            get { return ResourceManager.GetString("IDS_SELECT_WORKSHEET_EXCEL", resourceCulture); }
        }
        
        internal static string IDS_TXT_ERROR {
            get { return ResourceManager.GetString("IDS_TXT_ERROR", resourceCulture); }
        }
        
        internal static string IDS_TXT_INFORMATION {
            get { return ResourceManager.GetString("IDS_TXT_INFORMATION", resourceCulture); }
        }
        
        internal static string IDS_WARNING_IMPORT_EXCEL_GROUP {
            get { return ResourceManager.GetString("IDS_WARNING_IMPORT_EXCEL_GROUP", resourceCulture); }
        }
        
        internal static string IDS_WARNING_IMPORT_EXCEL_BACKGROUND_GROUP {
            get { return ResourceManager.GetString("IDS_WARNING_IMPORT_EXCEL_BACKGROUND_GROUP", resourceCulture); }
        }
        
        internal static string IDS_FILETYPES {
            get { return ResourceManager.GetString("IDS_FILETYPES", resourceCulture); }
        }
        
        internal static string IDS_TXT_LOAD_FILE {
            get { return ResourceManager.GetString("IDS_TXT_LOAD_FILE", resourceCulture); }
        }
        
        internal static string IDS_FORM_TITLE {
            get { return ResourceManager.GetString("IDS_FORM_TITLE", resourceCulture); }
        }
        
        internal static string IDS_BTN_CANCEL {
            get { return ResourceManager.GetString("IDS_BTN_CANCEL", resourceCulture); }
        }
        
        internal static string IDS_PSEUDO_COUNT {
            get { return ResourceManager.GetString("IDS_PSEUDO_COUNT", resourceCulture); }
        }
    }
}
