//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.JExtRAC.AveSiteLevelHeightCalc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADSK.JExtRAC.AveSiteLevelHeightCalc.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan Standards Extension.
        /// </summary>
        internal static string IDS_BTN_PANELNAME {
            get {
                return ResourceManager.GetString("IDS_BTN_PANELNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REXJ.
        /// </summary>
        internal static string IDS_BTN_TABNAME {
            get {
                return ResourceManager.GetString("IDS_BTN_TABNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JP建築.
        /// </summary>
        internal static string IDS_BTN_TABNAME_OLD {
            get {
                return ResourceManager.GetString("IDS_BTN_TABNAME_OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドが失敗しました.
        /// </summary>
        internal static string IDS_ERR_COMMAND {
            get {
                return ResourceManager.GetString("IDS_ERR_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均地盤面算定ポイント作成に失敗しました.
        /// </summary>
        internal static string IDS_ERR_CREATEAVEGLLEVELCALCPOS {
            get {
                return ResourceManager.GetString("IDS_ERR_CREATEAVEGLLEVELCALCPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 算定図作成に失敗しました.
        /// </summary>
        internal static string IDS_ERR_CREATECALCDRAW {
            get {
                return ResourceManager.GetString("IDS_ERR_CREATECALCDRAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 根拠式作成に失敗しました.
        /// </summary>
        internal static string IDS_ERR_CREATEGROUNDSEXP {
            get {
                return ResourceManager.GetString("IDS_ERR_CREATEGROUNDSEXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エリア境界線が直線ではありません.
        /// </summary>
        internal static string IDS_ERR_NOLINEAREABOUNDARY {
            get {
                return ResourceManager.GetString("IDS_ERR_NOLINEAREABOUNDARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エリア境界線が閉じられていません.
        /// </summary>
        internal static string IDS_ERR_NOTCLOSEDAREABOUNDARY {
            get {
                return ResourceManager.GetString("IDS_ERR_NOTCLOSEDAREABOUNDARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドパラメータの定義に失敗しました.
        /// </summary>
        internal static string IDS_ERR_PARAMCOMMAND {
            get {
                return ResourceManager.GetString("IDS_ERR_PARAMCOMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パラメータの定義に失敗しました.
        /// </summary>
        internal static string IDS_ERR_PARAMDEF {
            get {
                return ResourceManager.GetString("IDS_ERR_PARAMDEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エリア境界線を選択してから起動してください.
        /// </summary>
        internal static string IDS_ERR_SELAREABOUNDARY {
            get {
                return ResourceManager.GetString("IDS_ERR_SELAREABOUNDARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値を0より大きく設定してください.
        /// </summary>
        internal static string IDS_ERR_VALLARGE0 {
            get {
                return ResourceManager.GetString("IDS_ERR_VALLARGE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値を0以下に設定してください.
        /// </summary>
        internal static string IDS_ERR_VALLES0 {
            get {
                return ResourceManager.GetString("IDS_ERR_VALLES0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値が空白です.
        /// </summary>
        internal static string IDS_ERR_VALNULL {
            get {
                return ResourceManager.GetString("IDS_ERR_VALNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値が整数ではありません.
        /// </summary>
        internal static string IDS_ERR_VALNUMBER {
            get {
                return ResourceManager.GetString("IDS_ERR_VALNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値が実数ではありません.
        /// </summary>
        internal static string IDS_ERR_VALNUMERIC {
            get {
                return ResourceManager.GetString("IDS_ERR_VALNUMERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値が範囲外です.
        /// </summary>
        internal static string IDS_ERR_VALRANGE {
            get {
                return ResourceManager.GetString("IDS_ERR_VALRANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エリア平面図を開いてから使用してください.
        /// </summary>
        internal static string IDS_ERR_VIEWAREA {
            get {
                return ResourceManager.GetString("IDS_ERR_VIEWAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力した数字が範囲外でした。再入力してください。.
        /// </summary>
        internal static string IDS_ERROR_INVALID_LEVEL_VALUE {
            get {
                return ResourceManager.GetString("IDS_ERROR_INVALID_LEVEL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.txt.
        /// </summary>
        internal static string IDS_FILESETTINGNAME {
            get {
                return ResourceManager.GetString("IDS_FILESETTINGNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGL.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_BGL {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_BGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RexJpn-AveSiteLevleHeightCalc-Create.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_CMD_CREATE {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_CMD_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示レベル.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_DISPLEVEL {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_DISPLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示レベル.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_LEVEL {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 番号.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_NUMBER {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 横縮尺.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_SCALEHORIZONTAL {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_SCALEHORIZONTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 縦縮尺.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_SCALEVERTICAL {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_SCALEVERTICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RexJParam.txt.
        /// </summary>
        internal static string IDS_SHPARAM_FILE {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RexJpn.
        /// </summary>
        internal static string IDS_SHPARAM_GROUP {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REXJ_平均地盤面算定_記号.
        /// </summary>
        internal static string IDS_SYMCIRCLE {
            get {
                return ResourceManager.GetString("IDS_SYMCIRCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REXJ_平均地盤面_符号.
        /// </summary>
        internal static string IDS_SYMNAME_AVEGLLEVELPOINTSIGN {
            get {
                return ResourceManager.GetString("IDS_SYMNAME_AVEGLLEVELPOINTSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REXJ_既存BGL.
        /// </summary>
        internal static string IDS_SYMNAME_CURRENTBGL {
            get {
                return ResourceManager.GetString("IDS_SYMNAME_CURRENTBGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REXJ_設計GL.
        /// </summary>
        internal static string IDS_SYMNAME_DGL {
            get {
                return ResourceManager.GetString("IDS_SYMNAME_DGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REXJ_縮尺.
        /// </summary>
        internal static string IDS_SYMNAME_SCALE {
            get {
                return ResourceManager.GetString("IDS_SYMNAME_SCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ラベル 1.0mm.
        /// </summary>
        internal static string IDS_SYMNAME1_0 {
            get {
                return ResourceManager.GetString("IDS_SYMNAME1.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ラベル 2.0mm.
        /// </summary>
        internal static string IDS_SYMNAME2_0 {
            get {
                return ResourceManager.GetString("IDS_SYMNAME2.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ラベル 3.0mm.
        /// </summary>
        internal static string IDS_SYMNAME3_0 {
            get {
                return ResourceManager.GetString("IDS_SYMNAME3.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ラベル 4.0mm.
        /// </summary>
        internal static string IDS_SYMNAME4_0 {
            get {
                return ResourceManager.GetString("IDS_SYMNAME4.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ラベル 5.0mm.
        /// </summary>
        internal static string IDS_SYMNAME5_0 {
            get {
                return ResourceManager.GetString("IDS_SYMNAME5.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REXJ_平均地盤面算定_タグ.
        /// </summary>
        internal static string IDS_SYMTAG {
            get {
                return ResourceManager.GetString("IDS_SYMTAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/.
        /// </summary>
        internal static string IDS_TXT_1SLASH {
            get {
                return ResourceManager.GetString("IDS_TXT_1SLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 結果面積の桁処理.
        /// </summary>
        internal static string IDS_TXT_AREADECIMAL {
            get {
                return ResourceManager.GetString("IDS_TXT_AREADECIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均地盤面.
        /// </summary>
        internal static string IDS_TXT_AVEGLLEVEL {
            get {
                return ResourceManager.GetString("IDS_TXT_AVEGLLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BM高さ.
        /// </summary>
        internal static string IDS_TXT_BMHEIGHT {
            get {
                return ResourceManager.GetString("IDS_TXT_BMHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 算定図.
        /// </summary>
        internal static string IDS_TXT_CALCDRAW {
            get {
                return ResourceManager.GetString("IDS_TXT_CALCDRAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 算定ポイント.
        /// </summary>
        internal static string IDS_TXT_CALCPOINT {
            get {
                return ResourceManager.GetString("IDS_TXT_CALCPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string IDS_TXT_CANCEL {
            get {
                return ResourceManager.GetString("IDS_TXT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 閉じる.
        /// </summary>
        internal static string IDS_TXT_CLOSE {
            get {
                return ResourceManager.GetString("IDS_TXT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切り上げ.
        /// </summary>
        internal static string IDS_TXT_CLOSE1 {
            get {
                return ResourceManager.GetString("IDS_TXT_CLOSE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均地盤面算定図作成.
        /// </summary>
        internal static string IDS_TXT_CREATEAVEGLLEVELDRAW {
            get {
                return ResourceManager.GetString("IDS_TXT_CREATEAVEGLLEVELDRAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 算定図作成.
        /// </summary>
        internal static string IDS_TXT_CREATECALCDRAW {
            get {
                return ResourceManager.GetString("IDS_TXT_CREATECALCDRAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既存BGL.
        /// </summary>
        internal static string IDS_TXT_CURRENTBGL {
            get {
                return ResourceManager.GetString("IDS_TXT_CURRENTBGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切り捨て.
        /// </summary>
        internal static string IDS_TXT_CUTOFF {
            get {
                return ResourceManager.GetString("IDS_TXT_CUTOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小数点以下第.
        /// </summary>
        internal static string IDS_TXT_DECIMAL {
            get {
                return ResourceManager.GetString("IDS_TXT_DECIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        internal static string IDS_TXT_DEL {
            get {
                return ResourceManager.GetString("IDS_TXT_DEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓.
        /// </summary>
        internal static string IDS_TXT_DNSIGN {
            get {
                return ResourceManager.GetString("IDS_TXT_DNSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 横.
        /// </summary>
        internal static string IDS_TXT_HORIZONTAL {
            get {
                return ResourceManager.GetString("IDS_TXT_HORIZONTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レベル.
        /// </summary>
        internal static string IDS_TXT_LEVEL {
            get {
                return ResourceManager.GetString("IDS_TXT_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMからのレベル.
        /// </summary>
        internal static string IDS_TXT_LEVELFROMBM {
            get {
                return ResourceManager.GetString("IDS_TXT_LEVELFROMBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string IDS_TXT_M {
            get {
                return ResourceManager.GetString("IDS_TXT_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string IDS_TXT_MM {
            get {
                return ResourceManager.GetString("IDS_TXT_MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 番号.
        /// </summary>
        internal static string IDS_TXT_NUMBER {
            get {
                return ResourceManager.GetString("IDS_TXT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位を.
        /// </summary>
        internal static string IDS_TXT_ORDER {
            get {
                return ResourceManager.GetString("IDS_TXT_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四捨五入.
        /// </summary>
        internal static string IDS_TXT_ROUNDINGOFF {
            get {
                return ResourceManager.GetString("IDS_TXT_ROUNDINGOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 縮尺.
        /// </summary>
        internal static string IDS_TXT_SCALE {
            get {
                return ResourceManager.GetString("IDS_TXT_SCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単位.
        /// </summary>
        internal static string IDS_TXT_UNITLENGTH {
            get {
                return ResourceManager.GetString("IDS_TXT_UNITLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レベル更新.
        /// </summary>
        internal static string IDS_TXT_UPDATELEVEL {
            get {
                return ResourceManager.GetString("IDS_TXT_UPDATELEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 番号更新.
        /// </summary>
        internal static string IDS_TXT_UPDATENUMBER {
            get {
                return ResourceManager.GetString("IDS_TXT_UPDATENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↑.
        /// </summary>
        internal static string IDS_TXT_UPSIGN {
            get {
                return ResourceManager.GetString("IDS_TXT_UPSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 縦.
        /// </summary>
        internal static string IDS_TXT_VERTICAL {
            get {
                return ResourceManager.GetString("IDS_TXT_VERTICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 縦横比.
        /// </summary>
        internal static string IDS_TXT_VHRATE {
            get {
                return ResourceManager.GetString("IDS_TXT_VHRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.0.
        /// </summary>
        internal static string IDS_VAL_DIMDISTY {
            get {
                return ResourceManager.GetString("IDS_VAL_DIMDISTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -20.0.
        /// </summary>
        internal static string IDS_VAL_DIMPOSY {
            get {
                return ResourceManager.GetString("IDS_VAL_DIMPOSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.0.
        /// </summary>
        internal static string IDS_VAL_DIMSUPDIST {
            get {
                return ResourceManager.GetString("IDS_VAL_DIMSUPDIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string IDS_VAL_EXPINTERX {
            get {
                return ResourceManager.GetString("IDS_VAL_EXPINTERX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -5.
        /// </summary>
        internal static string IDS_VAL_EXPINTERY {
            get {
                return ResourceManager.GetString("IDS_VAL_EXPINTERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －.
        /// </summary>
        internal static string IDS_VAL_EXPSIGNTEXT {
            get {
                return ResourceManager.GetString("IDS_VAL_EXPSIGNTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string IDS_VAL_GLEXT {
            get {
                return ResourceManager.GetString("IDS_VAL_GLEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -20.
        /// </summary>
        internal static string IDS_VAL_SCALEPOSX {
            get {
                return ResourceManager.GetString("IDS_VAL_SCALEPOSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -3.
        /// </summary>
        internal static string IDS_VAL_SIGNPOSY {
            get {
                return ResourceManager.GetString("IDS_VAL_SIGNPOSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均地盤面算定図.
        /// </summary>
        internal static string IDS_VIEW_CALCDRAW {
            get {
                return ResourceManager.GetString("IDS_VIEW_CALCDRAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均地盤面根拠式.
        /// </summary>
        internal static string IDS_VIEW_GROUNDSEXP {
            get {
                return ResourceManager.GetString("IDS_VIEW_GROUNDSEXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既存の平均地盤面算定ポイントは削除されます.
        /// </summary>
        internal static string IDS_WAR_DELAVEGLLEVELPOINT {
            get {
                return ResourceManager.GetString("IDS_WAR_DELAVEGLLEVELPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMからのレベルを更新しますか？.
        /// </summary>
        internal static string IDS_WAR_UPDATELEVEL {
            get {
                return ResourceManager.GetString("IDS_WAR_UPDATELEVEL", resourceCulture);
            }
        }
    }
}
