//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.JExtRAC.ValueCopy.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   コマンドの実行中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_ERR_COMMAND {
            get {
                return ResourceManager.GetString("IDS_ERR_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_ERR_ERROR {
            get {
                return ResourceManager.GetString("IDS_ERR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADSK.JExtRAC.ValueCopy.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   値と最下値および最上値は同時に指定できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_ERR_ALLVALUE {
            get {
                return ResourceManager.GetString("IDS_ERR_ALLVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピーしたい属性を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_ERR_INPUTVALUE {
            get {
                return ResourceManager.GetString("IDS_ERR_INPUTVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1つ以上「コピー先」のインスタンスを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_ERR_NOSELECTELEMENT {
            get {
                return ResourceManager.GetString("IDS_ERR_NOSELECTELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピーできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_LOG_CANNOTCOPY {
            get {
                return ResourceManager.GetString("IDS_LOG_CANNOTCOPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_LOG_CANOTFINDPARAMETER {
            get {
                return ResourceManager.GetString("IDS_LOG_CANOTFINDPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値が範囲外です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_LOG_OUTOFRANGE {
            get {
                return ResourceManager.GetString("IDS_LOG_OUTOFRANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが 読み取り専用、または計算式なので、編集できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_LOG_READONLYORRECIPE {
            get {
                return ResourceManager.GetString("IDS_LOG_READONLYORRECIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常にコピーされました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_LOG_SUSSCESS {
            get {
                return ResourceManager.GetString("IDS_LOG_SUSSCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_ERROR {
            get {
                return ResourceManager.GetString("IDS_TXT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   適用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_APPLY {
            get {
                return ResourceManager.GetString("IDS_TXT_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_CANCEL {
            get {
                return ResourceManager.GetString("IDS_TXT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_CLOSELOG {
            get {
                return ResourceManager.GetString("IDS_TXT_CLOSELOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロパティ一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_COPYFORM {
            get {
                return ResourceManager.GetString("IDS_TXT_COPYFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーログ表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_ERRORDISPLAY {
            get {
                return ResourceManager.GetString("IDS_TXT_ERRORDISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファミリ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_FAMILYSTRINGFORM {
            get {
                return ResourceManager.GetString("IDS_TXT_FAMILYSTRINGFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_ICONSTATUSFORM {
            get {
                return ResourceManager.GetString("IDS_TXT_ICONSTATUSFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インスタンスID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_INSTANCEIDFORM {
            get {
                return ResourceManager.GetString("IDS_TXT_INSTANCEIDFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーログ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_LOG {
            get {
                return ResourceManager.GetString("IDS_TXT_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_OK {
            get {
                return ResourceManager.GetString("IDS_TXT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_PARAMETERNAMEFORM {
            get {
                return ResourceManager.GetString("IDS_TXT_PARAMETERNAMEFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_REPORTFORM {
            get {
                return ResourceManager.GetString("IDS_TXT_REPORTFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログ保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_SAVELOG {
            get {
                return ResourceManager.GetString("IDS_TXT_SAVELOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メッセージ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_STATUSFORM {
            get {
                return ResourceManager.GetString("IDS_TXT_STATUSFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   × に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_STATUSNOTOKSTRINGFORM {
            get {
                return ResourceManager.GetString("IDS_TXT_STATUSNOTOKSTRINGFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ○ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_STATUSOKSTRINGFORM {
            get {
                return ResourceManager.GetString("IDS_TXT_STATUSOKSTRINGFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイプ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_TYPESTRINGFORM {
            get {
                return ResourceManager.GetString("IDS_TXT_TYPESTRINGFORM", resourceCulture);
            }
        }
    }
}
