//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.JExtRAC.LevelFilter.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADSK.JExtRAC.LevelFilter.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string IDS_ERR_ERROR
        {
            get { return ResourceManager.GetString("IDS_ERR_ERROR", resourceCulture); }
        }

        internal static string IDS_ERR_NOELEMENTSELECT
        {
            get { return ResourceManager.GetString("IDS_ERR_NOELEMENTSELECT", resourceCulture); }
        }

        internal static string IDS_ERR_PARAMDEF
        {
            get { return ResourceManager.GetString("IDS_ERR_PARAMDEF", resourceCulture); }
        }

        internal static string IDS_SHPARAM_DEF_CMD
        {
            get { return ResourceManager.GetString("IDS_SHPARAM_DEF_CMD", resourceCulture); }
        }

        internal static string IDS_SHPARAM_FILE
        {
            get { return ResourceManager.GetString("IDS_SHPARAM_FILE", resourceCulture); }
        }

        internal static string IDS_SHPARAM_GROUP
        {
            get { return ResourceManager.GetString("IDS_SHPARAM_GROUP", resourceCulture); }
        }

        internal static string IDS_TXT_CANCEL
        {
            get { return ResourceManager.GetString("IDS_TXT_CANCEL", resourceCulture); }
        }

        internal static string IDS_TXT_CATEGORY
        {
            get { return ResourceManager.GetString("IDS_TXT_CATEGORY", resourceCulture); }
        }

        internal static string IDS_TXT_COUNT
        {
            get { return ResourceManager.GetString("IDS_TXT_COUNT", resourceCulture); }
        }

        internal static string IDS_TXT_COUNTOBJECT
        {
            get { return ResourceManager.GetString("IDS_TXT_COUNTOBJECT", resourceCulture); }
        }

        internal static string IDS_TXT_COUNTTYPE
        {
            get { return ResourceManager.GetString("IDS_TXT_COUNTTYPE", resourceCulture); }
        }

        internal static string IDS_TXT_FAMILY
        {
            get { return ResourceManager.GetString("IDS_TXT_FAMILY", resourceCulture); }
        }

        internal static string IDS_TXT_FAMILYTYPE
        {
            get { return ResourceManager.GetString("IDS_TXT_FAMILYTYPE", resourceCulture); }
        }

        internal static string IDS_TXT_FILTERFORM
        {
            get { return ResourceManager.GetString("IDS_TXT_FILTERFORM", resourceCulture); }
        }

        internal static string IDS_TXT_FILTERS
        {
            get { return ResourceManager.GetString("IDS_TXT_FILTERS", resourceCulture); }
        }

        internal static string IDS_TXT_MATERIAL
        {
            get { return ResourceManager.GetString("IDS_TXT_MATERIAL", resourceCulture); }
        }

        internal static string IDS_TXT_OK
        {
            get { return ResourceManager.GetString("IDS_TXT_OK", resourceCulture); }
        }

        internal static string IDS_TXT_OTHER
        {
            get { return ResourceManager.GetString("IDS_TXT_OTHER", resourceCulture); }
        }

        internal static string IDS_TXT_PARTS
        {
            get { return ResourceManager.GetString("IDS_TXT_PARTS", resourceCulture); }
        }

        internal static string IDS_TXT_PNTCHECK
        {
            get { return ResourceManager.GetString("IDS_TXT_PNTCHECK", resourceCulture); }
        }

        internal static string IDS_TXT_RULEFILTERS
        {
            get { return ResourceManager.GetString("IDS_TXT_RULEFILTERS", resourceCulture); }
        }

        internal static string IDS_TXT_SELECTALL
        {
            get { return ResourceManager.GetString("IDS_TXT_SELECTALL", resourceCulture); }
        }

        internal static string IDS_TXT_SELECTCLEAR
        {
            get { return ResourceManager.GetString("IDS_TXT_SELECTCLEAR", resourceCulture); }
        }
    }
}
