//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.JExtRAC.ExportSchedule.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADSK.JExtRAC.ExportSchedule.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 集計表のデータをExcelに出力できません。.
        /// </summary>
        internal static string IDS_ERROR_CANNOT_EXPORT_SCHEDULE
        {
            get
            {
                return ResourceManager.GetString("IDS_ERROR_CANNOT_EXPORT_SCHEDULE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Excelエクスポートが正常に完了しました。.
        /// </summary>
        internal static string IDS_EXPORT_SUCCESS
        {
            get
            {
                return ResourceManager.GetString("IDS_EXPORT_SUCCESS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UID warning (family/type).
        /// </summary>
        internal static string IDS_EXPORT_WARNINGFAMILYANDTYPE
        {
            get
            {
                return ResourceManager.GetString("IDS_EXPORT_WARNINGFAMILYANDTYPE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show header warning.
        /// </summary>
        internal static string IDS_EXPORT_WARNINGSHOWHEADER
        {
            get
            {
                return ResourceManager.GetString("IDS_EXPORT_WARNINGSHOWHEADER", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Combined UID and header warning.
        /// </summary>
        internal static string IDS_EXPORT_WARNING_FAMILYANDTYPE_SHOWHEADER
        {
            get
            {
                return ResourceManager.GetString("IDS_EXPORT_WARNING_FAMILYANDTYPE_SHOWHEADER", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Excelファイルが削除できません。.
        /// </summary>
        internal static string IDS_INFO_CANNOT_REMOVE_EXIST
        {
            get
            {
                return ResourceManager.GetString("IDS_INFO_CANNOT_REMOVE_EXIST", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 集計表を選択状態にしてコマンドを起動してください。.
        /// </summary>
        internal static string IDS_INFO_NO_ACTIVE_SCHEDULE
        {
            get
            {
                return ResourceManager.GetString("IDS_INFO_NO_ACTIVE_SCHEDULE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ファイル名は空白です。ファイル名を入力してください。.
        /// </summary>
        internal static string IDS_INFO_PATH_EMPTY
        {
            get
            {
                return ResourceManager.GetString("IDS_INFO_PATH_EMPTY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 名前を付けて保存.
        /// </summary>
        internal static string IDS_SAVE_EXCEL
        {
            get
            {
                return ResourceManager.GetString("IDS_SAVE_EXCEL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RexJParam.txt.
        /// </summary>
        internal static string IDS_SHPARAM_FILE
        {
            get
            {
                return ResourceManager.GetString("IDS_SHPARAM_FILE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RexJpn.
        /// </summary>
        internal static string IDS_SHPARAM_GROUP
        {
            get
            {
                return ResourceManager.GetString("IDS_SHPARAM_GROUP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 閉じる.
        /// </summary>
        internal static string IDS_TXT_CLOSELOG
        {
            get
            {
                return ResourceManager.GetString("IDS_TXT_CLOSELOG", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string IDS_TXT_ERROR
        {
            get
            {
                return ResourceManager.GetString("IDS_TXT_ERROR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        internal static string IDS_TXT_INFORMATION
        {
            get
            {
                return ResourceManager.GetString("IDS_TXT_INFORMATION", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to エラーログ.
        /// </summary>
        internal static string IDS_TXT_LOG
        {
            get
            {
                return ResourceManager.GetString("IDS_TXT_LOG", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ログ保存.
        /// </summary>
        internal static string IDS_TXT_SAVELOG
        {
            get
            {
                return ResourceManager.GetString("IDS_TXT_SAVELOG", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        internal static string IDS_TXT_WARNING
        {
            get
            {
                return ResourceManager.GetString("IDS_TXT_WARNING", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 集計表名称に日付を付ける.
        /// </summary>
        internal static string IDS_CHK_ADD_DATETIME
        {
            get
            {
                return ResourceManager.GetString("IDS_CHK_ADD_DATETIME", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 各インスタンスの内訳.
        /// </summary>
        internal static string IDS_CHK_ITEMIZED
        {
            get
            {
                return ResourceManager.GetString("IDS_CHK_ITEMIZED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to インポート機能を優先.
        /// </summary>
        internal static string IDS_RAD_FOR_IMPORT
        {
            get
            {
                return ResourceManager.GetString("IDS_RAD_FOR_IMPORT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 集計表表示出力を優先.
        /// </summary>
        internal static string IDS_RAD_FOR_SCHEDULE
        {
            get
            {
                return ResourceManager.GetString("IDS_RAD_FOR_SCHEDULE", resourceCulture);
            }
        }
    }
}
