//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.JExtRAC.ExportExcel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADSK.JExtRAC.ExportExcel.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エクスポートのデータが存在しません。.
        /// </summary>
        internal static string IDI_EXPORT_DATA_EMPTY {
            get {
                return ResourceManager.GetString("IDI_EXPORT_DATA_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excelにエクスポートできません。.
        /// </summary>
        internal static string IDS_ERROR_CANNOT_EXPORT_EXCEL {
            get {
                return ResourceManager.GetString("IDS_ERROR_CANNOT_EXPORT_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excelが起動していません。.
        /// </summary>
        internal static string IDS_ERROR_NO_OPEN_EXCEL {
            get {
                return ResourceManager.GetString("IDS_ERROR_NO_OPEN_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象項目が存在しません。.
        /// </summary>
        internal static string IDS_ERROR_SEARCH_NOT_FOUND {
            get {
                return ResourceManager.GetString("IDS_ERROR_SEARCH_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイトル行が不明です。.
        /// </summary>
        internal static string IDS_ERROR_TITLE_COLUMN {
            get {
                return ResourceManager.GetString("IDS_ERROR_TITLE_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excelエクスポートが正常に完了しました。.
        /// </summary>
        internal static string IDS_EXPORT_SUCCESS {
            get {
                return ResourceManager.GetString("IDS_EXPORT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在のビューにある要素.
        /// </summary>
        internal static string IDS_IN_CURRENT_VIEW {
            get {
                return ResourceManager.GetString("IDS_IN_CURRENT_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excelファイルが削除できません。.
        /// </summary>
        internal static string IDS_INFO_CANNOT_REMOVE_EXIST {
            get {
                return ResourceManager.GetString("IDS_INFO_CANNOT_REMOVE_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要素が選択されていません。.
        /// </summary>
        internal static string IDS_INFO_NO_EXIST_ELEMENTS {
            get {
                return ResourceManager.GetString("IDS_INFO_NO_EXIST_ELEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出力パラメータをご選択ください。.
        /// </summary>
        internal static string IDS_INFO_SELECT_PARAMETER_TO_EXPORT {
            get {
                return ResourceManager.GetString("IDS_INFO_SELECT_PARAMETER_TO_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 書出す要素の範囲を選択してください。.
        /// </summary>
        internal static string IDS_MAIN_CONTENT {
            get {
                return ResourceManager.GetString("IDS_MAIN_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 書出し範囲の選択.
        /// </summary>
        internal static string IDS_MAIN_INSTRUCTION {
            get {
                return ResourceManager.GetString("IDS_MAIN_INSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロジェクト全体の要素.
        /// </summary>
        internal static string IDS_SELECT_ALL {
            get {
                return ResourceManager.GetString("IDS_SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在選択されている要素.
        /// </summary>
        internal static string IDS_SELECTION_ELEMENT {
            get {
                return ResourceManager.GetString("IDS_SELECTION_ELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excelエクスポート.
        /// </summary>
        internal static string IDS_TITILE_SELECT_MODE {
            get {
                return ResourceManager.GetString("IDS_TITILE_SELECT_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string IDS_TXT_ERROR {
            get {
                return ResourceManager.GetString("IDS_TXT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        internal static string IDS_TXT_INFORMATION {
            get {
                return ResourceManager.GetString("IDS_TXT_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV UTF-8 (コンマ区切り) | *.csv.
        /// </summary>
        internal static string TXT_FILETYPE_CSV {
            get {
                return ResourceManager.GetString("TXT_FILETYPE_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Files | *.xls.
        /// </summary>
        internal static string TXT_FILETYPE_XLS {
            get {
                return ResourceManager.GetString("TXT_FILETYPE_XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Workbook | *.xlsx.
        /// </summary>
        internal static string TXT_FILETYPE_XLSX {
            get {
                return ResourceManager.GetString("TXT_FILETYPE_XLSX", resourceCulture);
            }
        }
        
        internal static string IDS_FORM_TITLE {
            get {
                return ResourceManager.GetString("IDS_FORM_TITLE", resourceCulture);
            }
        }
        
        internal static string IDS_LBL_CATEGORY {
            get {
                return ResourceManager.GetString("IDS_LBL_CATEGORY", resourceCulture);
            }
        }
        
        internal static string IDS_LBL_PARAMETER {
            get {
                return ResourceManager.GetString("IDS_LBL_PARAMETER", resourceCulture);
            }
        }
        
        internal static string IDS_LBL_OUTPUT {
            get {
                return ResourceManager.GetString("IDS_LBL_OUTPUT", resourceCulture);
            }
        }
        
        internal static string IDS_BTN_SEARCH {
            get {
                return ResourceManager.GetString("IDS_BTN_SEARCH", resourceCulture);
            }
        }
        
        internal static string IDS_BTN_RESTORE {
            get {
                return ResourceManager.GetString("IDS_BTN_RESTORE", resourceCulture);
            }
        }
        
        internal static string IDS_BTN_LOAD {
            get {
                return ResourceManager.GetString("IDS_BTN_LOAD", resourceCulture);
            }
        }
        
        internal static string IDS_BTN_SAVE {
            get {
                return ResourceManager.GetString("IDS_BTN_SAVE", resourceCulture);
            }
        }
        
        internal static string IDS_BTN_CANCEL {
            get {
                return ResourceManager.GetString("IDS_BTN_CANCEL", resourceCulture);
            }
        }
        
        internal static string IDS_SAVE_DIALOG_TITLE {
            get {
                return ResourceManager.GetString("IDS_SAVE_DIALOG_TITLE", resourceCulture);
            }
        }
        
        internal static string IDS_SAVE_SETTINGS_TITLE {
            get {
                return ResourceManager.GetString("IDS_SAVE_SETTINGS_TITLE", resourceCulture);
            }
        }
        
        internal static string IDS_LOAD_SETTINGS_TITLE {
            get {
                return ResourceManager.GetString("IDS_LOAD_SETTINGS_TITLE", resourceCulture);
            }
        }
        
        internal static string IDS_SETTINGS_FILE_FILTER {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_FILE_FILTER", resourceCulture);
            }
        }
        
        internal static string IDS_PSEUDO_TYPE_GUID {
            get {
                return ResourceManager.GetString("IDS_PSEUDO_TYPE_GUID", resourceCulture);
            }
        }
        
        internal static string IDS_PSEUDO_COUNT {
            get {
                return ResourceManager.GetString("IDS_PSEUDO_COUNT", resourceCulture);
            }
        }
    }
}
