//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.JExtRAC.FloorHeightDimension.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADSK.JExtRAC.FloorHeightDimension.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドが失敗しました.
        /// </summary>
        internal static string IDS_ERR_COMMAND {
            get {
                return ResourceManager.GetString("IDS_ERR_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レベルを選択してから起動してください。.
        /// </summary>
        internal static string IDS_ERR_NOLEVELSELECT {
            get {
                return ResourceManager.GetString("IDS_ERR_NOLEVELSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 立断面図ビューが開かれていません。.
        /// </summary>
        internal static string IDS_ERR_OPENVIEWSECTION {
            get {
                return ResourceManager.GetString("IDS_ERR_OPENVIEWSECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パラメータの定義に失敗しました.
        /// </summary>
        internal static string IDS_ERR_PARAMDEF {
            get {
                return ResourceManager.GetString("IDS_ERR_PARAMDEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RexJpn-FloorHeightDimension-Config.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_CMD_FLOORHEIGHTDIMENSION {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_CMD_FLOORHEIGHTDIMENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RexJParam.txt.
        /// </summary>
        internal static string IDS_SHPARAM_FILE {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RexJpn.
        /// </summary>
        internal static string IDS_SHPARAM_GROUP {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string IDS_TXT_CANCEL {
            get {
                return ResourceManager.GetString("IDS_TXT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string IDS_TXT_DIST {
            get {
                return ResourceManager.GetString("IDS_TXT_DIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string IDS_TXT_ERROR {
            get {
                return ResourceManager.GetString("IDS_TXT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 階高寸法.
        /// </summary>
        internal static string IDS_TXT_FLOORHEIGHTDIMENSION {
            get {
                return ResourceManager.GetString("IDS_TXT_FLOORHEIGHTDIMENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 距離.
        /// </summary>
        internal static string IDS_TXT_GROUP {
            get {
                return ResourceManager.GetString("IDS_TXT_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複数ビューに作成.
        /// </summary>
        internal static string IDS_TXT_MULTIVIEW {
            get {
                return ResourceManager.GetString("IDS_TXT_MULTIVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 階高寸法を作成するビューをご選択ください。.
        /// </summary>
        internal static string IDS_TXT_NOVIEWSELECT {
            get {
                return ResourceManager.GetString("IDS_TXT_NOVIEWSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string IDS_TXT_OK {
            get {
                return ResourceManager.GetString("IDS_TXT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全ビューの選択.
        /// </summary>
        internal static string IDS_TXT_SELECTALLVIEW {
            get {
                return ResourceManager.GetString("IDS_TXT_SELECTALLVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ビューを選択.
        /// </summary>
        internal static string IDS_TXT_SELECTVIEWS {
            get {
                return ResourceManager.GetString("IDS_TXT_SELECTVIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位置指定.
        /// </summary>
        internal static string IDS_TXT_SELPOS {
            get {
                return ResourceManager.GetString("IDS_TXT_SELPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string IDS_TXT_TOTALDIST {
            get {
                return ResourceManager.GetString("IDS_TXT_TOTALDIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 寸法タイプ.
        /// </summary>
        internal static string IDS_TXT_TYPE {
            get {
                return ResourceManager.GetString("IDS_TXT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string IDS_UNIT_MM {
            get {
                return ResourceManager.GetString("IDS_UNIT_MM", resourceCulture);
            }
        }
    }
}
