//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmdDuctDisplacement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmdDuctDisplacement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string DIALOG_TITLE_CONFIRM {
            get {
                return ResourceManager.GetString("DIALOG_TITLE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string DIALOG_TITLE_WARN {
            get {
                return ResourceManager.GetString("DIALOG_TITLE_WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string LOG_LEVEL_MAX {
            get {
                return ResourceManager.GetString("LOG_LEVEL_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string LOG_LEVEL_MIN {
            get {
                return ResourceManager.GetString("LOG_LEVEL_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move amount.
        /// </summary>
        public static string LVL_AmountMovement {
            get {
                return ResourceManager.GetString("LVL_AmountMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show move-distance options.
        /// </summary>
        public static string LVL_AmountMovementOPT_Disp {
            get {
                return ResourceManager.GetString("LVL_AmountMovementOPT_Disp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide move-distance options.
        /// </summary>
        public static string LVL_AmountMovementOPT_Hidden {
            get {
                return ResourceManager.GetString("LVL_AmountMovementOPT_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam.
        /// </summary>
        public static string LVL_Beam {
            get {
                return ResourceManager.GetString("LVL_Beam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string LVL_BottomSide {
            get {
                return ResourceManager.GetString("LVL_BottomSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string LVL_Center {
            get {
                return ResourceManager.GetString("LVL_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam.
        /// </summary>
        public static string LVL_DIRECT_SHAPE {
            get {
                return ResourceManager.GetString("LVL_DIRECT_SHAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down:.
        /// </summary>
        public static string LVL_Down {
            get {
                return ResourceManager.GetString("LVL_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45° elbow.
        /// </summary>
        public static string LVL_DuctElbow45Degree {
            get {
                return ResourceManager.GetString("LVL_DuctElbow45Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90° elbow.
        /// </summary>
        public static string LVL_DuctElbow90Degree {
            get {
                return ResourceManager.GetString("LVL_DuctElbow90Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oval duct.
        /// </summary>
        public static string LVL_EllipticalDuct {
            get {
                return ResourceManager.GetString("LVL_EllipticalDuct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit command.
        /// </summary>
        public static string LVL_EndThisCommand {
            get {
                return ResourceManager.GetString("LVL_EndThisCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam fireproofing thickness (entry).
        /// </summary>
        public static string LVL_EnterTheThicknessOfFireproofCoatingOfTheBeam {
            get {
                return ResourceManager.GetString("LVL_EnterTheThicknessOfFireproofCoatingOfTheBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FL.
        /// </summary>
        public static string LVL_FloorLevel {
            get {
                return ResourceManager.GetString("LVL_FloorLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string LVL_InValid {
            get {
                return ResourceManager.GetString("LVL_InValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interferes with.
        /// </summary>
        public static string LVL_IsolationWorningMessage_less {
            get {
                return ResourceManager.GetString("LVL_IsolationWorningMessage_less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required clearance between routed elements cannot be maintained.
        /// </summary>
        public static string LVL_IsolationWorningMessage_more {
            get {
                return ResourceManager.GetString("LVL_IsolationWorningMessage_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fittings.
        /// </summary>
        public static string LVL_Junction {
            get {
                return ResourceManager.GetString("LVL_Junction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level constraint.
        /// </summary>
        public static string LVL_Level {
            get {
                return ResourceManager.GetString("LVL_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string LVL_Move {
            get {
                return ResourceManager.GetString("LVL_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move-distance options.
        /// </summary>
        public static string LVL_MoveOption {
            get {
                return ResourceManager.GetString("LVL_MoveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply move.
        /// </summary>
        public static string LVL_Moving {
            get {
                return ResourceManager.GetString("LVL_Moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move mode.
        /// </summary>
        public static string LVL_MovingMethod {
            get {
                return ResourceManager.GetString("LVL_MovingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string LVL_None {
            get {
                return ResourceManager.GetString("LVL_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        public static string LVL_Of {
            get {
                return ResourceManager.GetString("LVL_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string LVL_Offset {
            get {
                return ResourceManager.GetString("LVL_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearances — .
        /// </summary>
        public static string LVL_OfTarget {
            get {
                return ResourceManager.GetString("LVL_OfTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick clearance target.
        /// </summary>
        public static string LVL_Pick_a_TargetObject {
            get {
                return ResourceManager.GetString("LVL_Pick_a_TargetObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick clearance target &lt;linked model&gt;.
        /// </summary>
        public static string LVL_Pick_a_TargetObject_LinkModel {
            get {
                return ResourceManager.GetString("LVL_Pick_a_TargetObject_LinkModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe type.
        /// </summary>
        public static string LVL_PipeType {
            get {
                return ResourceManager.GetString("LVL_PipeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement zone.
        /// </summary>
        public static string LVL_Placement {
            get {
                return ResourceManager.GetString("LVL_Placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout rules.
        /// </summary>
        public static string LVL_PlacementCondition {
            get {
                return ResourceManager.GetString("LVL_PlacementCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement position.
        /// </summary>
        public static string LVL_Position {
            get {
                return ResourceManager.GetString("LVL_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to segment pick.
        /// </summary>
        public static string LVL_ReturnToSectionSelection {
            get {
                return ResourceManager.GetString("LVL_ReturnToSectionSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round duct.
        /// </summary>
        public static string LVL_RoundDuct {
            get {
                return ResourceManager.GetString("LVL_RoundDuct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounding increment.
        /// </summary>
        public static string LVL_RoundingPrecision {
            get {
                return ResourceManager.GetString("LVL_RoundingPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-curve.
        /// </summary>
        public static string LVL_SCurveShapedDuct {
            get {
                return ResourceManager.GetString("LVL_SCurveShapedDuct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected element FL:.
        /// </summary>
        public static string LVL_SelectedFL {
            get {
                return ResourceManager.GetString("LVL_SelectedFL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearance spacing.
        /// </summary>
        public static string LVL_Separation {
            get {
                return ResourceManager.GetString("LVL_Separation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        public static string LVL_Shape {
            get {
                return ResourceManager.GetString("LVL_Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangular duct.
        /// </summary>
        public static string LVL_SquareDuct {
            get {
                return ResourceManager.GetString("LVL_SquareDuct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum clearance between routed elements.
        /// </summary>
        public static string LVL_TheDistanceOfElement {
            get {
                return ResourceManager.GetString("LVL_TheDistanceOfElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam fireproofing thickness.
        /// </summary>
        public static string LVL_ThicknessOfFireProofOfBeam {
            get {
                return ResourceManager.GetString("LVL_ThicknessOfFireProofOfBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string LVL_TopSide {
            get {
                return ResourceManager.GetString("LVL_TopSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match levels.
        /// </summary>
        public static string LVL_UnifyLevels {
            get {
                return ResourceManager.GetString("LVL_UnifyLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up:.
        /// </summary>
        public static string LVL_Up {
            get {
                return ResourceManager.GetString("LVL_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string LVL_Valid {
            get {
                return ResourceManager.GetString("LVL_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment pick error: the specified duct or pipe is not contained in the picked segment..
        /// </summary>
        public static string MSG_ERROR1 {
            get {
                return ResourceManager.GetString("MSG_ERROR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not reserve space for reconnecting the routing segment; cannot apply the move..
        /// </summary>
        public static string MSG_ERROR2 {
            get {
                return ResourceManager.GetString("MSG_ERROR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not trim the branch taps; routing cannot be moved..
        /// </summary>
        public static string MSG_ERROR3 {
            get {
                return ResourceManager.GetString("MSG_ERROR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two MEPCurve elements are not connected..
        /// </summary>
        public static string MSG_WARN1 {
            get {
                return ResourceManager.GetString("MSG_WARN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start this command from a plan view or a reflected ceiling plan..
        /// </summary>
        public static string MSG_WARN2 {
            get {
                return ResourceManager.GetString("MSG_WARN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot pick a duct endpoint that connects to a fabrication part..
        /// </summary>
        public static string MSG_WARN3 {
            get {
                return ResourceManager.GetString("MSG_WARN3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the move segment, pick two distinct points..
        /// </summary>
        public static string MSG_WARN4 {
            get {
                return ResourceManager.GetString("MSG_WARN4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the duct or pipe to trim at the picked split location..
        /// </summary>
        public static string REQ_ENTER_CUT_OBJ {
            get {
                return ResourceManager.GetString("REQ_ENTER_CUT_OBJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick split point.
        /// </summary>
        public static string REQ_ENTER_POINT {
            get {
                return ResourceManager.GetString("REQ_ENTER_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string REQ_ENTER_POINT_CNT {
            get {
                return ResourceManager.GetString("REQ_ENTER_POINT_CNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a reference element to derive the move amount..
        /// </summary>
        public static string REQ_ENTER_TARGET {
            get {
                return ResourceManager.GetString("REQ_ENTER_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string S_CURVE_ANGLE {
            get {
                return ResourceManager.GetString("S_CURVE_ANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S管(楕円型).
        /// </summary>
        public static string S_CURVE_OVL_FAMILY {
            get {
                return ResourceManager.GetString("S_CURVE_OVL_FAMILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S管(楕円型).rfa.
        /// </summary>
        public static string S_CURVE_OVL_FILE {
            get {
                return ResourceManager.GetString("S_CURVE_OVL_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 標準.
        /// </summary>
        public static string S_CURVE_OVL_TYPE {
            get {
                return ResourceManager.GetString("S_CURVE_OVL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S管(配管).
        /// </summary>
        public static string S_CURVE_PIPE_FAMILY {
            get {
                return ResourceManager.GetString("S_CURVE_PIPE_FAMILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S管(配管).rfa.
        /// </summary>
        public static string S_CURVE_PIPE_FILE {
            get {
                return ResourceManager.GetString("S_CURVE_PIPE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 標準.
        /// </summary>
        public static string S_CURVE_PIPE_TYPE {
            get {
                return ResourceManager.GetString("S_CURVE_PIPE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S管(角型).
        /// </summary>
        public static string S_CURVE_REC_FAMILY {
            get {
                return ResourceManager.GetString("S_CURVE_REC_FAMILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S管(角型).rfa.
        /// </summary>
        public static string S_CURVE_REC_FILE {
            get {
                return ResourceManager.GetString("S_CURVE_REC_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 標準.
        /// </summary>
        public static string S_CURVE_REC_TYPE {
            get {
                return ResourceManager.GetString("S_CURVE_REC_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S管(円型).
        /// </summary>
        public static string S_CURVE_RND_FAMILY {
            get {
                return ResourceManager.GetString("S_CURVE_RND_FAMILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S管(円型).rfa.
        /// </summary>
        public static string S_CURVE_RND_FILE {
            get {
                return ResourceManager.GetString("S_CURVE_RND_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 標準.
        /// </summary>
        public static string S_CURVE_RND_TYPE {
            get {
                return ResourceManager.GetString("S_CURVE_RND_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Worn_Caption {
            get {
                return ResourceManager.GetString("Worn_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occurred; the routing cannot be moved..
        /// </summary>
        public static string Worn_ExceptionMessege {
            get {
                return ResourceManager.GetString("Worn_ExceptionMessege", resourceCulture);
            }
        }
    }
}
