//------------------------------------------------------------------------------
// <auto-generated>
//     Strongly typed resources for ADSK.ViewExtension.TenkaiView
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.ViewExtension.TenkaiView.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() { }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
                        "ADSK.ViewExtension.TenkaiView.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static string CMD_TENKAIVIEW => ResourceManager.GetString("CMD_TENKAIVIEW", resourceCulture);
        internal static string ERR_CANNOTSELECTROOM => ResourceManager.GetString("ERR_CANNOTSELECTROOM", resourceCulture);
        internal static string ERR_CHANGEROOMBOUNDARYFAIL => ResourceManager.GetString("ERR_CHANGEROOMBOUNDARYFAIL", resourceCulture);
        internal static string ERR_CREATEDIMENSIONFAIL => ResourceManager.GetString("ERR_CREATEDIMENSIONFAIL", resourceCulture);
        internal static string ERR_CREATETENKAIVIEWFAIL => ResourceManager.GetString("ERR_CREATETENKAIVIEWFAIL", resourceCulture);
        internal static string ERR_NOACTIBEVIEW => ResourceManager.GetString("ERR_NOACTIBEVIEW", resourceCulture);
        internal static string ERR_NODIMSTYLE => ResourceManager.GetString("ERR_NODIMSTYLE", resourceCulture);
        internal static string ERR_NOFLOORPLAN => ResourceManager.GetString("ERR_NOFLOORPLAN", resourceCulture);
        internal static string ERR_NOLEVEL => ResourceManager.GetString("ERR_NOLEVEL", resourceCulture);
        internal static string ERR_NOROOM => ResourceManager.GetString("ERR_NOROOM", resourceCulture);
        internal static string ERR_NOROOMONLEVEL => ResourceManager.GetString("ERR_NOROOMONLEVEL", resourceCulture);
        internal static string ERR_NOSELECTROOM => ResourceManager.GetString("ERR_NOSELECTROOM", resourceCulture);
        internal static string ERR_NOSELECTVIEWFAMILY => ResourceManager.GetString("ERR_NOSELECTVIEWFAMILY", resourceCulture);
        internal static string ERR_NOTFLOORPLAN => ResourceManager.GetString("ERR_NOTFLOORPLAN", resourceCulture);
        internal static string ERR_NOTFLOORPLANVIEW => ResourceManager.GetString("ERR_NOTFLOORPLANVIEW", resourceCulture);
        internal static string ERR_NOTNUMBER => ResourceManager.GetString("ERR_NOTNUMBER", resourceCulture);
        internal static string ERR_OPERATIONCANCEL => ResourceManager.GetString("ERR_OPERATIONCANCEL", resourceCulture);
        internal static string ERR_ROLLBACKFAIL => ResourceManager.GetString("ERR_ROLLBACKFAIL", resourceCulture);
        internal static string ERR_UPDATECROPBOXFAIL => ResourceManager.GetString("ERR_UPDATECROPBOXFAIL", resourceCulture);
        internal static string ERR_VIEWDUPLICATED => ResourceManager.GetString("ERR_VIEWDUPLICATED", resourceCulture);
        internal static string INFO_OPERATIONCANCEL => ResourceManager.GetString("INFO_OPERATIONCANCEL", resourceCulture);
        internal static string LBL_INFO => ResourceManager.GetString("LBL_INFO", resourceCulture);
        internal static string TRANS_CREATEDIMENSION => ResourceManager.GetString("TRANS_CREATEDIMENSION", resourceCulture);
        internal static string TRANS_CREATEVIEWSECTION => ResourceManager.GetString("TRANS_CREATEVIEWSECTION", resourceCulture);
        internal static string TRANS_ELEVATIONMARKER => ResourceManager.GetString("TRANS_ELEVATIONMARKER", resourceCulture);
        internal static string TRANS_ROLLBACKROOMBOUNDARY => ResourceManager.GetString("TRANS_ROLLBACKROOMBOUNDARY", resourceCulture);
        internal static string TRANS_SETROOMBOUNDARY => ResourceManager.GetString("TRANS_SETROOMBOUNDARY", resourceCulture);
        internal static string TRANS_UPDATECROPBOX => ResourceManager.GetString("TRANS_UPDATECROPBOX", resourceCulture);
        internal static string TXT_DIRECTIONA => ResourceManager.GetString("TXT_DIRECTIONA", resourceCulture);
        internal static string TXT_DIRECTIONB => ResourceManager.GetString("TXT_DIRECTIONB", resourceCulture);
        internal static string TXT_DIRECTIONC => ResourceManager.GetString("TXT_DIRECTIONC", resourceCulture);
        internal static string TXT_DIRECTIOND => ResourceManager.GetString("TXT_DIRECTIOND", resourceCulture);
        internal static string TXT_ERR => ResourceManager.GetString("TXT_ERR", resourceCulture);
        internal static string TXT_ERROR => ResourceManager.GetString("TXT_ERROR", resourceCulture);
        internal static string TXT_PREFIX => ResourceManager.GetString("TXT_PREFIX", resourceCulture);
        internal static string TXT_PROCESSING => ResourceManager.GetString("TXT_PROCESSING", resourceCulture);
        internal static string TXT_SHEETTITLEFORMAT => ResourceManager.GetString("TXT_SHEETTITLEFORMAT", resourceCulture);
        internal static string TXT_SLASH => ResourceManager.GetString("TXT_SLASH", resourceCulture);
        internal static string TXT_SUFFIX_EAST => ResourceManager.GetString("TXT_SUFFIX_EAST", resourceCulture);
        internal static string TXT_SUFFIX_NORTH => ResourceManager.GetString("TXT_SUFFIX_NORTH", resourceCulture);
        internal static string TXT_SUFFIX_SOUTH => ResourceManager.GetString("TXT_SUFFIX_SOUTH", resourceCulture);
        internal static string TXT_SUFFIX_WEST => ResourceManager.GetString("TXT_SUFFIX_WEST", resourceCulture);
        internal static string TXT_TRANSACTIONNAME => ResourceManager.GetString("TXT_TRANSACTIONNAME", resourceCulture);
        internal static string TXT_UNDERSCORE => ResourceManager.GetString("TXT_UNDERSCORE", resourceCulture);
        internal static string TXT_VIEWA => ResourceManager.GetString("TXT_VIEWA", resourceCulture);
        internal static string TXT_VIEWB => ResourceManager.GetString("TXT_VIEWB", resourceCulture);
        internal static string TXT_VIEWC => ResourceManager.GetString("TXT_VIEWC", resourceCulture);
        internal static string TXT_VIEWD => ResourceManager.GetString("TXT_VIEWD", resourceCulture);
        internal static string TXT_VIEWDISCIPLINE_ARCHITECTURAL => ResourceManager.GetString("TXT_VIEWDISCIPLINE_ARCHITECTURAL", resourceCulture);
        internal static string TXT_VIEWDISCIPLINE_COORDINATION => ResourceManager.GetString("TXT_VIEWDISCIPLINE_COORDINATION", resourceCulture);
        internal static string TXT_VIEWDISCIPLINE_ELECTRICAL => ResourceManager.GetString("TXT_VIEWDISCIPLINE_ELECTRICAL", resourceCulture);
        internal static string TXT_VIEWDISCIPLINE_MECHANICAL => ResourceManager.GetString("TXT_VIEWDISCIPLINE_MECHANICAL", resourceCulture);
        internal static string TXT_VIEWDISCIPLINE_PLUMBING => ResourceManager.GetString("TXT_VIEWDISCIPLINE_PLUMBING", resourceCulture);
        internal static string TXT_VIEWDISCIPLINE_STRUCTURAL => ResourceManager.GetString("TXT_VIEWDISCIPLINE_STRUCTURAL", resourceCulture);
        internal static string DLG_CANCEL => ResourceManager.GetString("DLG_CANCEL", resourceCulture);
        internal static string DLG_OK => ResourceManager.GetString("DLG_OK", resourceCulture);
        internal static string GRP_VIEWSETTINGS => ResourceManager.GetString("GRP_VIEWSETTINGS", resourceCulture);
        internal static string LBL_SCALE => ResourceManager.GetString("LBL_SCALE", resourceCulture);
        internal static string LBL_VIEWTYPE => ResourceManager.GetString("LBL_VIEWTYPE", resourceCulture);
        internal static string TIP_SCALE => ResourceManager.GetString("TIP_SCALE", resourceCulture);
        internal static string TIP_VIEWTYPE => ResourceManager.GetString("TIP_VIEWTYPE", resourceCulture);
        internal static string GRP_TRIMBASE => ResourceManager.GetString("GRP_TRIMBASE", resourceCulture);
        internal static string RBN_TRIMLEVEL => ResourceManager.GetString("RBN_TRIMLEVEL", resourceCulture);
        internal static string RBN_TRIMVOL => ResourceManager.GetString("RBN_TRIMVOL", resourceCulture);
        internal static string TIP_TRIMVOL => ResourceManager.GetString("TIP_TRIMVOL", resourceCulture);
        internal static string GRP_CROPEXTEND => ResourceManager.GetString("GRP_CROPEXTEND", resourceCulture);
        internal static string LBL_TOPBOTTOM => ResourceManager.GetString("LBL_TOPBOTTOM", resourceCulture);
        internal static string LBL_LEFTRIGHT => ResourceManager.GetString("LBL_LEFTRIGHT", resourceCulture);
        internal static string TIP_TOPBOTTOM => ResourceManager.GetString("TIP_TOPBOTTOM", resourceCulture);
        internal static string TIP_LEFTRIGHT => ResourceManager.GetString("TIP_LEFTRIGHT", resourceCulture);
        internal static string GRP_ROOMS => ResourceManager.GetString("GRP_ROOMS", resourceCulture);
        internal static string BTN_SELECTALL => ResourceManager.GetString("BTN_SELECTALL", resourceCulture);
        internal static string BTN_CLEARALL => ResourceManager.GetString("BTN_CLEARALL", resourceCulture);
        internal static string TIP_ROOMS => ResourceManager.GetString("TIP_ROOMS", resourceCulture);
        internal static string GRP_DIMSTYLE => ResourceManager.GetString("GRP_DIMSTYLE", resourceCulture);
        internal static string LBL_DIMLEVEL => ResourceManager.GetString("LBL_DIMLEVEL", resourceCulture);
        internal static string LBL_DIMGRID => ResourceManager.GetString("LBL_DIMGRID", resourceCulture);
        internal static string PROC_INFO => ResourceManager.GetString("PROC_INFO", resourceCulture);
        internal static string BTN_START => ResourceManager.GetString("BTN_START", resourceCulture);
        internal static string BTN_STOP => ResourceManager.GetString("BTN_STOP", resourceCulture);
    }
}
