//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.JExtRAC.AutoCreateRoomView.Resources
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADSK.JExtRAC.AutoCreateRoomView.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static string IDS_ERR_ROOM_NOT_ENCLOSED => ResourceManager.GetString("IDS_ERR_ROOM_NOT_ENCLOSED", resourceCulture);
        internal static string IDS_TXT_APPLY => ResourceManager.GetString("IDS_TXT_APPLY", resourceCulture);
        internal static string IDS_TXT_CANCEL => ResourceManager.GetString("IDS_TXT_CANCEL", resourceCulture);
        internal static string IDS_TXT_CEILING_PER_ROOM => ResourceManager.GetString("IDS_TXT_CEILING_PER_ROOM", resourceCulture);
        internal static string IDS_TXT_CEILING_PLAN => ResourceManager.GetString("IDS_TXT_CEILING_PLAN", resourceCulture);
        internal static string IDS_TXT_COPY => ResourceManager.GetString("IDS_TXT_COPY", resourceCulture);
        internal static string IDS_TXT_COPY_CREATE => ResourceManager.GetString("IDS_TXT_COPY_CREATE", resourceCulture);
        internal static string IDS_TXT_DUPLICATE_NAME => ResourceManager.GetString("IDS_TXT_DUPLICATE_NAME", resourceCulture);
        internal static string IDS_TXT_FLOOR_PER_ROOM => ResourceManager.GetString("IDS_TXT_FLOOR_PER_ROOM", resourceCulture);
        internal static string IDS_TXT_FLOOR_PLAN => ResourceManager.GetString("IDS_TXT_FLOOR_PLAN", resourceCulture);
        internal static string IDS_TXT_FORM_TITLE => ResourceManager.GetString("IDS_TXT_FORM_TITLE", resourceCulture);
        internal static string IDS_TXT_LEVEL => ResourceManager.GetString("IDS_TXT_LEVEL", resourceCulture);
        internal static string IDS_TXT_MANAGE_TEMPLATES => ResourceManager.GetString("IDS_TXT_MANAGE_TEMPLATES", resourceCulture);
        internal static string IDS_TXT_MM => ResourceManager.GetString("IDS_TXT_MM", resourceCulture);
        internal static string IDS_TXT_NONE_TEMPLATE => ResourceManager.GetString("IDS_TXT_NONE_TEMPLATE", resourceCulture);
        internal static string IDS_TXT_NO_ROOM_NAME => ResourceManager.GetString("IDS_TXT_NO_ROOM_NAME", resourceCulture);
        internal static string IDS_TXT_OK => ResourceManager.GetString("IDS_TXT_OK", resourceCulture);
        internal static string IDS_TXT_OFFSET => ResourceManager.GetString("IDS_TXT_OFFSET", resourceCulture);
        internal static string IDS_TXT_OVERWRITE => ResourceManager.GetString("IDS_TXT_OVERWRITE", resourceCulture);
        internal static string IDS_TXT_RECTANGLE => ResourceManager.GetString("IDS_TXT_RECTANGLE", resourceCulture);
        internal static string IDS_TXT_ROOMNAME => ResourceManager.GetString("IDS_TXT_ROOMNAME", resourceCulture);
        internal static string IDS_TXT_ROOM_BOUNDARY => ResourceManager.GetString("IDS_TXT_ROOM_BOUNDARY", resourceCulture);
        internal static string IDS_TXT_ROOM_SHAPE => ResourceManager.GetString("IDS_TXT_ROOM_SHAPE", resourceCulture);
        internal static string IDS_TXT_ROOM_TAG => ResourceManager.GetString("IDS_TXT_ROOM_TAG", resourceCulture);
        internal static string IDS_TXT_SELECT_VIEW_CATEGORY => ResourceManager.GetString("IDS_TXT_SELECT_VIEW_CATEGORY", resourceCulture);
        internal static string IDS_TXT_SHAPE => ResourceManager.GetString("IDS_TXT_SHAPE", resourceCulture);
        internal static string IDS_TXT_SKIP => ResourceManager.GetString("IDS_TXT_SKIP", resourceCulture);
        internal static string IDS_TXT_TAG => ResourceManager.GetString("IDS_TXT_TAG", resourceCulture);
        internal static string IDS_TXT_TRIM => ResourceManager.GetString("IDS_TXT_TRIM", resourceCulture);
        internal static string IDS_TXT_TYPE_EDIT => ResourceManager.GetString("IDS_TXT_TYPE_EDIT", resourceCulture);
        internal static string IDS_TXT_VIEW_CATEGORY => ResourceManager.GetString("IDS_TXT_VIEW_CATEGORY", resourceCulture);
        internal static string IDS_TXT_VIEW_TEMPLATE => ResourceManager.GetString("IDS_TXT_VIEW_TEMPLATE", resourceCulture);
        internal static string IDS_TXT_VIEW_TYPE => ResourceManager.GetString("IDS_TXT_VIEW_TYPE", resourceCulture);
        internal static string IDS_TXT_WARNING => ResourceManager.GetString("IDS_TXT_WARNING", resourceCulture);
    }
}
