//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.JExtRAC.ParameterFilter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADSK.JExtRAC.ParameterFilter.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドが失敗しました.
        /// </summary>
        internal static string IDS_ERR_COMMAND {
            get {
                return ResourceManager.GetString("IDS_ERR_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string IDS_ERR_ERROR {
            get {
                return ResourceManager.GetString("IDS_ERR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値を0以上の整数に設定してください.
        /// </summary>
        internal static string IDS_ERR_GREATER0 {
            get {
                return ResourceManager.GetString("IDS_ERR_GREATER0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値は値上限以下の値を入力してください。.
        /// </summary>
        internal static string IDS_ERR_GREATERMAX {
            get {
                return ResourceManager.GetString("IDS_ERR_GREATERMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値は値下限以上の値を入力してください。.
        /// </summary>
        internal static string IDS_ERR_LESSMIN {
            get {
                return ResourceManager.GetString("IDS_ERR_LESSMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値上限は値下限以上の値を入力してください。.
        /// </summary>
        internal static string IDS_ERR_MINMAXVALUE {
            get {
                return ResourceManager.GetString("IDS_ERR_MINMAXVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要素を選択してください。.
        /// </summary>
        internal static string IDS_ERR_NOELEMENTSELECT {
            get {
                return ResourceManager.GetString("IDS_ERR_NOELEMENTSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値を0以上の整数に設定してください.
        /// </summary>
        internal static string IDS_ERR_NUMBERONLY {
            get {
                return ResourceManager.GetString("IDS_ERR_NUMBERONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パラメータの定義に失敗しました.
        /// </summary>
        internal static string IDS_ERR_PARAMDEF {
            get {
                return ResourceManager.GetString("IDS_ERR_PARAMDEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「&lt;&lt; 戻る」、「次へ &gt;&gt;」ボタンでタブ間に移動してください。.
        /// </summary>
        internal static string IDS_ERR_SELECTTAB {
            get {
                return ResourceManager.GetString("IDS_ERR_SELECTTAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RexJpn-LevelFilter.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_CMD {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RexJParam.txt.
        /// </summary>
        internal static string IDS_SHPARAM_FILE {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RexJpn.
        /// </summary>
        internal static string IDS_SHPARAM_GROUP {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string IDS_TXT_CANCEL {
            get {
                return ResourceManager.GetString("IDS_TXT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリ.
        /// </summary>
        internal static string IDS_TXT_CATEGORY {
            get {
                return ResourceManager.GetString("IDS_TXT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 個数.
        /// </summary>
        internal static string IDS_TXT_COUNT {
            get {
                return ResourceManager.GetString("IDS_TXT_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択総数.
        /// </summary>
        internal static string IDS_TXT_COUNTOBJECT {
            get {
                return ResourceManager.GetString("IDS_TXT_COUNTOBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択項目数.
        /// </summary>
        internal static string IDS_TXT_COUNTTYPE {
            get {
                return ResourceManager.GetString("IDS_TXT_COUNTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パラメータグループ一覧.
        /// </summary>
        internal static string IDS_TXT_DGVPARAMETERGROUP {
            get {
                return ResourceManager.GetString("IDS_TXT_DGVPARAMETERGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファミリ.
        /// </summary>
        internal static string IDS_TXT_FAMILY {
            get {
                return ResourceManager.GetString("IDS_TXT_FAMILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファミリタイプ.
        /// </summary>
        internal static string IDS_TXT_FAMILYTYPE {
            get {
                return ResourceManager.GetString("IDS_TXT_FAMILYTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パラメータフィルタ.
        /// </summary>
        internal static string IDS_TXT_FILTERFORM {
            get {
                return ResourceManager.GetString("IDS_TXT_FILTERFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次へ&gt;&gt;.
        /// </summary>
        internal static string IDS_TXT_NEXT {
            get {
                return ResourceManager.GetString("IDS_TXT_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string IDS_TXT_OK {
            get {
                return ResourceManager.GetString("IDS_TXT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ＜なし＞.
        /// </summary>
        internal static string IDS_TXT_OTHER {
            get {
                return ResourceManager.GetString("IDS_TXT_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パラメータ.
        /// </summary>
        internal static string IDS_TXT_PARAMETER {
            get {
                return ResourceManager.GetString("IDS_TXT_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パラメータグループ設定.
        /// </summary>
        internal static string IDS_TXT_PARAMETERGROUP {
            get {
                return ResourceManager.GetString("IDS_TXT_PARAMETERGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 適用.
        /// </summary>
        internal static string IDS_TXT_PNTCHECK {
            get {
                return ResourceManager.GetString("IDS_TXT_PNTCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;戻る.
        /// </summary>
        internal static string IDS_TXT_PREVIOUS {
            get {
                return ResourceManager.GetString("IDS_TXT_PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 読み込み中.
        /// </summary>
        internal static string IDS_TXT_PROGESSBAR {
            get {
                return ResourceManager.GetString("IDS_TXT_PROGESSBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全選択.
        /// </summary>
        internal static string IDS_TXT_SELECTALL {
            get {
                return ResourceManager.GetString("IDS_TXT_SELECTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択解除.
        /// </summary>
        internal static string IDS_TXT_SELECTCLEAR {
            get {
                return ResourceManager.GetString("IDS_TXT_SELECTCLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続部材一括選択.
        /// </summary>
        internal static string IDS_TXT_SELECTCONNECT {
            get {
                return ResourceManager.GetString("IDS_TXT_SELECTCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パラメータグループ設定.
        /// </summary>
        internal static string IDS_TXT_SETTINGPARAMETERGROUP {
            get {
                return ResourceManager.GetString("IDS_TXT_SETTINGPARAMETERGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値（ｍｍ）.
        /// </summary>
        internal static string IDS_TXT_VALUEPARAMETER {
            get {
                return ResourceManager.GetString("IDS_TXT_VALUEPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値上限（ｍｍ）.
        /// </summary>
        internal static string IDS_TXT_VALUEPARAMETERMAX {
            get {
                return ResourceManager.GetString("IDS_TXT_VALUEPARAMETERMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値下限（ｍｍ）.
        /// </summary>
        internal static string IDS_TXT_VALUEPARAMETERMIN {
            get {
                return ResourceManager.GetString("IDS_TXT_VALUEPARAMETERMIN", resourceCulture);
            }
        }
    }
}
