//------------------------------------------------------------------------------
// <auto-generated>
//     Strongly typed resources for SheetLayout (hand-maintained to match Text.resx).
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.ViewExtension.SheetLayout.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Text() { }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    var temp = new global::System.Resources.ResourceManager("ADSK.ViewExtension.SheetLayout.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string CMD_SHEETLAYOUT => ResourceManager.GetString(nameof(CMD_SHEETLAYOUT), resourceCulture);
        internal static string ERR_NOTVIEWSHEET => ResourceManager.GetString(nameof(ERR_NOTVIEWSHEET), resourceCulture);
        internal static string ERR_NOVIEWPORTSCHEDULE => ResourceManager.GetString(nameof(ERR_NOVIEWPORTSCHEDULE), resourceCulture);
        internal static string ERR_SELECTVIEW => ResourceManager.GetString(nameof(ERR_SELECTVIEW), resourceCulture);
        internal static string TXT_ERROR => ResourceManager.GetString(nameof(TXT_ERROR), resourceCulture);
        internal static string TXT_VIEWDISCIPLINE_ARCHITECTURAL => ResourceManager.GetString(nameof(TXT_VIEWDISCIPLINE_ARCHITECTURAL), resourceCulture);
        internal static string TXT_VIEWDISCIPLINE_COORDINATION => ResourceManager.GetString(nameof(TXT_VIEWDISCIPLINE_COORDINATION), resourceCulture);
        internal static string TXT_VIEWDISCIPLINE_ELECTRICAL => ResourceManager.GetString(nameof(TXT_VIEWDISCIPLINE_ELECTRICAL), resourceCulture);
        internal static string TXT_VIEWDISCIPLINE_MECHANICAL => ResourceManager.GetString(nameof(TXT_VIEWDISCIPLINE_MECHANICAL), resourceCulture);
        internal static string TXT_VIEWDISCIPLINE_PLUMBING => ResourceManager.GetString(nameof(TXT_VIEWDISCIPLINE_PLUMBING), resourceCulture);
        internal static string TXT_VIEWDISCIPLINE_STRUCTURAL => ResourceManager.GetString(nameof(TXT_VIEWDISCIPLINE_STRUCTURAL), resourceCulture);
        internal static string TXT_OK => ResourceManager.GetString(nameof(TXT_OK), resourceCulture);
        internal static string TXT_CANCEL => ResourceManager.GetString(nameof(TXT_CANCEL), resourceCulture);
        internal static string TXT_GRP_VIEWPORTS => ResourceManager.GetString(nameof(TXT_GRP_VIEWPORTS), resourceCulture);
        internal static string TXT_GRP_SCHEDULES => ResourceManager.GetString(nameof(TXT_GRP_SCHEDULES), resourceCulture);
        internal static string TXT_LABEL_VIEWPORTS_ON_SHEET => ResourceManager.GetString(nameof(TXT_LABEL_VIEWPORTS_ON_SHEET), resourceCulture);
        internal static string TXT_LABEL_SELECT_VIEWS => ResourceManager.GetString(nameof(TXT_LABEL_SELECT_VIEWS), resourceCulture);
        internal static string TXT_LABEL_ORDER_NEW_SHEET => ResourceManager.GetString(nameof(TXT_LABEL_ORDER_NEW_SHEET), resourceCulture);
        internal static string TXT_LABEL_DISCIPLINE => ResourceManager.GetString(nameof(TXT_LABEL_DISCIPLINE), resourceCulture);
        internal static string TXT_LABEL_VIEW_CATEGORY => ResourceManager.GetString(nameof(TXT_LABEL_VIEW_CATEGORY), resourceCulture);
        internal static string TXT_LABEL_VIEW_FAMILY_TYPE => ResourceManager.GetString(nameof(TXT_LABEL_VIEW_FAMILY_TYPE), resourceCulture);
        internal static string TXT_CHK_SAME_LEGEND => ResourceManager.GetString(nameof(TXT_CHK_SAME_LEGEND), resourceCulture);
        internal static string TXT_LABEL_SCHEDULES_ON_SHEET => ResourceManager.GetString(nameof(TXT_LABEL_SCHEDULES_ON_SHEET), resourceCulture);
        internal static string TXT_LABEL_SCHEDULES_TO_PLACE => ResourceManager.GetString(nameof(TXT_LABEL_SCHEDULES_TO_PLACE), resourceCulture);
        internal static string TXT_SCHEDULE_INFO => ResourceManager.GetString(nameof(TXT_SCHEDULE_INFO), resourceCulture);
        internal static string TXT_CREDIT => ResourceManager.GetString(nameof(TXT_CREDIT), resourceCulture);
        internal static string TXT_COL_ID => ResourceManager.GetString(nameof(TXT_COL_ID), resourceCulture);
        internal static string TXT_COL_SHEET => ResourceManager.GetString(nameof(TXT_COL_SHEET), resourceCulture);
        internal static string TXT_COL_NUMBER => ResourceManager.GetString(nameof(TXT_COL_NUMBER), resourceCulture);
        internal static string TXT_COL_NAME => ResourceManager.GetString(nameof(TXT_COL_NAME), resourceCulture);
        internal static string TXT_ALL => ResourceManager.GetString(nameof(TXT_ALL), resourceCulture);
        internal static string TXT_VT_ALL => ResourceManager.GetString(nameof(TXT_VT_ALL), resourceCulture);
        internal static string TXT_VT_AREA_PLAN => ResourceManager.GetString(nameof(TXT_VT_AREA_PLAN), resourceCulture);
        internal static string TXT_VT_CEILING_PLAN => ResourceManager.GetString(nameof(TXT_VT_CEILING_PLAN), resourceCulture);
        internal static string TXT_VT_COLUMN_SCHEDULE => ResourceManager.GetString(nameof(TXT_VT_COLUMN_SCHEDULE), resourceCulture);
        internal static string TXT_VT_COST_REPORT => ResourceManager.GetString(nameof(TXT_VT_COST_REPORT), resourceCulture);
        internal static string TXT_VT_DETAIL => ResourceManager.GetString(nameof(TXT_VT_DETAIL), resourceCulture);
        internal static string TXT_VT_DRAFTING_VIEW => ResourceManager.GetString(nameof(TXT_VT_DRAFTING_VIEW), resourceCulture);
        internal static string TXT_VT_DRAWING_SHEET => ResourceManager.GetString(nameof(TXT_VT_DRAWING_SHEET), resourceCulture);
        internal static string TXT_VT_ELEVATION => ResourceManager.GetString(nameof(TXT_VT_ELEVATION), resourceCulture);
        internal static string TXT_VT_ENGINEERING_PLAN => ResourceManager.GetString(nameof(TXT_VT_ENGINEERING_PLAN), resourceCulture);
        internal static string TXT_VT_FLOOR_PLAN => ResourceManager.GetString(nameof(TXT_VT_FLOOR_PLAN), resourceCulture);
        internal static string TXT_VT_INTERNAL => ResourceManager.GetString(nameof(TXT_VT_INTERNAL), resourceCulture);
        internal static string TXT_VT_LEGEND => ResourceManager.GetString(nameof(TXT_VT_LEGEND), resourceCulture);
        internal static string TXT_VT_LOADS_REPORT => ResourceManager.GetString(nameof(TXT_VT_LOADS_REPORT), resourceCulture);
        internal static string TXT_VT_PANEL_SCHEDULE => ResourceManager.GetString(nameof(TXT_VT_PANEL_SCHEDULE), resourceCulture);
        internal static string TXT_VT_PRESSURE_LOSS_REPORT => ResourceManager.GetString(nameof(TXT_VT_PRESSURE_LOSS_REPORT), resourceCulture);
        internal static string TXT_VT_PROJECT_BROWSER => ResourceManager.GetString(nameof(TXT_VT_PROJECT_BROWSER), resourceCulture);
        internal static string TXT_VT_RENDERING => ResourceManager.GetString(nameof(TXT_VT_RENDERING), resourceCulture);
        internal static string TXT_VT_REPORT => ResourceManager.GetString(nameof(TXT_VT_REPORT), resourceCulture);
        internal static string TXT_VT_SECTION => ResourceManager.GetString(nameof(TXT_VT_SECTION), resourceCulture);
        internal static string TXT_VT_SCHEDULE => ResourceManager.GetString(nameof(TXT_VT_SCHEDULE), resourceCulture);
        internal static string TXT_VT_SYSTEM_BROWSER => ResourceManager.GetString(nameof(TXT_VT_SYSTEM_BROWSER), resourceCulture);
        internal static string TXT_VT_THREE_D => ResourceManager.GetString(nameof(TXT_VT_THREE_D), resourceCulture);
        internal static string TXT_VT_UNDEFINED => ResourceManager.GetString(nameof(TXT_VT_UNDEFINED), resourceCulture);
        internal static string TXT_VT_WALKTHROUGH => ResourceManager.GetString(nameof(TXT_VT_WALKTHROUGH), resourceCulture);
    }
}
