//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.JExtRAC.JoinOrderInspector.Resources {

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADSK.JExtRAC.JoinOrderInspector.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string IDS_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("IDS_WINDOW_TITLE", resourceCulture);
            }
        }

        internal static string IDS_PICK_PROMPT {
            get {
                return ResourceManager.GetString("IDS_PICK_PROMPT", resourceCulture);
            }
        }

        internal static string IDS_CATEGORY_CUTTING {
            get {
                return ResourceManager.GetString("IDS_CATEGORY_CUTTING", resourceCulture);
            }
        }

        internal static string IDS_CATEGORY_SELECTED {
            get {
                return ResourceManager.GetString("IDS_CATEGORY_SELECTED", resourceCulture);
            }
        }

        internal static string IDS_CATEGORY_CUT_BY {
            get {
                return ResourceManager.GetString("IDS_CATEGORY_CUT_BY", resourceCulture);
            }
        }

        internal static string IDS_NONE {
            get {
                return ResourceManager.GetString("IDS_NONE", resourceCulture);
            }
        }

        internal static string IDS_NO_SELECTION {
            get {
                return ResourceManager.GetString("IDS_NO_SELECTION", resourceCulture);
            }
        }

        internal static string IDS_ERROR_PREFIX {
            get {
                return ResourceManager.GetString("IDS_ERROR_PREFIX", resourceCulture);
            }
        }

        internal static string IDS_LEGEND_SELECTED {
            get {
                return ResourceManager.GetString("IDS_LEGEND_SELECTED", resourceCulture);
            }
        }

        internal static string IDS_LEGEND_CUTTING {
            get {
                return ResourceManager.GetString("IDS_LEGEND_CUTTING", resourceCulture);
            }
        }

        internal static string IDS_LEGEND_CUT_BY {
            get {
                return ResourceManager.GetString("IDS_LEGEND_CUT_BY", resourceCulture);
            }
        }

        internal static string IDS_BTN_REANALYZE {
            get {
                return ResourceManager.GetString("IDS_BTN_REANALYZE", resourceCulture);
            }
        }
    }
}
