//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SectionListSteel.Utils ;

namespace SectionListSteel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Image {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Image() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SectionListSteel.Resources.Image", typeof(Image).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help_24x24 {
            get {
                // object obj = ResourceManager.GetObject("help_24x24", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.help_24x24.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_ADDPARAMETER_CANTIGIRDER_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_ADDPARAMETER_CANTIGIRDER_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.help_24x24.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_ADDPARAMETER_CFTRECTCOLUMN_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_ADDPARAMETER_CFTRECTCOLUMN_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_ADDPARAMETER_CFTRECTCOLUMN_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_ADDPARAMETER_CFTROUNDCOLUMN_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_ADDPARAMETER_CFTROUNDCOLUMN_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_ADDPARAMETER_CFTROUNDCOLUMN_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_ADDPARAMETER_GIRDER_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_ADDPARAMETER_GIRDER_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_ADDPARAMETER_GIRDER_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_ADDPARAMETER_HCOLUMN_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_ADDPARAMETER_HCOLUMN_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_ADDPARAMETER_HCOLUMN_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_ADDPARAMETER_RECTCOLUMN_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_ADDPARAMETER_RECTCOLUMN_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_ADDPARAMETER_RECTCOLUMN_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_ADDPARAMETER_ROUNDCOLUMN_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_ADDPARAMETER_ROUNDCOLUMN_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_ADDPARAMETER_ROUNDCOLUMN_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_BEAMLIST_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_BEAMLIST_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_BEAMLIST_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_BEAMLIST_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_BEAMLIST_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._16x16.IDI_BTN_BEAMLIST_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_BRACELIST_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_BRACELIST_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_BRACELIST_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_BRACELIST_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_BRACELIST_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._16x16.IDI_BTN_BRACELIST_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_COLUMNLIST_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_COLUMNLIST_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_COLUMNLIST_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_COLUMNLIST_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_COLUMNLIST_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._16x16.IDI_BTN_COLUMNLIST_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_COLUMNSETTING_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_COLUMNSETTING_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_COLUMNSETTING_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_COLUMNSETTING_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_COLUMNSETTING_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._16x16.IDI_BTN_COLUMNSETTING_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_COMMONSETTING_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_COMMONSETTING_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_COMMONSETTING_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_COMMONSETTING_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_COMMONSETTING_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._16x16.IDI_BTN_COMMONSETTING_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_GIRDERLIST_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_GIRDERLIST_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_GIRDERLIST_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_GIRDERLIST_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_GIRDERLIST_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._16x16.IDI_BTN_GIRDERLIST_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_GIRDERSETTING_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_GIRDERSETTING_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_GIRDERSETTING_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_GIRDERSETTING_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_GIRDERSETTING_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._16x16.IDI_BTN_GIRDERSETTING_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_LEVELSORTORDER_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_LEVELSORTORDER_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_LEVELSORTORDER_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_LEVELSORTORDER_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_LEVELSORTORDER_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._16x16.IDI_BTN_LEVELSORTORDER_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_LIST_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_LIST_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_LIST_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_LIST_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_LIST_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._16x16.IDI_BTN_LIST_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_LISTBEAM_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_LISTBEAM_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_LISTBEAM_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_LISTBEAM_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_LISTBEAM_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._16x16.IDI_BTN_LISTBEAM_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_LISTCOLUMN_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_LISTCOLUMN_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_LISTCOLUMN_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_LISTCOLUMN_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_LISTCOLUMN_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._16x16.IDI_BTN_LISTCOLUMN_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_LISTPOST_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_LISTPOST_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_LISTPOST_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_LISTPOST_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_LISTPOST_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._16x16.IDI_BTN_LISTPOST_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_PARAMETERMAPPING_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_PARAMETERMAPPING_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_PARAMETERMAPPING_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_PARAMETERMAPPING_S {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_PARAMETERMAPPING_S", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._16x16.IDI_BTN_PARAMETERMAPPING_S.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_BTN_SHOWMANUAL_L {
            get {
                // object obj = ResourceManager.GetObject("IDI_BTN_SHOWMANUAL_L", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources._32x32.IDI_BTN_SHOWMANUAL_L.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_1TITLE {
            get {
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_1TITLE.png" ) ;
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_1TITLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_2TITLE {
            get {
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_2TITLE.png" ) ;
                //object obj = ResourceManager.GetObject("IDI_FORMIMAGE_2TITLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_BEAMFRAME {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_BEAMFRAME", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_BEAMFRAME.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_BEAMFRAME_SUB {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_BEAMFRAME_SUB", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_BEAMFRAME_SUB.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_BRACEFRAME {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_BRACEFRAME", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_BRACEFRAME.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_COLUMNFRAME {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_COLUMNFRAME", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_COLUMNFRAME.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_COLUMNFRAME_POST {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_COLUMNFRAME_POST", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_COLUMNFRAME_POST.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_HELP_BEAMMATERIAL {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_HELP_BEAMMATERIAL", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_HELP_BEAMMATERIAL.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_HELP_BEAMMATERIAL_SUB {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_HELP_BEAMMATERIAL_SUB", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_HELP_BEAMMATERIAL_SUB.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_HELP_BRACEMATERIAL {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_HELP_BRACEMATERIAL", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_HELP_BRACEMATERIAL.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_HELP_COLUMNMATERIAL {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_HELP_COLUMNMATERIAL", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_HELP_COLUMNMATERIAL.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_HELP_COLUMNMATERIAL_POST {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_HELP_COLUMNMATERIAL_POST", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_HELP_COLUMNMATERIAL_POST.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_SUBTITLE {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_SUBTITLE", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_SUBTITLE.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
