//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.JExtRAC.ExcelImageInsert.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADSK.JExtRAC.ExcelImageInsert.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to コマンドが失敗しました.
        /// </summary>
        internal static string IDS_ERR_COMMAND {
            get {
                return ResourceManager.GetString("IDS_ERR_COMMAND", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Excelのセルを選択してください.
        /// </summary>
        internal static string IDS_ERR_EXCELRANGESELECT {
            get {
                return ResourceManager.GetString("IDS_ERR_EXCELRANGESELECT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to イメージファイルの取り込みに失敗しました.
        /// </summary>
        internal static string IDS_ERR_IMPIMAGEFILE {
            get {
                return ResourceManager.GetString("IDS_ERR_IMPIMAGEFILE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to クリップボード設定に失敗しました.
        /// </summary>
        internal static string IDS_ERR_SETCLIPBOARD {
            get {
                return ResourceManager.GetString("IDS_ERR_SETCLIPBOARD", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Excelを起動してください.
        /// </summary>
        internal static string IDS_ERR_STARTEXCEL {
            get {
                return ResourceManager.GetString("IDS_ERR_STARTEXCEL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ExcelImage.bmp.
        /// </summary>
        internal static string IDS_TXT_IMAGEFILENAME {
            get {
                return ResourceManager.GetString("IDS_TXT_IMAGEFILENAME", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Excel画像挿入.
        /// </summary>
        internal static string IDS_TRANSACTION_GROUP {
            get {
                return ResourceManager.GetString("IDS_TRANSACTION_GROUP", resourceCulture);
            }
        }
    }
}
