//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace ADSK.ViewExtension.ViewDuplicate.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                    resourceMan = new global::System.Resources.ResourceManager("ADSK.ViewExtension.ViewDuplicate.Resources.Text", typeof(Text).Assembly);
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string BTN_ADD => ResourceManager.GetString(nameof(BTN_ADD), resourceCulture);
        public static string BTN_CANCEL => ResourceManager.GetString(nameof(BTN_CANCEL), resourceCulture);
        public static string BTN_DELETE => ResourceManager.GetString(nameof(BTN_DELETE), resourceCulture);
        public static string CMD_VIEWDUPLICATE => ResourceManager.GetString(nameof(CMD_VIEWDUPLICATE), resourceCulture);
        public static string DGCOL_ADDED_TEXT => ResourceManager.GetString(nameof(DGCOL_ADDED_TEXT), resourceCulture);
        public static string DGCOL_PREFIX_SUFFIX => ResourceManager.GetString(nameof(DGCOL_PREFIX_SUFFIX), resourceCulture);
        public static string DGCOL_VIEW_TEMPLATE => ResourceManager.GetString(nameof(DGCOL_VIEW_TEMPLATE), resourceCulture);
        public static string DGCOL_VIEW_TYPE => ResourceManager.GetString(nameof(DGCOL_VIEW_TYPE), resourceCulture);
        public static string DUP_MODE_DUPLICATE => ResourceManager.GetString(nameof(DUP_MODE_DUPLICATE), resourceCulture);
        public static string DUP_MODE_WITH_DETAILING => ResourceManager.GetString(nameof(DUP_MODE_WITH_DETAILING), resourceCulture);
        public static string ERR_CANNOTCOPY => ResourceManager.GetString(nameof(ERR_CANNOTCOPY), resourceCulture);
        public static string ERR_FIELD_EMPTY => ResourceManager.GetString(nameof(ERR_FIELD_EMPTY), resourceCulture);
        public static string ERR_INPUTCOPYRULE => ResourceManager.GetString(nameof(ERR_INPUTCOPYRULE), resourceCulture);
        public static string ERR_SELECTROW => ResourceManager.GetString(nameof(ERR_SELECTROW), resourceCulture);
        public static string ERR_SELECTTARGETVIEW => ResourceManager.GetString(nameof(ERR_SELECTTARGETVIEW), resourceCulture);
        public static string GP_ADD_STRING => ResourceManager.GetString(nameof(GP_ADD_STRING), resourceCulture);
        public static string LBL_CREDIT => ResourceManager.GetString(nameof(LBL_CREDIT), resourceCulture);
        public static string LBL_DISCIPLINE => ResourceManager.GetString(nameof(LBL_DISCIPLINE), resourceCulture);
        public static string LBL_DUP_KIND => ResourceManager.GetString(nameof(LBL_DUP_KIND), resourceCulture);
        public static string LBL_ITEM_VIEW_TEMPLATE => ResourceManager.GetString(nameof(LBL_ITEM_VIEW_TEMPLATE), resourceCulture);
        public static string LBL_ITEM_VIEW_TYPE => ResourceManager.GetString(nameof(LBL_ITEM_VIEW_TYPE), resourceCulture);
        public static string LBL_VIEW_CATEGORY => ResourceManager.GetString(nameof(LBL_VIEW_CATEGORY), resourceCulture);
        public static string LBL_VIEW_TYPE_FILTER => ResourceManager.GetString(nameof(LBL_VIEW_TYPE_FILTER), resourceCulture);
        public static string TXT_CANNOTCOPYVIEW => ResourceManager.GetString(nameof(TXT_CANNOTCOPYVIEW), resourceCulture);
        public static string TXT_ERROR => ResourceManager.GetString(nameof(TXT_ERROR), resourceCulture);
        public static string TXT_LEFTBRACE => ResourceManager.GetString(nameof(TXT_LEFTBRACE), resourceCulture);
        public static string TXT_PREFIX => ResourceManager.GetString(nameof(TXT_PREFIX), resourceCulture);
        public static string TXT_RIGHTBRACE => ResourceManager.GetString(nameof(TXT_RIGHTBRACE), resourceCulture);
        public static string TXT_SUFFIX => ResourceManager.GetString(nameof(TXT_SUFFIX), resourceCulture);
        public static string TXT_VIEWDISCIPLINE_ARCHITECTURAL => ResourceManager.GetString(nameof(TXT_VIEWDISCIPLINE_ARCHITECTURAL), resourceCulture);
        public static string TXT_VIEWDISCIPLINE_COORDINATION => ResourceManager.GetString(nameof(TXT_VIEWDISCIPLINE_COORDINATION), resourceCulture);
        public static string TXT_VIEWDISCIPLINE_ELECTRICAL => ResourceManager.GetString(nameof(TXT_VIEWDISCIPLINE_ELECTRICAL), resourceCulture);
        public static string TXT_VIEWDISCIPLINE_MECHANICAL => ResourceManager.GetString(nameof(TXT_VIEWDISCIPLINE_MECHANICAL), resourceCulture);
        public static string TXT_VIEWDISCIPLINE_PLUMBING => ResourceManager.GetString(nameof(TXT_VIEWDISCIPLINE_PLUMBING), resourceCulture);
        public static string TXT_VIEWDISCIPLINE_STRUCTURAL => ResourceManager.GetString(nameof(TXT_VIEWDISCIPLINE_STRUCTURAL), resourceCulture);
        public static string TXT_VIEWFAMILY_ALL => ResourceManager.GetString(nameof(TXT_VIEWFAMILY_ALL), resourceCulture);
        public static string TXT_VIEWTYPE_ALL => ResourceManager.GetString(nameof(TXT_VIEWTYPE_ALL), resourceCulture);
        public static string TXT_VIEWTYPE_AREA_PLAN => ResourceManager.GetString(nameof(TXT_VIEWTYPE_AREA_PLAN), resourceCulture);
        public static string TXT_VIEWTYPE_CEILING_PLAN => ResourceManager.GetString(nameof(TXT_VIEWTYPE_CEILING_PLAN), resourceCulture);
        public static string TXT_VIEWTYPE_COLUMN_SCHEDULE => ResourceManager.GetString(nameof(TXT_VIEWTYPE_COLUMN_SCHEDULE), resourceCulture);
        public static string TXT_VIEWTYPE_COST_REPORT => ResourceManager.GetString(nameof(TXT_VIEWTYPE_COST_REPORT), resourceCulture);
        public static string TXT_VIEWTYPE_DETAIL => ResourceManager.GetString(nameof(TXT_VIEWTYPE_DETAIL), resourceCulture);
        public static string TXT_VIEWTYPE_DRAFTING_VIEW => ResourceManager.GetString(nameof(TXT_VIEWTYPE_DRAFTING_VIEW), resourceCulture);
        public static string TXT_VIEWTYPE_DRAWING_SHEET => ResourceManager.GetString(nameof(TXT_VIEWTYPE_DRAWING_SHEET), resourceCulture);
        public static string TXT_VIEWTYPE_ELEVATION => ResourceManager.GetString(nameof(TXT_VIEWTYPE_ELEVATION), resourceCulture);
        public static string TXT_VIEWTYPE_ENGINEERING_PLAN => ResourceManager.GetString(nameof(TXT_VIEWTYPE_ENGINEERING_PLAN), resourceCulture);
        public static string TXT_VIEWTYPE_FLOOR_PLAN => ResourceManager.GetString(nameof(TXT_VIEWTYPE_FLOOR_PLAN), resourceCulture);
        public static string TXT_VIEWTYPE_INTERNAL => ResourceManager.GetString(nameof(TXT_VIEWTYPE_INTERNAL), resourceCulture);
        public static string TXT_VIEWTYPE_LEGEND => ResourceManager.GetString(nameof(TXT_VIEWTYPE_LEGEND), resourceCulture);
        public static string TXT_VIEWTYPE_LOADS_REPORT => ResourceManager.GetString(nameof(TXT_VIEWTYPE_LOADS_REPORT), resourceCulture);
        public static string TXT_VIEWTYPE_PANEL_SCHEDULE => ResourceManager.GetString(nameof(TXT_VIEWTYPE_PANEL_SCHEDULE), resourceCulture);
        public static string TXT_VIEWTYPE_PRESSURE_LOSS_REPORT => ResourceManager.GetString(nameof(TXT_VIEWTYPE_PRESSURE_LOSS_REPORT), resourceCulture);
        public static string TXT_VIEWTYPE_PROJECT_BROWSER => ResourceManager.GetString(nameof(TXT_VIEWTYPE_PROJECT_BROWSER), resourceCulture);
        public static string TXT_VIEWTYPE_RENDERING => ResourceManager.GetString(nameof(TXT_VIEWTYPE_RENDERING), resourceCulture);
        public static string TXT_VIEWTYPE_REPORT => ResourceManager.GetString(nameof(TXT_VIEWTYPE_REPORT), resourceCulture);
        public static string TXT_VIEWTYPE_SECTION => ResourceManager.GetString(nameof(TXT_VIEWTYPE_SECTION), resourceCulture);
        public static string TXT_VIEWTYPE_SCHEDULE => ResourceManager.GetString(nameof(TXT_VIEWTYPE_SCHEDULE), resourceCulture);
        public static string TXT_VIEWTYPE_SYSTEM_BROWSER => ResourceManager.GetString(nameof(TXT_VIEWTYPE_SYSTEM_BROWSER), resourceCulture);
        public static string TXT_VIEWTYPE_THREE_D => ResourceManager.GetString(nameof(TXT_VIEWTYPE_THREE_D), resourceCulture);
        public static string TXT_VIEWTYPE_UNDEFINED => ResourceManager.GetString(nameof(TXT_VIEWTYPE_UNDEFINED), resourceCulture);
        public static string TXT_VIEWTYPE_WALKTHROUGH => ResourceManager.GetString(nameof(TXT_VIEWTYPE_WALKTHROUGH), resourceCulture);
    }
}
