//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SectionListSteel.Utils ;

namespace SectionListSteel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SectionListSteel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help_24x24 {
            get {
                // object obj = ResourceManager.GetObject("help_24x24", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.help_24x24.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_1TITLE {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_1TITLE", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_1TITLE.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_2TITLE {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_2TITLE", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_2TITLE.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_BEAMFRAME {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_BEAMFRAME", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_BEAMFRAME.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_BEAMFRAME_SUB {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_BEAMFRAME_SUB", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_BEAMFRAME_SUB.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_BRACEFRAME {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_BRACEFRAME", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_BRACEFRAME.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_COLUMNFRAME {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_COLUMNFRAME", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_COLUMNFRAME_POST.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_COLUMNFRAME_POST {
            get {
                // object obj = ResourceManager.GetObject("IDI_FORMIMAGE_COLUMNFRAME_POST", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_COLUMNFRAME_POST.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDI_FORMIMAGE_SUBTITLE {
            get {
                //object obj = ResourceManager.GetObject("IDI_FORMIMAGE_SUBTITLE", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListSteel.Resources.FormImage.IDI_FORMIMAGE_SUBTITLE.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
