//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.JExtRAC.LayoutInstanceInRegion.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class for localized strings.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADSK.JExtRAC.LayoutInstanceInRegion.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture for all resource lookups.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string ButtonClose => ResourceManager.GetString(nameof(ButtonClose), resourceCulture);

        internal static string ButtonPickObject => ResourceManager.GetString(nameof(ButtonPickObject), resourceCulture);

        internal static string ButtonPickRegion => ResourceManager.GetString(nameof(ButtonPickRegion), resourceCulture);

        internal static string ButtonPlace => ResourceManager.GetString(nameof(ButtonPlace), resourceCulture);

        internal static string ButtonPlaceAndClose => ResourceManager.GetString(nameof(ButtonPlaceAndClose), resourceCulture);

        internal static string ButtonTwoPointPick => ResourceManager.GetString(nameof(ButtonTwoPointPick), resourceCulture);

        internal static string CheckDeleteOutside => ResourceManager.GetString(nameof(CheckDeleteOutside), resourceCulture);

        internal static string DialogWarning => ResourceManager.GetString(nameof(DialogWarning), resourceCulture);

        internal static string FilterRoom => ResourceManager.GetString(nameof(FilterRoom), resourceCulture);

        internal static string FilterSpace => ResourceManager.GetString(nameof(FilterSpace), resourceCulture);

        internal static string FormTitle => ResourceManager.GetString(nameof(FormTitle), resourceCulture);

        internal static string GroupPlacementFamily => ResourceManager.GetString(nameof(GroupPlacementFamily), resourceCulture);

        internal static string GroupPlacementPosition => ResourceManager.GetString(nameof(GroupPlacementPosition), resourceCulture);

        internal static string GroupPlacementSettings => ResourceManager.GetString(nameof(GroupPlacementSettings), resourceCulture);

        internal static string GroupPreview => ResourceManager.GetString(nameof(GroupPreview), resourceCulture);

        internal static string LabelAxisAngle => ResourceManager.GetString(nameof(LabelAxisAngle), resourceCulture);

        internal static string LabelBack => ResourceManager.GetString(nameof(LabelBack), resourceCulture);

        internal static string LabelCategory => ResourceManager.GetString(nameof(LabelCategory), resourceCulture);

        internal static string LabelFamily => ResourceManager.GetString(nameof(LabelFamily), resourceCulture);

        internal static string LabelFamilyAngle => ResourceManager.GetString(nameof(LabelFamilyAngle), resourceCulture);

        internal static string LabelFront => ResourceManager.GetString(nameof(LabelFront), resourceCulture);

        internal static string LabelLeft => ResourceManager.GetString(nameof(LabelLeft), resourceCulture);

        internal static string LabelMargin => ResourceManager.GetString(nameof(LabelMargin), resourceCulture);

        internal static string LabelMethod => ResourceManager.GetString(nameof(LabelMethod), resourceCulture);

        internal static string LabelNotSelected => ResourceManager.GetString(nameof(LabelNotSelected), resourceCulture);

        internal static string LabelNotSpecified => ResourceManager.GetString(nameof(LabelNotSpecified), resourceCulture);

        internal static string LabelOffsetFromLevel => ResourceManager.GetString(nameof(LabelOffsetFromLevel), resourceCulture);

        internal static string LabelPlacementPattern => ResourceManager.GetString(nameof(LabelPlacementPattern), resourceCulture);

        internal static string LabelRight => ResourceManager.GetString(nameof(LabelRight), resourceCulture);

        internal static string LabelSelected => ResourceManager.GetString(nameof(LabelSelected), resourceCulture);

        internal static string LabelSpecified => ResourceManager.GetString(nameof(LabelSpecified), resourceCulture);

        internal static string LabelType => ResourceManager.GetString(nameof(LabelType), resourceCulture);

        internal static string LabelUnit => ResourceManager.GetString(nameof(LabelUnit), resourceCulture);

        internal static string MsgInvalidInput => ResourceManager.GetString(nameof(MsgInvalidInput), resourceCulture);

        internal static string MsgPickEndPoint => ResourceManager.GetString(nameof(MsgPickEndPoint), resourceCulture);

        internal static string MsgPickStartPoint => ResourceManager.GetString(nameof(MsgPickStartPoint), resourceCulture);

        internal static string MsgPointsTooClose => ResourceManager.GetString(nameof(MsgPointsTooClose), resourceCulture);

        internal static string MsgViewTypeError => ResourceManager.GetString(nameof(MsgViewTypeError), resourceCulture);

        internal static string MsgXDirectionError => ResourceManager.GetString(nameof(MsgXDirectionError), resourceCulture);

        internal static string MsgXIntervalMinError => ResourceManager.GetString(nameof(MsgXIntervalMinError), resourceCulture);

        internal static string MsgYDirectionError => ResourceManager.GetString(nameof(MsgYDirectionError), resourceCulture);

        internal static string MsgYIntervalMinError => ResourceManager.GetString(nameof(MsgYIntervalMinError), resourceCulture);

        internal static string ParamBaseOffset => ResourceManager.GetString(nameof(ParamBaseOffset), resourceCulture);

        internal static string ParamTopOffset => ResourceManager.GetString(nameof(ParamTopOffset), resourceCulture);

        internal static string PatternEqualSpacing => ResourceManager.GetString(nameof(PatternEqualSpacing), resourceCulture);

        internal static string PatternRatio121 => ResourceManager.GetString(nameof(PatternRatio121), resourceCulture);

        internal static string RadioCountBased => ResourceManager.GetString(nameof(RadioCountBased), resourceCulture);

        internal static string RadioIntervalBased => ResourceManager.GetString(nameof(RadioIntervalBased), resourceCulture);

        internal static string RadioRegionSelection => ResourceManager.GetString(nameof(RadioRegionSelection), resourceCulture);

        internal static string RadioSelectObject => ResourceManager.GetString(nameof(RadioSelectObject), resourceCulture);

        internal static string TransactionArrayLayout => ResourceManager.GetString(nameof(TransactionArrayLayout), resourceCulture);

        internal static string TransactionDeleteLine => ResourceManager.GetString(nameof(TransactionDeleteLine), resourceCulture);

        internal static string TransactionOffset => ResourceManager.GetString(nameof(TransactionOffset), resourceCulture);

        internal static string TransactionRotateFamily => ResourceManager.GetString(nameof(TransactionRotateFamily), resourceCulture);
    }
}
