<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <OutputType>Library</OutputType>
    <UseWpf>true</UseWpf>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>ADSK.JExtRAC.ValueCopy</RootNamespace>
    <AssemblyName>ADSK.JExtRAC.ValueCopy</AssemblyName>
    <SatelliteResourceLanguages>ja;en</SatelliteResourceLanguages>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Configurations>Debug 2027;Release 2027</Configurations>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug 2027|x64'">
    <DebugSymbols>true</DebugSymbols>
    <DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release 2027|x64'">
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>C:\Program Files\Autodesk\Revit 2027\RevitAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>C:\Program Files\Autodesk\Revit 2027\RevitAPIUI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Text.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Text.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Text.en.resx" />
    <EmbeddedResource Update="Resources\Image.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Image.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Images\IDI_SUBS_ICON.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="UI\FormReport.cs" />
    <Compile Remove="UI\FormReport.Designer.cs" />
    <Compile Remove="UI\FormParameter.cs" />
    <Compile Remove="UI\FormParameter.Designer.cs" />
    <Compile Remove="UI\FormLog.cs" />
    <Compile Remove="UI\FormLog.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="UI\FormReport.resx" />
    <EmbeddedResource Remove="UI\FormParameter.resx" />
    <EmbeddedResource Remove="UI\FormLog.resx" />
  </ItemGroup>

  <ItemGroup>
    <None Include="ADSK.JExtRAC.ValueCopy.addin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Images\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
