'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports ADSK.MepVerticalMark.Res

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ADSK.MepVerticalMark.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  矢羽ダクト作成 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CMD_VERTICAL_DUCT() As String
            Get
                Return ResourceManager.GetString("CMD_VERTICAL_DUCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  矢羽配管作成 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CMD_VERTICALMARK() As String
            Get
                Return ResourceManager.GetString("CMD_VERTICALMARK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property ICON_LARGE_YABANE_DUCT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_LARGE_YABANE_DUCT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property ICON_LARGE_YABANE_PIPE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_LARGE_YABANE_PIPE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property ICON_SMALL_YABANE_DUCT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_SMALL_YABANE_DUCT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property ICON_SMALL_YABANE_PIPE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_SMALL_YABANE_PIPE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  矢羽ツール に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_BTN_PANELNAME() As String
            Get
                Return ResourceManager.GetString("IDS_BTN_PANELNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  JP設備 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_BTN_TABNAME_OLD() As String
            Get
                Return ResourceManager.GetString("IDS_BTN_TABNAME_OLD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  JP設備 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_BTN_TABNAME() As String
            Get
                Return ResourceManager.GetString("IDS_BTN_TABNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ADSK.MepVerticalMark.dll に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_BTN_VERTICALDUCTMARK_ASSEMBLYNAME() As String
            Get
                Return ResourceManager.GetString("IDS_BTN_VERTICALDUCTMARK_ASSEMBLYNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ADSK.MepVerticalMark.CmdVerticalDuctMark に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_BTN_VERTICALDUCTMARK_CLASSNAME() As String
            Get
                Return ResourceManager.GetString("IDS_BTN_VERTICALDUCTMARK_CLASSNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  矢羽ダクト に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_BTN_VERTICALDUCTMARK_NAME() As String
            Get
                Return ResourceManager.GetString("IDS_BTN_VERTICALDUCTMARK_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  矢羽ダクト に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_BTN_VERTICALDUCTMARK_TEXT() As String
            Get
                Return ResourceManager.GetString("IDS_BTN_VERTICALDUCTMARK_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ダクトの矢羽を作成します に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_BTN_VERTICALDUCTMARK_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("IDS_BTN_VERTICALDUCTMARK_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ADSK.MepVerticalMark.dll に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_BTN_VERTICALPIPEMARK_ASSEMBLYNAME() As String
            Get
                Return ResourceManager.GetString("IDS_BTN_VERTICALPIPEMARK_ASSEMBLYNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ADSK.MepVerticalMark.CmdVerticalPipeMark に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_BTN_VERTICALPIPEMARK_CLASSNAME() As String
            Get
                Return ResourceManager.GetString("IDS_BTN_VERTICALPIPEMARK_CLASSNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  矢羽配管 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_BTN_VERTICALPIPEMARK_NAME() As String
            Get
                Return ResourceManager.GetString("IDS_BTN_VERTICALPIPEMARK_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  矢羽配管 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_BTN_VERTICALPIPEMARK_TEXT() As String
            Get
                Return ResourceManager.GetString("IDS_BTN_VERTICALPIPEMARK_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  配管の矢羽を作成します に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_BTN_VERTICALPIPEMARK_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("IDS_BTN_VERTICALPIPEMARK_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  詳細線分作成のエラー に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_ERR_CREATEDETAILLINEERR() As String
            Get
                Return ResourceManager.GetString("IDS_ERR_CREATEDETAILLINEERR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0} がロードされていません。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_ERR_FAMILYNOTLOAD() As String
            Get
                Return ResourceManager.GetString("IDS_ERR_FAMILYNOTLOAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  点の位置が不適切です。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_ERR_INVALIDPOINT() As String
            Get
                Return ResourceManager.GetString("IDS_ERR_INVALIDPOINT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0}+100を通過するダクトが見つかりません。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_ERR_NOCURRENTLEVELDUCT() As String
            Get
                Return ResourceManager.GetString("IDS_ERR_NOCURRENTLEVELDUCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0}+100を通過する配管が見つかりません。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_ERR_NOCURRENTLEVELPIPE() As String
            Get
                Return ResourceManager.GetString("IDS_ERR_NOCURRENTLEVELPIPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0}{1}を通過するダクトが見つかりません。
        '''</summary>
        Friend ReadOnly Property IDS_ERR_NO_SPECIFIED_DUCT() As String
            Get
                Return ResourceManager.GetString("IDS_ERR_NO_SPECIFIED_DUCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0}{1}を通過する配管が見つかりません。
        '''</summary>
        Friend ReadOnly Property IDS_ERR_NO_SPECIFIED_PIPE() As String
            Get
                Return ResourceManager.GetString("IDS_ERR_NO_SPECIFIED_PIPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  線種「{0}」が定義されていません。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_ERR_NOLEADERLINESTYLE() As String
            Get
                Return ResourceManager.GetString("IDS_ERR_NOLEADERLINESTYLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  平面図で起動してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_ERR_NOTVIEWPLAN() As String
            Get
                Return ResourceManager.GetString("IDS_ERR_NOTVIEWPLAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0}-100を通過するダクトが見つかりません。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_ERR_NOUPLEVELDUCT() As String
            Get
                Return ResourceManager.GetString("IDS_ERR_NOUPLEVELDUCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0}-100を通過する配管が見つかりません。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_ERR_NOUPLEVELPIPE() As String
            Get
                Return ResourceManager.GetString("IDS_ERR_NOUPLEVELPIPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  上のレベルがありません。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_ERR_NOUPPERLEVEL() As String
            Get
                Return ResourceManager.GetString("IDS_ERR_NOUPPERLEVEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ダクトを選択してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_ERR_SELECTDUCT() As String
            Get
                Return ResourceManager.GetString("IDS_ERR_SELECTDUCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  配管を選択してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_ERR_SELECTPIPE() As String
            Get
                Return ResourceManager.GetString("IDS_ERR_SELECTPIPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  操作がキャンセルされました。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_INFO_OPERATIONCANCEL() As String
            Get
                Return ResourceManager.GetString("IDS_INFO_OPERATIONCANCEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  たてダクトを選択 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_STATUS_SELECTDUCT() As String
            Get
                Return ResourceManager.GetString("IDS_STATUS_SELECTDUCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  たて配管を選択 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_STATUS_SELECTPIPE() As String
            Get
                Return ResourceManager.GetString("IDS_STATUS_SELECTPIPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タグを配置する点を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_STATUS_SELECTPLACETAGPOINT() As String
            Get
                Return ResourceManager.GetString("IDS_STATUS_SELECTPLACETAGPOINT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  始点となるダクトを選択 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_STATUS_SELECTSTARTDUCT() As String
            Get
                Return ResourceManager.GetString("IDS_STATUS_SELECTSTARTDUCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  始点となる配管を選択 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_STATUS_SELECTSTARTPIPE() As String
            Get
                Return ResourceManager.GetString("IDS_STATUS_SELECTSTARTPIPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  : に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_TXT_COLON() As String
            Get
                Return ResourceManager.GetString("IDS_TXT_COLON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  下向き に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_TXT_DOWNDIR() As String
            Get
                Return ResourceManager.GetString("IDS_TXT_DOWNDIR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  エラー に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_TXT_ERR() As String
            Get
                Return ResourceManager.GetString("IDS_TXT_ERR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  RME 矢羽配管・ダクト.pdf に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_TXT_HELP() As String
            Get
                Return ResourceManager.GetString("IDS_TXT_HELP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Resources に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_TXT_HELPFOLDER() As String
            Get
                Return ResourceManager.GetString("IDS_TXT_HELPFOLDER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  情報 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_TXT_INFO() As String
            Get
                Return ResourceManager.GetString("IDS_TXT_INFO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  上向き に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_TXT_UPDIR() As String
            Get
                Return ResourceManager.GetString("IDS_TXT_UPDIR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  雑排水 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_TXT_ZATSUHAISUI() As String
            Get
                Return ResourceManager.GetString("IDS_TXT_ZATSUHAISUI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  *引出線 - D2/黒/実線 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LINESTYLE_LEADER() As String
            Get
                Return ResourceManager.GetString("LINESTYLE_LEADER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  D に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MARK_D() As String
            Get
                Return ResourceManager.GetString("MARK_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MARK_HAISUI() As String
            Get
                Return ResourceManager.GetString("MARK_HAISUI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  R に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MARK_R() As String
            Get
                Return ResourceManager.GetString("MARK_R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タグ 矢羽 ダクト サイズ_SC 100 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TAG_DUCT_SIZE_100() As String
            Get
                Return ResourceManager.GetString("TAG_DUCT_SIZE_100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タグ 矢羽 ダクト サイズ_SC 200 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TAG_DUCT_SIZE_200() As String
            Get
                Return ResourceManager.GetString("TAG_DUCT_SIZE_200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タグ 矢羽 ダクト システム省略形_SC 100 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TAG_DUCT_YABANE_100() As String
            Get
                Return ResourceManager.GetString("TAG_DUCT_YABANE_100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タグ 矢羽 ダクト システム省略形_SC 200 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TAG_DUCT_YABANE_200() As String
            Get
                Return ResourceManager.GetString("TAG_DUCT_YABANE_200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タグ 矢羽 配管 冷媒管符号_SC 100 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TAG_PIPE_REIBAI_100() As String
            Get
                Return ResourceManager.GetString("TAG_PIPE_REIBAI_100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タグ 矢羽 配管 冷媒管符号_SC 200 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TAG_PIPE_REIBAI_200() As String
            Get
                Return ResourceManager.GetString("TAG_PIPE_REIBAI_200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タグ 矢羽 配管 サイズ_SC 100 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TAG_PIPE_SIZE_100() As String
            Get
                Return ResourceManager.GetString("TAG_PIPE_SIZE_100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タグ 矢羽 配管 サイズ_SC 200 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TAG_PIPE_SIZE_200() As String
            Get
                Return ResourceManager.GetString("TAG_PIPE_SIZE_200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タグ 矢羽 配管 システム省略形_排水_SC 100 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TAG_PIPE_YABANE_EX_100() As String
            Get
                Return ResourceManager.GetString("TAG_PIPE_YABANE_EX_100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タグ 矢羽 配管 システム省略形_排水_SC 200 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TAG_PIPE_YABANE_EX_200() As String
            Get
                Return ResourceManager.GetString("TAG_PIPE_YABANE_EX_200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タグ 矢羽 配管 システム省略形_供給_SC 100 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TAG_PIPE_YABANE_SA_100() As String
            Get
                Return ResourceManager.GetString("TAG_PIPE_YABANE_SA_100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タグ 矢羽 配管 システム省略形_供給_SC 200 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TAG_PIPE_YABANE_SA_200() As String
            Get
                Return ResourceManager.GetString("TAG_PIPE_YABANE_SA_200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  線種の作成 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TRANS_CREATELINESTYLE() As String
            Get
                Return ResourceManager.GetString("TRANS_CREATELINESTYLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  矢羽作成 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TRANS_CREATEMARK() As String
            Get
                Return ResourceManager.GetString("TRANS_CREATEMARK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  下線の作成 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TRANS_CREATEUNDERLINE() As String
            Get
                Return ResourceManager.GetString("TRANS_CREATEUNDERLINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  タグ移動 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TRANS_MOVETAG() As String
            Get
                Return ResourceManager.GetString("TRANS_MOVETAG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  カンマ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TYPE_COMMA() As String
            Get
                Return ResourceManager.GetString("TYPE_COMMA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  00_なし に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TYPE_NASHI() As String
            Get
                Return ResourceManager.GetString("TYPE_NASHI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  01_汚水 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TYPE_OSUI() As String
            Get
                Return ResourceManager.GetString("TYPE_OSUI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  02_下 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TYPE_SHITA() As String
            Get
                Return ResourceManager.GetString("TYPE_SHITA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  標準 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TYPE_STANDARD() As String
            Get
                Return ResourceManager.GetString("TYPE_STANDARD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  00_通気 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TYPE_TSUKI() As String
            Get
                Return ResourceManager.GetString("TYPE_TSUKI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  01_上 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TYPE_UE() As String
            Get
                Return ResourceManager.GetString("TYPE_UE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  02_雑排水 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TYPE_ZATSUHAISUI() As String
            Get
                Return ResourceManager.GetString("TYPE_ZATSUHAISUI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property VerticalMark0() As System.Drawing.Bitmap
            Get
                Return Res.VerticalMark0
'                Dim obj As Object = ResourceManager.GetObject("VerticalMark0", resourceCulture)
'                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property VerticalMark1() As System.Drawing.Bitmap
            Get
                Return Res.VerticalMark1
'                Dim obj As Object = ResourceManager.GetObject("VerticalMark1", resourceCulture)
'                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
