//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.JExtRAC.CheckingALVS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADSK.JExtRAC.CheckingALVS.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan Standards Extension.
        /// </summary>
        internal static string IDS_BTN_PANELNAME {
            get {
                return ResourceManager.GetString("IDS_BTN_PANELNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REXJ.
        /// </summary>
        internal static string IDS_BTN_TABNAME {
            get {
                return ResourceManager.GetString("IDS_BTN_TABNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JP建築.
        /// </summary>
        internal static string IDS_BTN_TABNAME_OLD {
            get {
                return ResourceManager.GetString("IDS_BTN_TABNAME_OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string IDS_COLNAME_A {
            get {
                return ResourceManager.GetString("IDS_COLNAME_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACorr.
        /// </summary>
        internal static string IDS_COLNAME_ACORR {
            get {
                return ResourceManager.GetString("IDS_COLNAME_ACORR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AffiliationRoom.
        /// </summary>
        internal static string IDS_COLNAME_AFFILIATIONROOM {
            get {
                return ResourceManager.GetString("IDS_COLNAME_AFFILIATIONROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string IDS_COLNAME_AREA {
            get {
                return ResourceManager.GetString("IDS_COLNAME_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATemp.
        /// </summary>
        internal static string IDS_COLNAME_ATEMP {
            get {
                return ResourceManager.GetString("IDS_COLNAME_ATEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AverageCeilingHeight.
        /// </summary>
        internal static string IDS_COLNAME_AVERAGECEILINGHEIGHT {
            get {
                return ResourceManager.GetString("IDS_COLNAME_AVERAGECEILINGHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.
        /// </summary>
        internal static string IDS_COLNAME_B {
            get {
                return ResourceManager.GetString("IDS_COLNAME_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalcGroupName.
        /// </summary>
        internal static string IDS_COLNAME_CALCGROUPNAME {
            get {
                return ResourceManager.GetString("IDS_COLNAME_CALCGROUPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string IDS_COLNAME_CATEGORY {
            get {
                return ResourceManager.GetString("IDS_COLNAME_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CeilingHeight.
        /// </summary>
        internal static string IDS_COLNAME_CEILINGHEIGHT {
            get {
                return ResourceManager.GetString("IDS_COLNAME_CEILINGHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string IDS_COLNAME_D {
            get {
                return ResourceManager.GetString("IDS_COLNAME_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DistHorizontalCorr.
        /// </summary>
        internal static string IDS_COLNAME_DISTHORIZONTAL_CORR {
            get {
                return ResourceManager.GetString("IDS_COLNAME_DISTHORIZONTAL_CORR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DistHorizontalMeas.
        /// </summary>
        internal static string IDS_COLNAME_DISTHORIZONTAL_MEAS {
            get {
                return ResourceManager.GetString("IDS_COLNAME_DISTHORIZONTAL_MEAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DistVerticalCorr.
        /// </summary>
        internal static string IDS_COLNAME_DISTVERTICAL_CORR {
            get {
                return ResourceManager.GetString("IDS_COLNAME_DISTVERTICAL_CORR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DistVerticalMeas.
        /// </summary>
        internal static string IDS_COLNAME_DISTVERTICAL_MEAS {
            get {
                return ResourceManager.GetString("IDS_COLNAME_DISTVERTICAL_MEAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DsH.
        /// </summary>
        internal static string IDS_COLNAME_DSH {
            get {
                return ResourceManager.GetString("IDS_COLNAME_DSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupName.
        /// </summary>
        internal static string IDS_COLNAME_GROUPNAME {
            get {
                return ResourceManager.GetString("IDS_COLNAME_GROUPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeadHeight.
        /// </summary>
        internal static string IDS_COLNAME_HEADHEIGHT {
            get {
                return ResourceManager.GetString("IDS_COLNAME_HEADHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string IDS_COLNAME_HEIGHT {
            get {
                return ResourceManager.GetString("IDS_COLNAME_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HorizontalDist.
        /// </summary>
        internal static string IDS_COLNAME_HORIZONTALDIST {
            get {
                return ResourceManager.GetString("IDS_COLNAME_HORIZONTALDIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string IDS_COLNAME_ID {
            get {
                return ResourceManager.GetString("IDS_COLNAME_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judgment.
        /// </summary>
        internal static string IDS_COLNAME_JUDGMENT {
            get {
                return ResourceManager.GetString("IDS_COLNAME_JUDGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LevelName.
        /// </summary>
        internal static string IDS_COLNAME_LEVELNAME {
            get {
                return ResourceManager.GetString("IDS_COLNAME_LEVELNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NecessaryArea.
        /// </summary>
        internal static string IDS_COLNAME_NECESSARYAREA {
            get {
                return ResourceManager.GetString("IDS_COLNAME_NECESSARYAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NecessaryCoefficient.
        /// </summary>
        internal static string IDS_COLNAME_NECESSARYCOEFFICIENT {
            get {
                return ResourceManager.GetString("IDS_COLNAME_NECESSARYCOEFFICIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenCoefficient.
        /// </summary>
        internal static string IDS_COLNAME_OPENCOEFFICIENT {
            get {
                return ResourceManager.GetString("IDS_COLNAME_OPENCOEFFICIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoadSide.
        /// </summary>
        internal static string IDS_COLNAME_ROADSIDE {
            get {
                return ResourceManager.GetString("IDS_COLNAME_ROADSIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomKind.
        /// </summary>
        internal static string IDS_COLNAME_ROOMKIND {
            get {
                return ResourceManager.GetString("IDS_COLNAME_ROOMKIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomName.
        /// </summary>
        internal static string IDS_COLNAME_ROOMNAME {
            get {
                return ResourceManager.GetString("IDS_COLNAME_ROOMNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomNo.
        /// </summary>
        internal static string IDS_COLNAME_ROOMNO {
            get {
                return ResourceManager.GetString("IDS_COLNAME_ROOMNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign.
        /// </summary>
        internal static string IDS_COLNAME_SIGN {
            get {
                return ResourceManager.GetString("IDS_COLNAME_SIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmokeWallLength.
        /// </summary>
        internal static string IDS_COLNAME_SMOKEWALLLENGTH {
            get {
                return ResourceManager.GetString("IDS_COLNAME_SMOKEWALLLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmokeWinHeight.
        /// </summary>
        internal static string IDS_COLNAME_SMOKEWINHEIGHT {
            get {
                return ResourceManager.GetString("IDS_COLNAME_SMOKEWINHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmokeWinWidth.
        /// </summary>
        internal static string IDS_COLNAME_SMOKEWINWIDTH {
            get {
                return ResourceManager.GetString("IDS_COLNAME_SMOKEWINWIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalUsableArea.
        /// </summary>
        internal static string IDS_COLNAME_TOTALUSABLEAREA {
            get {
                return ResourceManager.GetString("IDS_COLNAME_TOTALUSABLEAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeID.
        /// </summary>
        internal static string IDS_COLNAME_TYPEID {
            get {
                return ResourceManager.GetString("IDS_COLNAME_TYPEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsableArea.
        /// </summary>
        internal static string IDS_COLNAME_USABLEAREA {
            get {
                return ResourceManager.GetString("IDS_COLNAME_USABLEAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsableHeight.
        /// </summary>
        internal static string IDS_COLNAME_USABLEHEIGHT {
            get {
                return ResourceManager.GetString("IDS_COLNAME_USABLEHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsableHeightCA.
        /// </summary>
        internal static string IDS_COLNAME_USABLEHEIGHTCA {
            get {
                return ResourceManager.GetString("IDS_COLNAME_USABLEHEIGHTCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsableHeightCB.
        /// </summary>
        internal static string IDS_COLNAME_USABLEHEIGHTCB {
            get {
                return ResourceManager.GetString("IDS_COLNAME_USABLEHEIGHTCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsableHeightSmoke.
        /// </summary>
        internal static string IDS_COLNAME_USABLEHEIGHTSMOKE {
            get {
                return ResourceManager.GetString("IDS_COLNAME_USABLEHEIGHTSMOKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsableOpenArea.
        /// </summary>
        internal static string IDS_COLNAME_USABLEOPENAREA {
            get {
                return ResourceManager.GetString("IDS_COLNAME_USABLEOPENAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsableWidth.
        /// </summary>
        internal static string IDS_COLNAME_USABLEWIDTH {
            get {
                return ResourceManager.GetString("IDS_COLNAME_USABLEWIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsableWidthCA.
        /// </summary>
        internal static string IDS_COLNAME_USABLEWIDTHCA {
            get {
                return ResourceManager.GetString("IDS_COLNAME_USABLEWIDTHCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsableWidthCB.
        /// </summary>
        internal static string IDS_COLNAME_USABLEWIDTHCB {
            get {
                return ResourceManager.GetString("IDS_COLNAME_USABLEWIDTHCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranda.
        /// </summary>
        internal static string IDS_COLNAME_VERANDA {
            get {
                return ResourceManager.GetString("IDS_COLNAME_VERANDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VerticalDist.
        /// </summary>
        internal static string IDS_COLNAME_VERTICALDIST {
            get {
                return ResourceManager.GetString("IDS_COLNAME_VERTICALDIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string IDS_COLNAME_WIDTH {
            get {
                return ResourceManager.GetString("IDS_COLNAME_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドが失敗しました.
        /// </summary>
        internal static string IDS_ERR_COMMAND {
            get {
                return ResourceManager.GetString("IDS_ERR_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既存のエクセルに上書きしますか？.
        /// </summary>
        internal static string IDS_ERR_EXCELUPDATE {
            get {
                return ResourceManager.GetString("IDS_ERR_EXCELUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋種類係数取得に失敗しました.
        /// </summary>
        internal static string IDS_ERR_GETCOEFF_ROOMKIND {
            get {
                return ResourceManager.GetString("IDS_ERR_GETCOEFF_ROOMKIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用途地域係数取得に失敗しました.
        /// </summary>
        internal static string IDS_ERR_GETCOEFF_USEDISTRICT {
            get {
                return ResourceManager.GetString("IDS_ERR_GETCOEFF_USEDISTRICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エクセルをインストールしてください.
        /// </summary>
        internal static string IDS_ERR_INSTALLEXCEL {
            get {
                return ResourceManager.GetString("IDS_ERR_INSTALLEXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドパラメータの定義に失敗しました.
        /// </summary>
        internal static string IDS_ERR_PARAMCOMMAND {
            get {
                return ResourceManager.GetString("IDS_ERR_PARAMCOMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パラメータの定義に失敗しました.
        /// </summary>
        internal static string IDS_ERR_PARAMDEF {
            get {
                return ResourceManager.GetString("IDS_ERR_PARAMDEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 採光パラメータの定義に失敗しました.
        /// </summary>
        internal static string IDS_ERR_PARAMDEFLIGHTING {
            get {
                return ResourceManager.GetString("IDS_ERR_PARAMDEFLIGHTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to いくつかまたはすべての部屋の法定面積が設定されていません。面積の値を使用しますか？.
        /// </summary>
        internal static string IDS_ERR_ROOMNOLEGALAREA {
            get {
                return ResourceManager.GetString("IDS_ERR_ROOMNOLEGALAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建具を選択してから起動してください.
        /// </summary>
        internal static string IDS_ERR_SELPARTS {
            get {
                return ResourceManager.GetString("IDS_ERR_SELPARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋を選択してから起動してください.
        /// </summary>
        internal static string IDS_ERR_SELROOM {
            get {
                return ResourceManager.GetString("IDS_ERR_SELROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値が空白です.
        /// </summary>
        internal static string IDS_ERR_VALNULL {
            get {
                return ResourceManager.GetString("IDS_ERR_VALNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値が整数ではありません.
        /// </summary>
        internal static string IDS_ERR_VALNUMBER {
            get {
                return ResourceManager.GetString("IDS_ERR_VALNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値が数値ではありません.
        /// </summary>
        internal static string IDS_ERR_VALNUMERIC {
            get {
                return ResourceManager.GetString("IDS_ERR_VALNUMERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値が範囲外です.
        /// </summary>
        internal static string IDS_ERR_VALRANGE {
            get {
                return ResourceManager.GetString("IDS_ERR_VALRANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 防煙壁長さ（0.5m以上に設定してください）.
        /// </summary>
        internal static string IDS_ERR_VALSMOKEWALLLENGTH {
            get {
                return ResourceManager.GetString("IDS_ERR_VALSMOKEWALLLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficient.xml.
        /// </summary>
        internal static string IDS_FILE_COEFFICIENT {
            get {
                return ResourceManager.GetString("IDS_FILE_COEFFICIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建具を選択.
        /// </summary>
        internal static string IDS_PRT_SELECTWINDOOR {
            get {
                return ResourceManager.GetString("IDS_PRT_SELECTWINDOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RexJpn-CheckingALVS.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_CMD {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天井高さ.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_PARTS_CEILINGHEIGHT {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_CEILINGHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天端高さ.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_PARTS_HEADHEIGHT {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_HEADHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平補正距離.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_PARTS_HORIZONTALCORRDIST {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_HORIZONTALCORRDIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平距離.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_PARTS_HORIZONTALDIST {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_HORIZONTALDIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平測定距離.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_PARTS_HORIZONTALMEASDIST {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_HORIZONTALMEASDIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建具記号.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_PARTS_MARK {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建具番号.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_PARTS_NUMBER {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開口係数.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_PARTS_OPENCOEFF {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_OPENCOEFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 道路面.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_PARTS_ROADSIDE {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_ROADSIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 防煙壁長さ.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_PARTS_SMOKEWALLLENGTH {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_SMOKEWALLLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙窓高さ.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_PARTS_SMOKEWINHEIGHT {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_SMOKEWINHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙窓幅.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_PARTS_SMOKEWINWIDTH {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_SMOKEWINWIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙有効高さ.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_PARTS_USABLEHEIGHTSMOKE {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_USABLEHEIGHTSMOKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 縁側.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_PARTS_VERANDA {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_VERANDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直補正距離.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_PARTS_VERTICALCORRDIST {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_VERTICALCORRDIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直距離.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_PARTS_VERTICALDIST {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_VERTICALDIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直測定距離.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_PARTS_VERTICALMEASDIST {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_VERTICALMEASDIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋計算グループ.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_ROOM_CALCGROUP {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_ROOM_CALCGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋グループ.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_ROOM_GROUP {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_ROOM_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋種類.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_ROOM_KIND {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_ROOM_KIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 法定面積.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_ROOM_LEGALAREA {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_ROOM_LEGALAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 屋外.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_ROOM_OUTDOORS {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_ROOM_OUTDOORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RexJParam.txt.
        /// </summary>
        internal static string IDS_SHPARAM_FILE {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RexJpn.
        /// </summary>
        internal static string IDS_SHPARAM_GROUP {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/x.
        /// </summary>
        internal static string IDS_TXT_1SX {
            get {
                return ResourceManager.GetString("IDS_TXT_1SX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A(補正値).
        /// </summary>
        internal static string IDS_TXT_A_CORR {
            get {
                return ResourceManager.GetString("IDS_TXT_A_CORR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A
        ///(補正値).
        /// </summary>
        internal static string IDS_TXT_A_CORR_N {
            get {
                return ResourceManager.GetString("IDS_TXT_A_CORR_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A(仮).
        /// </summary>
        internal static string IDS_TXT_A_TEMP {
            get {
                return ResourceManager.GetString("IDS_TXT_A_TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A
        ///(仮).
        /// </summary>
        internal static string IDS_TXT_A_TEMP_N {
            get {
                return ResourceManager.GetString("IDS_TXT_A_TEMP_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加.
        /// </summary>
        internal static string IDS_TXT_ADD {
            get {
                return ResourceManager.GetString("IDS_TXT_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to α.
        /// </summary>
        internal static string IDS_TXT_ALPHA {
            get {
                return ResourceManager.GetString("IDS_TXT_ALPHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 面積.
        /// </summary>
        internal static string IDS_TXT_AREA {
            get {
                return ResourceManager.GetString("IDS_TXT_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均天井高.
        /// </summary>
        internal static string IDS_TXT_AVERAGECEILINGHEIGHT {
            get {
                return ResourceManager.GetString("IDS_TXT_AVERAGECEILINGHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均
        ///天井高.
        /// </summary>
        internal static string IDS_TXT_AVERAGECEILINGHEIGHT_N {
            get {
                return ResourceManager.GetString("IDS_TXT_AVERAGECEILINGHEIGHT_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to β.
        /// </summary>
        internal static string IDS_TXT_BETA {
            get {
                return ResourceManager.GetString("IDS_TXT_BETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 計算グループ.
        /// </summary>
        internal static string IDS_TXT_CALCGROUP {
            get {
                return ResourceManager.GetString("IDS_TXT_CALCGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 計算
        ///グループ.
        /// </summary>
        internal static string IDS_TXT_CALCGROUP_N {
            get {
                return ResourceManager.GetString("IDS_TXT_CALCGROUP_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string IDS_TXT_CANCEL {
            get {
                return ResourceManager.GetString("IDS_TXT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリ.
        /// </summary>
        internal static string IDS_TXT_CATEGORY {
            get {
                return ResourceManager.GetString("IDS_TXT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天井高.
        /// </summary>
        internal static string IDS_TXT_CEILINGHEIGHT {
            get {
                return ResourceManager.GetString("IDS_TXT_CEILINGHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一括変更.
        /// </summary>
        internal static string IDS_TXT_CHANGEBULK {
            get {
                return ResourceManager.GetString("IDS_TXT_CHANGEBULK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建具の有効寸法変更確認.
        /// </summary>
        internal static string IDS_TXT_CHANGEUSABLEDIMPARTS {
            get {
                return ResourceManager.GetString("IDS_TXT_CHANGEUSABLEDIMPARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切り上げ.
        /// </summary>
        internal static string IDS_TXT_CLOS {
            get {
                return ResourceManager.GetString("IDS_TXT_CLOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 閉じる.
        /// </summary>
        internal static string IDS_TXT_CLOSE {
            get {
                return ResourceManager.GetString("IDS_TXT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d/h・A(仮)・A(補正値).
        /// </summary>
        internal static string IDS_TXT_COMMON {
            get {
                return ResourceManager.GetString("IDS_TXT_COMMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 補正値.
        /// </summary>
        internal static string IDS_TXT_CORRECTIONVALUE {
            get {
                return ResourceManager.GetString("IDS_TXT_CORRECTIONVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見出しを作成する.
        /// </summary>
        internal static string IDS_TXT_CREATEHEADER {
            get {
                return ResourceManager.GetString("IDS_TXT_CREATEHEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切り捨て.
        /// </summary>
        internal static string IDS_TXT_CUTOFF {
            get {
                return ResourceManager.GetString("IDS_TXT_CUTOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string IDS_TXT_D {
            get {
                return ResourceManager.GetString("IDS_TXT_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小数点以下第.
        /// </summary>
        internal static string IDS_TXT_DECIMAL {
            get {
                return ResourceManager.GetString("IDS_TXT_DECIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既定.
        /// </summary>
        internal static string IDS_TXT_DEFAULT {
            get {
                return ResourceManager.GetString("IDS_TXT_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        internal static string IDS_TXT_DEL {
            get {
                return ResourceManager.GetString("IDS_TXT_DEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平距離.
        /// </summary>
        internal static string IDS_TXT_DISTHORIZONTAL {
            get {
                return ResourceManager.GetString("IDS_TXT_DISTHORIZONTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平補正距離.
        /// </summary>
        internal static string IDS_TXT_DISTHORIZONTAL_CORR {
            get {
                return ResourceManager.GetString("IDS_TXT_DISTHORIZONTAL_CORR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平測定距離.
        /// </summary>
        internal static string IDS_TXT_DISTHORIZONTAL_MEAS {
            get {
                return ResourceManager.GetString("IDS_TXT_DISTHORIZONTAL_MEAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d
        ///(水平距離).
        /// </summary>
        internal static string IDS_TXT_DISTHORIZONTAL_N {
            get {
                return ResourceManager.GetString("IDS_TXT_DISTHORIZONTAL_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直距離.
        /// </summary>
        internal static string IDS_TXT_DISTVERTICAL {
            get {
                return ResourceManager.GetString("IDS_TXT_DISTVERTICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直補正距離.
        /// </summary>
        internal static string IDS_TXT_DISTVERTICAL_CORR {
            get {
                return ResourceManager.GetString("IDS_TXT_DISTVERTICAL_CORR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直測定距離.
        /// </summary>
        internal static string IDS_TXT_DISTVERTICAL_MEAS {
            get {
                return ResourceManager.GetString("IDS_TXT_DISTVERTICAL_MEAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h
        ///(垂直距離).
        /// </summary>
        internal static string IDS_TXT_DISTVERTICAL_N {
            get {
                return ResourceManager.GetString("IDS_TXT_DISTVERTICAL_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to いない.
        /// </summary>
        internal static string IDS_TXT_DOESNT {
            get {
                return ResourceManager.GetString("IDS_TXT_DOESNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d/h
        ///(参考).
        /// </summary>
        internal static string IDS_TXT_DSH {
            get {
                return ResourceManager.GetString("IDS_TXT_DSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集.
        /// </summary>
        internal static string IDS_TXT_EDIT {
            get {
                return ResourceManager.GetString("IDS_TXT_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 階.
        /// </summary>
        internal static string IDS_TXT_FLOOR {
            get {
                return ResourceManager.GetString("IDS_TXT_FLOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to グループ.
        /// </summary>
        internal static string IDS_TXT_GROUP {
            get {
                return ResourceManager.GetString("IDS_TXT_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to グループ名.
        /// </summary>
        internal static string IDS_TXT_GROUPNAME {
            get {
                return ResourceManager.GetString("IDS_TXT_GROUPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高さ.
        /// </summary>
        internal static string IDS_TXT_HEIGHT {
            get {
                return ResourceManager.GetString("IDS_TXT_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あり.
        /// </summary>
        internal static string IDS_TXT_IS {
            get {
                return ResourceManager.GetString("IDS_TXT_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to いる.
        /// </summary>
        internal static string IDS_TXT_IT {
            get {
                return ResourceManager.GetString("IDS_TXT_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 判定.
        /// </summary>
        internal static string IDS_TXT_JUDGMENT {
            get {
                return ResourceManager.GetString("IDS_TXT_JUDGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 法定面積.
        /// </summary>
        internal static string IDS_TXT_LEGALAREA {
            get {
                return ResourceManager.GetString("IDS_TXT_LEGALAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レベル.
        /// </summary>
        internal static string IDS_TXT_LEVEL {
            get {
                return ResourceManager.GetString("IDS_TXT_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 採光.
        /// </summary>
        internal static string IDS_TXT_LIGHTING {
            get {
                return ResourceManager.GetString("IDS_TXT_LIGHTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 採光／排煙／換気.
        /// </summary>
        internal static string IDS_TXT_LIGHTING_SMOKE_VENTILATION {
            get {
                return ResourceManager.GetString("IDS_TXT_LIGHTING_SMOKE_VENTILATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 採光必要面積.
        /// </summary>
        internal static string IDS_TXT_LIGHTINGNESAREA {
            get {
                return ResourceManager.GetString("IDS_TXT_LIGHTINGNESAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 採光
        ///必要面積.
        /// </summary>
        internal static string IDS_TXT_LIGHTINGNESAREA_N {
            get {
                return ResourceManager.GetString("IDS_TXT_LIGHTINGNESAREA_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 採光必要係数.
        /// </summary>
        internal static string IDS_TXT_LIGHTINGNESCOEFF {
            get {
                return ResourceManager.GetString("IDS_TXT_LIGHTINGNESCOEFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 採光
        ///必要係数.
        /// </summary>
        internal static string IDS_TXT_LIGHTINGNESCOEFF_N {
            get {
                return ResourceManager.GetString("IDS_TXT_LIGHTINGNESCOEFF_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効採光面積.
        /// </summary>
        internal static string IDS_TXT_LIGHTINGUSABLEAREA {
            get {
                return ResourceManager.GetString("IDS_TXT_LIGHTINGUSABLEAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効採光
        ///面積.
        /// </summary>
        internal static string IDS_TXT_LIGHTINGUSABLEAREA_N {
            get {
                return ResourceManager.GetString("IDS_TXT_LIGHTINGUSABLEAREA_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ㎡.
        /// </summary>
        internal static string IDS_TXT_M2 {
            get {
                return ResourceManager.GetString("IDS_TXT_M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必要面積.
        /// </summary>
        internal static string IDS_TXT_NESAREA {
            get {
                return ResourceManager.GetString("IDS_TXT_NESAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to なし.
        /// </summary>
        internal static string IDS_TXT_NONE {
            get {
                return ResourceManager.GetString("IDS_TXT_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to なし.
        /// </summary>
        internal static string IDS_TXT_NOTHING {
            get {
                return ResourceManager.GetString("IDS_TXT_NOTHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string IDS_TXT_OK {
            get {
                return ResourceManager.GetString("IDS_TXT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開口係数.
        /// </summary>
        internal static string IDS_TXT_OPENCOEFF {
            get {
                return ResourceManager.GetString("IDS_TXT_OPENCOEFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効開口面積.
        /// </summary>
        internal static string IDS_TXT_OPENINGUSABLEAREA {
            get {
                return ResourceManager.GetString("IDS_TXT_OPENINGUSABLEAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効開口
        ///面積.
        /// </summary>
        internal static string IDS_TXT_OPENINGUSABLEAREA_N {
            get {
                return ResourceManager.GetString("IDS_TXT_OPENINGUSABLEAREA_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効開口高さ.
        /// </summary>
        internal static string IDS_TXT_OPENINGUSABLEHEIGHT {
            get {
                return ResourceManager.GetString("IDS_TXT_OPENINGUSABLEHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効開口
        ///高さ.
        /// </summary>
        internal static string IDS_TXT_OPENINGUSABLEHEIGHT_N {
            get {
                return ResourceManager.GetString("IDS_TXT_OPENINGUSABLEHEIGHT_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効開口幅.
        /// </summary>
        internal static string IDS_TXT_OPENINGUSABLEWIDTH {
            get {
                return ResourceManager.GetString("IDS_TXT_OPENINGUSABLEWIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効開口
        ///幅.
        /// </summary>
        internal static string IDS_TXT_OPENINGUSABLEWIDTH_N {
            get {
                return ResourceManager.GetString("IDS_TXT_OPENINGUSABLEWIDTH_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位を.
        /// </summary>
        internal static string IDS_TXT_ORDER {
            get {
                return ResourceManager.GetString("IDS_TXT_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel出力.
        /// </summary>
        internal static string IDS_TXT_OUTEXCEL {
            get {
                return ResourceManager.GetString("IDS_TXT_OUTEXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パラメータ.
        /// </summary>
        internal static string IDS_TXT_PARAMETER {
            get {
                return ResourceManager.GetString("IDS_TXT_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建具要素所属部屋.
        /// </summary>
        internal static string IDS_TXT_PARTSAFFILIATIONROOM {
            get {
                return ResourceManager.GetString("IDS_TXT_PARTSAFFILIATIONROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建具要素ID.
        /// </summary>
        internal static string IDS_TXT_PARTSELEMENTID {
            get {
                return ResourceManager.GetString("IDS_TXT_PARTSELEMENTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建具要素タイプ.
        /// </summary>
        internal static string IDS_TXT_PARTSELEMENTTYPE {
            get {
                return ResourceManager.GetString("IDS_TXT_PARTSELEMENTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建具要素FROM部屋ID.
        /// </summary>
        internal static string IDS_TXT_PARTSFROMROOMID {
            get {
                return ResourceManager.GetString("IDS_TXT_PARTSFROMROOMID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建具要素FROM部屋屋外.
        /// </summary>
        internal static string IDS_TXT_PARTSFROMROOMOUTDOORS {
            get {
                return ResourceManager.GetString("IDS_TXT_PARTSFROMROOMOUTDOORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建具符号.
        /// </summary>
        internal static string IDS_TXT_PARTSSIGN {
            get {
                return ResourceManager.GetString("IDS_TXT_PARTSSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建具
        ///符号.
        /// </summary>
        internal static string IDS_TXT_PARTSSIGN_N {
            get {
                return ResourceManager.GetString("IDS_TXT_PARTSSIGN_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建具要素TO部屋ID.
        /// </summary>
        internal static string IDS_TXT_PARTSTOROOMID {
            get {
                return ResourceManager.GetString("IDS_TXT_PARTSTOROOMID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建具要素TO部屋屋外.
        /// </summary>
        internal static string IDS_TXT_PARTSTOROOMOUTDOORS {
            get {
                return ResourceManager.GetString("IDS_TXT_PARTSTOROOMOUTDOORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建具天端高さ.
        /// </summary>
        internal static string IDS_TXT_PARTSUPPERMOSTSIDEHEIGHT {
            get {
                return ResourceManager.GetString("IDS_TXT_PARTSUPPERMOSTSIDEHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 道路面.
        /// </summary>
        internal static string IDS_TXT_ROADSIDE {
            get {
                return ResourceManager.GetString("IDS_TXT_ROADSIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋要素ID.
        /// </summary>
        internal static string IDS_TXT_ROOMELEMENTID {
            get {
                return ResourceManager.GetString("IDS_TXT_ROOMELEMENTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋グループ.
        /// </summary>
        internal static string IDS_TXT_ROOMGROUP {
            get {
                return ResourceManager.GetString("IDS_TXT_ROOMGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋グループ集計.
        /// </summary>
        internal static string IDS_TXT_ROOMGROUPTOTAL {
            get {
                return ResourceManager.GetString("IDS_TXT_ROOMGROUPTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋種類.
        /// </summary>
        internal static string IDS_TXT_ROOMKIND {
            get {
                return ResourceManager.GetString("IDS_TXT_ROOMKIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋名.
        /// </summary>
        internal static string IDS_TXT_ROOMNAME {
            get {
                return ResourceManager.GetString("IDS_TXT_ROOMNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋番号.
        /// </summary>
        internal static string IDS_TXT_ROOMNO {
            get {
                return ResourceManager.GetString("IDS_TXT_ROOMNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四捨五入.
        /// </summary>
        internal static string IDS_TXT_ROUNDINGOFF {
            get {
                return ResourceManager.GetString("IDS_TXT_ROUNDINGOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (安全側).
        /// </summary>
        internal static string IDS_TXT_SAFE_SIDE {
            get {
                return ResourceManager.GetString("IDS_TXT_SAFE_SIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string IDS_TXT_SAVE {
            get {
                return ResourceManager.GetString("IDS_TXT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択した建具.
        /// </summary>
        internal static string IDS_TXT_SELECTEDPARTS {
            get {
                return ResourceManager.GetString("IDS_TXT_SELECTEDPARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択した部屋.
        /// </summary>
        internal static string IDS_TXT_SELECTEDROOM {
            get {
                return ResourceManager.GetString("IDS_TXT_SELECTEDROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択した部屋グループ.
        /// </summary>
        internal static string IDS_TXT_SELECTEDROOMGROUP {
            get {
                return ResourceManager.GetString("IDS_TXT_SELECTEDROOMGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建具を選択.
        /// </summary>
        internal static string IDS_TXT_SELECTPARTS {
            get {
                return ResourceManager.GetString("IDS_TXT_SELECTPARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 採光-桁処理設定.
        /// </summary>
        internal static string IDS_TXT_SETTING {
            get {
                return ResourceManager.GetString("IDS_TXT_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 室番号.
        /// </summary>
        internal static string IDS_TXT_SITSUBANGO {
            get {
                return ResourceManager.GetString("IDS_TXT_SITSUBANGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 室グループ.
        /// </summary>
        internal static string IDS_TXT_SITSUGROUP {
            get {
                return ResourceManager.GetString("IDS_TXT_SITSUGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 室名.
        /// </summary>
        internal static string IDS_TXT_SITSUMEI {
            get {
                return ResourceManager.GetString("IDS_TXT_SITSUMEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙.
        /// </summary>
        internal static string IDS_TXT_SMOKE {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙-桁処理設定.
        /// </summary>
        internal static string IDS_TXT_SMOKE_SETTING {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙必要面積.
        /// </summary>
        internal static string IDS_TXT_SMOKENESAREA {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKENESAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙
        ///必要面積.
        /// </summary>
        internal static string IDS_TXT_SMOKENESAREA_N {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKENESAREA_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙必要係数.
        /// </summary>
        internal static string IDS_TXT_SMOKENESCOEFF {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKENESCOEFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙
        ///必要係数.
        /// </summary>
        internal static string IDS_TXT_SMOKENESCOEFF_N {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKENESCOEFF_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙有効面積.
        /// </summary>
        internal static string IDS_TXT_SMOKEUSABLEAREA {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKEUSABLEAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙有効
        ///面積.
        /// </summary>
        internal static string IDS_TXT_SMOKEUSABLEAREA_N {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKEUSABLEAREA_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙有効高さ.
        /// </summary>
        internal static string IDS_TXT_SMOKEUSABLEHEIGHT {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKEUSABLEHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙有効
        ///高さ.
        /// </summary>
        internal static string IDS_TXT_SMOKEUSABLEHEIGHT_N {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKEUSABLEHEIGHT_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙有効高下端.
        /// </summary>
        internal static string IDS_TXT_SMOKEUSABLEHEIGHTBOTTOM {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKEUSABLEHEIGHTBOTTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙有効幅.
        /// </summary>
        internal static string IDS_TXT_SMOKEUSABLEWIDTH {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKEUSABLEWIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙有効
        ///幅.
        /// </summary>
        internal static string IDS_TXT_SMOKEUSABLEWIDTH_N {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKEUSABLEWIDTH_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 防煙壁長さ.
        /// </summary>
        internal static string IDS_TXT_SMOKEWALLLENGTH {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKEWALLLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 防煙壁
        ///長さ.
        /// </summary>
        internal static string IDS_TXT_SMOKEWALLLENGTH_N {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKEWALLLENGTH_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙窓高さ.
        /// </summary>
        internal static string IDS_TXT_SMOKEWINHEIGHT {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKEWINHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙窓
        ///高さ.
        /// </summary>
        internal static string IDS_TXT_SMOKEWINHEIGHT_N {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKEWINHEIGHT_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更後
        ///排煙窓高さ.
        /// </summary>
        internal static string IDS_TXT_SMOKEWINHEIGHTCA {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKEWINHEIGHTCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更前
        ///排煙窓高さ.
        /// </summary>
        internal static string IDS_TXT_SMOKEWINHEIGHTCB {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKEWINHEIGHTCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙窓幅.
        /// </summary>
        internal static string IDS_TXT_SMOKEWINWIDTH {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKEWINWIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙窓
        ///幅.
        /// </summary>
        internal static string IDS_TXT_SMOKEWINWIDTH_N {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKEWINWIDTH_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更後
        ///排煙窓幅.
        /// </summary>
        internal static string IDS_TXT_SMOKEWINWIDTHCA {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKEWINWIDTHCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更前
        ///排煙窓幅.
        /// </summary>
        internal static string IDS_TXT_SMOKEWINWIDTHCB {
            get {
                return ResourceManager.GetString("IDS_TXT_SMOKEWINWIDTHCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仮.
        /// </summary>
        internal static string IDS_TXT_TEMP {
            get {
                return ResourceManager.GetString("IDS_TXT_TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 道路に.
        /// </summary>
        internal static string IDS_TXT_TOROAD {
            get {
                return ResourceManager.GetString("IDS_TXT_TOROAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合計.
        /// </summary>
        internal static string IDS_TXT_TOTAL {
            get {
                return ResourceManager.GetString("IDS_TXT_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 面している.
        /// </summary>
        internal static string IDS_TXT_TOUCHESIT {
            get {
                return ResourceManager.GetString("IDS_TXT_TOUCHESIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        internal static string IDS_TXT_UPDATE {
            get {
                return ResourceManager.GetString("IDS_TXT_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天端高さ.
        /// </summary>
        internal static string IDS_TXT_UPPERMOSTSIDEHEIGHT {
            get {
                return ResourceManager.GetString("IDS_TXT_UPPERMOSTSIDEHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効面積.
        /// </summary>
        internal static string IDS_TXT_USABLEAREA {
            get {
                return ResourceManager.GetString("IDS_TXT_USABLEAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更後
        ///有効高さ.
        /// </summary>
        internal static string IDS_TXT_USABLEHEIGHTCA {
            get {
                return ResourceManager.GetString("IDS_TXT_USABLEHEIGHTCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更前
        ///有効高さ.
        /// </summary>
        internal static string IDS_TXT_USABLEHEIGHTCB {
            get {
                return ResourceManager.GetString("IDS_TXT_USABLEHEIGHTCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更後
        ///有効幅.
        /// </summary>
        internal static string IDS_TXT_USABLEWIDTHCA {
            get {
                return ResourceManager.GetString("IDS_TXT_USABLEWIDTHCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更前
        ///有効幅.
        /// </summary>
        internal static string IDS_TXT_USABLEWIDTHCB {
            get {
                return ResourceManager.GetString("IDS_TXT_USABLEWIDTHCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用途地域.
        /// </summary>
        internal static string IDS_TXT_USEDISTRICT {
            get {
                return ResourceManager.GetString("IDS_TXT_USEDISTRICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 換気.
        /// </summary>
        internal static string IDS_TXT_VENTILATION {
            get {
                return ResourceManager.GetString("IDS_TXT_VENTILATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 換気-桁処理設定.
        /// </summary>
        internal static string IDS_TXT_VENTILATION_SETTING {
            get {
                return ResourceManager.GetString("IDS_TXT_VENTILATION_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 換気必要面積.
        /// </summary>
        internal static string IDS_TXT_VENTILATIONNESAREA {
            get {
                return ResourceManager.GetString("IDS_TXT_VENTILATIONNESAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 換気
        ///必要面積.
        /// </summary>
        internal static string IDS_TXT_VENTILATIONNESAREA_N {
            get {
                return ResourceManager.GetString("IDS_TXT_VENTILATIONNESAREA_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 換気必要係数.
        /// </summary>
        internal static string IDS_TXT_VENTILATIONNESCOEFF {
            get {
                return ResourceManager.GetString("IDS_TXT_VENTILATIONNESCOEFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 換気
        ///必要係数.
        /// </summary>
        internal static string IDS_TXT_VENTILATIONNESCOEFF_N {
            get {
                return ResourceManager.GetString("IDS_TXT_VENTILATIONNESCOEFF_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 換気有効面積.
        /// </summary>
        internal static string IDS_TXT_VENTILATIONUSABLEAREA {
            get {
                return ResourceManager.GetString("IDS_TXT_VENTILATIONUSABLEAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 換気有効
        ///面積.
        /// </summary>
        internal static string IDS_TXT_VENTILATIONUSABLEAREA_N {
            get {
                return ResourceManager.GetString("IDS_TXT_VENTILATIONUSABLEAREA_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 換気有効高さ.
        /// </summary>
        internal static string IDS_TXT_VENTILATIONUSABLEHEIGHT {
            get {
                return ResourceManager.GetString("IDS_TXT_VENTILATIONUSABLEHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 換気有効
        ///高さ.
        /// </summary>
        internal static string IDS_TXT_VENTILATIONUSABLEHEIGHT_N {
            get {
                return ResourceManager.GetString("IDS_TXT_VENTILATIONUSABLEHEIGHT_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 換気有効幅.
        /// </summary>
        internal static string IDS_TXT_VENTILATIONUSABLEWIDTH {
            get {
                return ResourceManager.GetString("IDS_TXT_VENTILATIONUSABLEWIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 換気有効
        ///幅.
        /// </summary>
        internal static string IDS_TXT_VENTILATIONUSABLEWIDTH_N {
            get {
                return ResourceManager.GetString("IDS_TXT_VENTILATIONUSABLEWIDTH_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 縁側.
        /// </summary>
        internal static string IDS_TXT_VERANDA {
            get {
                return ResourceManager.GetString("IDS_TXT_VERANDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幅.
        /// </summary>
        internal static string IDS_TXT_WIDTH {
            get {
                return ResourceManager.GetString("IDS_TXT_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窓の面積.
        /// </summary>
        internal static string IDS_TXT_WINDOWAREA {
            get {
                return ResourceManager.GetString("IDS_TXT_WINDOWAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排煙有効面積.
        /// </summary>
        internal static string IDS_TXT_WINDOWSMOKEUSABLEAREA {
            get {
                return ResourceManager.GetString("IDS_TXT_WINDOWSMOKEUSABLEAREA", resourceCulture);
            }
        }
    }
}
