//------------------------------------------------------------------------------
// <auto-generated>
//     Strongly typed resources for ADSK.JExtRAC.PrintRegion.Resources.Text
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.JExtRAC.PrintRegion.Resources
{
    using System;
    using System.Globalization;
    using System.Resources;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal Text()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    ResourceManager temp = new ResourceManager("ADSK.JExtRAC.PrintRegion.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static string IDS_ERR_NO_PLANE => ResourceManager.GetString("IDS_ERR_NO_PLANE", resourceCulture);
        internal static string IDS_ERR_NO_PRINTER => ResourceManager.GetString("IDS_ERR_NO_PRINTER", resourceCulture);
        internal static string IDS_ERR_SAME_POINT => ResourceManager.GetString("IDS_ERR_SAME_POINT", resourceCulture);
        internal static string IDS_ERROR_FORMAT_SCALE => ResourceManager.GetString("IDS_ERROR_FORMAT_SCALE", resourceCulture);
        internal static string IDS_INFO_PICK_POINT_1 => ResourceManager.GetString("IDS_INFO_PICK_POINT_1", resourceCulture);
        internal static string IDS_INFO_PICK_POINT_2 => ResourceManager.GetString("IDS_INFO_PICK_POINT_2", resourceCulture);
        internal static string IDS_SHPARAM_DEF_CMD_LOCATESLAB => ResourceManager.GetString("IDS_SHPARAM_DEF_CMD_LOCATESLAB", resourceCulture);
        internal static string IDS_SHPARAM_FILE => ResourceManager.GetString("IDS_SHPARAM_FILE", resourceCulture);
        internal static string IDS_SHPARAM_GROUP => ResourceManager.GetString("IDS_SHPARAM_GROUP", resourceCulture);
        internal static string IDS_TXT_APPEARANCE => ResourceManager.GetString("IDS_TXT_APPEARANCE", resourceCulture);
        internal static string IDS_TXT_CANCEL => ResourceManager.GetString("IDS_TXT_CANCEL", resourceCulture);
        internal static string IDS_TXT_CENTER => ResourceManager.GetString("IDS_TXT_CENTER", resourceCulture);
        internal static string IDS_TXT_COLOR_COLOR => ResourceManager.GetString("IDS_TXT_COLOR_COLOR", resourceCulture);
        internal static string IDS_TXT_COLOR_GRAYSCALE => ResourceManager.GetString("IDS_TXT_COLOR_GRAYSCALE", resourceCulture);
        internal static string IDS_TXT_COLOR_MONOCHROME => ResourceManager.GetString("IDS_TXT_COLOR_MONOCHROME", resourceCulture);
        internal static string IDS_TXT_COLORS => ResourceManager.GetString("IDS_TXT_COLORS", resourceCulture);
        internal static string IDS_TXT_DELETE => ResourceManager.GetString("IDS_TXT_DELETE", resourceCulture);
        internal static string IDS_TXT_ERROR => ResourceManager.GetString("IDS_TXT_ERROR", resourceCulture);
        internal static string IDS_TXT_FIT_TO_PAGE => ResourceManager.GetString("IDS_TXT_FIT_TO_PAGE", resourceCulture);
        internal static string IDS_TXT_HIDDEN_LINES_VIEWS => ResourceManager.GetString("IDS_TXT_HIDDEN_LINES_VIEWS", resourceCulture);
        internal static string IDS_TXT_HIDE_CROP_BOUNDARIES => ResourceManager.GetString("IDS_TXT_HIDE_CROP_BOUNDARIES", resourceCulture);
        internal static string IDS_TXT_HIDE_REF_WORK_PLANES => ResourceManager.GetString("IDS_TXT_HIDE_REF_WORK_PLANES", resourceCulture);
        internal static string IDS_TXT_HIDE_SCOPE_BOXED => ResourceManager.GetString("IDS_TXT_HIDE_SCOPE_BOXED", resourceCulture);
        internal static string IDS_TXT_HIDE_UNREFERENCED_VIEW_TAGS => ResourceManager.GetString("IDS_TXT_HIDE_UNREFERENCED_VIEW_TAGS", resourceCulture);
        internal static string IDS_TXT_INVALID_INPUT => ResourceManager.GetString("IDS_TXT_INVALID_INPUT", resourceCulture);
        internal static string IDS_TXT_LANDSCAPE => ResourceManager.GetString("IDS_TXT_LANDSCAPE", resourceCulture);
        internal static string IDS_TXT_MARGIN_NO_MARGIN => ResourceManager.GetString("IDS_TXT_MARGIN_NO_MARGIN", resourceCulture);
        internal static string IDS_TXT_MARGIN_PRINTER_LIMIT => ResourceManager.GetString("IDS_TXT_MARGIN_PRINTER_LIMIT", resourceCulture);
        internal static string IDS_TXT_MARGIN_USER_DEFINED => ResourceManager.GetString("IDS_TXT_MARGIN_USER_DEFINED", resourceCulture);
        internal static string IDS_TXT_NAME => ResourceManager.GetString("IDS_TXT_NAME", resourceCulture);
        internal static string IDS_TXT_NEW => ResourceManager.GetString("IDS_TXT_NEW", resourceCulture);
        internal static string IDS_TXT_OFFSET_FROM_CONER => ResourceManager.GetString("IDS_TXT_OFFSET_FROM_CONER", resourceCulture);
        internal static string IDS_TXT_OK => ResourceManager.GetString("IDS_TXT_OK", resourceCulture);
        internal static string IDS_TXT_OPTION => ResourceManager.GetString("IDS_TXT_OPTION", resourceCulture);
        internal static string IDS_TXT_ORIENTATION => ResourceManager.GetString("IDS_TXT_ORIENTATION", resourceCulture);
        internal static string IDS_TXT_PAPER => ResourceManager.GetString("IDS_TXT_PAPER", resourceCulture);
        internal static string IDS_TXT_PAPER_PLACEMENT => ResourceManager.GetString("IDS_TXT_PAPER_PLACEMENT", resourceCulture);
        internal static string IDS_TXT_PICK_AREA => ResourceManager.GetString("IDS_TXT_PICK_AREA", resourceCulture);
        internal static string IDS_TXT_PORTRAIT => ResourceManager.GetString("IDS_TXT_PORTRAIT", resourceCulture);
        internal static string IDS_TXT_PREVIEW => ResourceManager.GetString("IDS_TXT_PREVIEW", resourceCulture);
        internal static string IDS_TXT_PREVIOUS => ResourceManager.GetString("IDS_TXT_PREVIOUS", resourceCulture);
        internal static string IDS_TXT_PRINT_REGION => ResourceManager.GetString("IDS_TXT_PRINT_REGION", resourceCulture);
        internal static string IDS_TXT_PRINT_SCALE => ResourceManager.GetString("IDS_TXT_PRINT_SCALE", resourceCulture);
        internal static string IDS_TXT_PRINT_SETUP => ResourceManager.GetString("IDS_TXT_PRINT_SETUP", resourceCulture);
        internal static string IDS_TXT_PRINTER_NAME => ResourceManager.GetString("IDS_TXT_PRINTER_NAME", resourceCulture);
        internal static string IDS_TXT_PROPERTIES => ResourceManager.GetString("IDS_TXT_PROPERTIES", resourceCulture);
        internal static string IDS_TXT_RASTER_HIGH => ResourceManager.GetString("IDS_TXT_RASTER_HIGH", resourceCulture);
        internal static string IDS_TXT_RASTER_LOW => ResourceManager.GetString("IDS_TXT_RASTER_LOW", resourceCulture);
        internal static string IDS_TXT_RASTER_MEDIUM => ResourceManager.GetString("IDS_TXT_RASTER_MEDIUM", resourceCulture);
        internal static string IDS_TXT_RASTER_PRESENTATION => ResourceManager.GetString("IDS_TXT_RASTER_PRESENTATION", resourceCulture);
        internal static string IDS_TXT_RASTER_PROCESSING => ResourceManager.GetString("IDS_TXT_RASTER_PROCESSING", resourceCulture);
        internal static string IDS_TXT_RASTER_QUALITY => ResourceManager.GetString("IDS_TXT_RASTER_QUALITY", resourceCulture);
        internal static string IDS_TXT_REGION_EDGES_MASK_COINCIDENT_LINES => ResourceManager.GetString("IDS_TXT_REGION_EDGES_MASK_COINCIDENT_LINES", resourceCulture);
        internal static string IDS_TXT_REMOVE_LINES_USING => ResourceManager.GetString("IDS_TXT_REMOVE_LINES_USING", resourceCulture);
        internal static string IDS_TXT_RENAME => ResourceManager.GetString("IDS_TXT_RENAME", resourceCulture);
        internal static string IDS_TXT_REPLACE_HALFTONE_WITH_THIN_LINES => ResourceManager.GetString("IDS_TXT_REPLACE_HALFTONE_WITH_THIN_LINES", resourceCulture);
        internal static string IDS_TXT_REVERT => ResourceManager.GetString("IDS_TXT_REVERT", resourceCulture);
        internal static string IDS_TXT_SAVE => ResourceManager.GetString("IDS_TXT_SAVE", resourceCulture);
        internal static string IDS_TXT_SAVE_AS => ResourceManager.GetString("IDS_TXT_SAVE_AS", resourceCulture);
        internal static string IDS_TXT_SCALE_FORMAT => ResourceManager.GetString("IDS_TXT_SCALE_FORMAT", resourceCulture);
        internal static string IDS_TXT_SHOW_LOG_ENG => ResourceManager.GetString("IDS_TXT_SHOW_LOG_ENG", resourceCulture);
        internal static string IDS_TXT_SHOW_LOG_JPN => ResourceManager.GetString("IDS_TXT_SHOW_LOG_JPN", resourceCulture);
        internal static string IDS_TXT_SIZE => ResourceManager.GetString("IDS_TXT_SIZE", resourceCulture);
        internal static string IDS_TXT_SOURCE => ResourceManager.GetString("IDS_TXT_SOURCE", resourceCulture);
        internal static string IDS_TXT_TRANSACTION_PRINT_REGION => ResourceManager.GetString("IDS_TXT_TRANSACTION_PRINT_REGION", resourceCulture);
        internal static string IDS_TXT_VECTOR_PROCESSING => ResourceManager.GetString("IDS_TXT_VECTOR_PROCESSING", resourceCulture);
        internal static string IDS_TXT_VIEW_LINKS_IN_BLUE => ResourceManager.GetString("IDS_TXT_VIEW_LINKS_IN_BLUE", resourceCulture);
        internal static string IDS_TXT_VIEW_PRINTER => ResourceManager.GetString("IDS_TXT_VIEW_PRINTER", resourceCulture);
        internal static string IDS_TXT_ZOOM => ResourceManager.GetString("IDS_TXT_ZOOM", resourceCulture);
    }
}
