// ToDo: リソース読み込みできなくなったので暫定的にリソース読み込みの自動生成をやめ手動で対応。

//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using SectionListRC.Utils ;

namespace SectionListRC.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SectionListRC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap GapSetting_Beam {
            get {
                // object obj = ResourceManager.GetObject("GapSetting_Beam", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.GapSetting_Beam.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap GapSetting_Column {
            get {
                // object obj = ResourceManager.GetObject("GapSetting_Column", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.GapSetting_Column.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap help_24x24 {
            get {
                // object obj = ResourceManager.GetObject("help_24x24", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.help_24x24.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap help_32x32 {
            get {
                // object obj = ResourceManager.GetObject("help_32x32", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.help_32x32.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap help2_32x32 {
            get {
                // object obj = ResourceManager.GetObject("help2_32x32", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.help2_32x32.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Hint_Dimension {
            get {
                // object obj = ResourceManager.GetObject("Hint_Dimension", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.Hint_Dimension.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap LevelFrameSetting_InItemFrame {
            get {
                //object obj = ResourceManager.GetObject("LevelFrameSetting_InItemFrame", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.LevelFrameSetting_InItemFrame.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap LevelFrameSetting_Show {
            get {
                //object obj = ResourceManager.GetObject("LevelFrameSetting_Show", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.LevelFrameSetting_Show.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap PositionSeparator_NoShow {
            get {
                // object obj = ResourceManager.GetObject("PositionSeparator_NoShow", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.PositionSeparator_NoShow.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap PositionSeparator_Show {
            get {
                // object obj = ResourceManager.GetObject("PositionSeparator_Show", resourceCulture);
                var obj = ResHelper.GetEmbeddedImage( "SectionListRC.Res.PositionSeparator_Show.png" ) ;
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
