//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.JExtRAC.FittingSchedule.Resources {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADSK.JExtRAC.FittingSchedule.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string IDS_BTN_PANELNAME {
            get { return ResourceManager.GetString("IDS_BTN_PANELNAME", resourceCulture); }
        }

        internal static string IDS_BTN_TABNAME {
            get { return ResourceManager.GetString("IDS_BTN_TABNAME", resourceCulture); }
        }

        internal static string IDS_BTN_TABNAME_OLD {
            get { return ResourceManager.GetString("IDS_BTN_TABNAME_OLD", resourceCulture); }
        }

        internal static string IDS_ERR_CBONULL {
            get { return ResourceManager.GetString("IDS_ERR_CBONULL", resourceCulture); }
        }

        internal static string IDS_ERR_COMMAND {
            get { return ResourceManager.GetString("IDS_ERR_COMMAND", resourceCulture); }
        }

        internal static string IDS_ERR_CREATEPARTSDRAW {
            get { return ResourceManager.GetString("IDS_ERR_CREATEPARTSDRAW", resourceCulture); }
        }

        internal static string IDS_ERR_DELETEACTIVEVIEW {
            get { return ResourceManager.GetString("IDS_ERR_DELETEACTIVEVIEW", resourceCulture); }
        }

        internal static string IDS_ERR_GETVIEWPARTS {
            get { return ResourceManager.GetString("IDS_ERR_GETVIEWPARTS", resourceCulture); }
        }

        internal static string IDS_ERR_LAYOUTPARTSDRAW {
            get { return ResourceManager.GetString("IDS_ERR_LAYOUTPARTSDRAW", resourceCulture); }
        }

        internal static string IDS_ERR_LSTNULL {
            get { return ResourceManager.GetString("IDS_ERR_LSTNULL", resourceCulture); }
        }

        internal static string IDS_ERR_NOPARTS {
            get { return ResourceManager.GetString("IDS_ERR_NOPARTS", resourceCulture); }
        }

        internal static string IDS_ERR_PARAMCOMMAND {
            get { return ResourceManager.GetString("IDS_ERR_PARAMCOMMAND", resourceCulture); }
        }

        internal static string IDS_ERR_PARAMDEF {
            get { return ResourceManager.GetString("IDS_ERR_PARAMDEF", resourceCulture); }
        }

        internal static string IDS_ERR_SELPARTS {
            get { return ResourceManager.GetString("IDS_ERR_SELPARTS", resourceCulture); }
        }

        internal static string IDS_ERR_SETVIEWPORT {
            get { return ResourceManager.GetString("IDS_ERR_SETVIEWPORT", resourceCulture); }
        }

        internal static string IDS_ERR_VALNULL {
            get { return ResourceManager.GetString("IDS_ERR_VALNULL", resourceCulture); }
        }

        internal static string IDS_ERR_VALNUMBER {
            get { return ResourceManager.GetString("IDS_ERR_VALNUMBER", resourceCulture); }
        }

        internal static string IDS_ERR_VALRANGE {
            get { return ResourceManager.GetString("IDS_ERR_VALRANGE", resourceCulture); }
        }

        internal static string IDS_ERR_VIEWSEC {
            get { return ResourceManager.GetString("IDS_ERR_VIEWSEC", resourceCulture); }
        }

        internal static string IDS_ERR_VIEWSHEET {
            get { return ResourceManager.GetString("IDS_ERR_VIEWSHEET", resourceCulture); }
        }

        internal static string IDS_LST_SECVIEW_DOOR {
            get { return ResourceManager.GetString("IDS_LST_SECVIEW_DOOR", resourceCulture); }
        }

        internal static string IDS_LST_SECVIEW_WINDOW {
            get { return ResourceManager.GetString("IDS_LST_SECVIEW_WINDOW", resourceCulture); }
        }

        internal static string IDS_SET_VIEWBBOXBLANK {
            get { return ResourceManager.GetString("IDS_SET_VIEWBBOXBLANK", resourceCulture); }
        }

        internal static string IDS_SET_VIEWPORTSYM_1 {
            get { return ResourceManager.GetString("IDS_SET_VIEWPORTSYM_1", resourceCulture); }
        }

        internal static string IDS_SET_VIEWPORTSYM_2 {
            get { return ResourceManager.GetString("IDS_SET_VIEWPORTSYM_2", resourceCulture); }
        }

        internal static string IDS_SET_VIEWPORTSYM_3 {
            get { return ResourceManager.GetString("IDS_SET_VIEWPORTSYM_3", resourceCulture); }
        }

        internal static string IDS_SHPARAM_DEF_CMD_CREATEANDEDIT {
            get { return ResourceManager.GetString("IDS_SHPARAM_DEF_CMD_CREATEANDEDIT", resourceCulture); }
        }

        internal static string IDS_SHPARAM_DEF_CMD_LAYOUT {
            get { return ResourceManager.GetString("IDS_SHPARAM_DEF_CMD_LAYOUT", resourceCulture); }
        }

        internal static string IDS_SHPARAM_DEF_PARTS_MARK {
            get { return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_MARK", resourceCulture); }
        }

        internal static string IDS_SHPARAM_DEF_PARTS_NUMBER {
            get { return ResourceManager.GetString("IDS_SHPARAM_DEF_PARTS_NUMBER", resourceCulture); }
        }

        internal static string IDS_SHPARAM_FILE {
            get { return ResourceManager.GetString("IDS_SHPARAM_FILE", resourceCulture); }
        }

        internal static string IDS_SHPARAM_GROUP {
            get { return ResourceManager.GetString("IDS_SHPARAM_GROUP", resourceCulture); }
        }

        internal static string IDS_TXT_BLANK {
            get { return ResourceManager.GetString("IDS_TXT_BLANK", resourceCulture); }
        }

        internal static string IDS_TXT_BOTH {
            get { return ResourceManager.GetString("IDS_TXT_BOTH", resourceCulture); }
        }

        internal static string IDS_TXT_BOTTOM {
            get { return ResourceManager.GetString("IDS_TXT_BOTTOM", resourceCulture); }
        }

        internal static string IDS_TXT_CANCEL {
            get { return ResourceManager.GetString("IDS_TXT_CANCEL", resourceCulture); }
        }

        internal static string IDS_TXT_CATEGORY {
            get { return ResourceManager.GetString("IDS_TXT_CATEGORY", resourceCulture); }
        }

        internal static string IDS_TXT_CHANGEOLDVIEW {
            get { return ResourceManager.GetString("IDS_TXT_CHANGEOLDVIEW", resourceCulture); }
        }

        internal static string IDS_TXT_CLOSELOG {
            get { return ResourceManager.GetString("IDS_TXT_CLOSELOG", resourceCulture); }
        }

        internal static string IDS_TXT_COLON1 {
            get { return ResourceManager.GetString("IDS_TXT_COLON1", resourceCulture); }
        }

        internal static string IDS_TXT_CREATEPARTSDRAWING {
            get { return ResourceManager.GetString("IDS_TXT_CREATEPARTSDRAWING", resourceCulture); }
        }

        internal static string IDS_TXT_CREATEVIEWPARTS {
            get { return ResourceManager.GetString("IDS_TXT_CREATEVIEWPARTS", resourceCulture); }
        }

        internal static string IDS_TXT_CUSTOM {
            get { return ResourceManager.GetString("IDS_TXT_CUSTOM", resourceCulture); }
        }

        internal static string IDS_TXT_DELOLDVIEW {
            get { return ResourceManager.GetString("IDS_TXT_DELOLDVIEW", resourceCulture); }
        }

        internal static string IDS_TXT_DETAILLEVEL {
            get { return ResourceManager.GetString("IDS_TXT_DETAILLEVEL", resourceCulture); }
        }

        internal static string IDS_TXT_DETAILLEVEL_COARSE {
            get { return ResourceManager.GetString("IDS_TXT_DETAILLEVEL_COARSE", resourceCulture); }
        }

        internal static string IDS_TXT_DETAILLEVEL_FINE {
            get { return ResourceManager.GetString("IDS_TXT_DETAILLEVEL_FINE", resourceCulture); }
        }

        internal static string IDS_TXT_DETAILLEVEL_MEDIUM {
            get { return ResourceManager.GetString("IDS_TXT_DETAILLEVEL_MEDIUM", resourceCulture); }
        }

        internal static string IDS_TXT_DOOR {
            get { return ResourceManager.GetString("IDS_TXT_DOOR", resourceCulture); }
        }

        internal static string IDS_TXT_DOORTAG {
            get { return ResourceManager.GetString("IDS_TXT_DOORTAG", resourceCulture); }
        }

        internal static string IDS_TXT_ERROR {
            get { return ResourceManager.GetString("IDS_TXT_ERROR", resourceCulture); }
        }

        internal static string IDS_TXT_GETVIEWPARTS {
            get { return ResourceManager.GetString("IDS_TXT_GETVIEWPARTS", resourceCulture); }
        }

        internal static string IDS_TXT_HANDLINGDUPLICATEVIEW {
            get { return ResourceManager.GetString("IDS_TXT_HANDLINGDUPLICATEVIEW", resourceCulture); }
        }

        internal static string IDS_TXT_INFO {
            get { return ResourceManager.GetString("IDS_TXT_INFO", resourceCulture); }
        }

        internal static string IDS_TXT_LAYOUTPARTSDRAWING {
            get { return ResourceManager.GetString("IDS_TXT_LAYOUTPARTSDRAWING", resourceCulture); }
        }

        internal static string IDS_TXT_LAYOUTVIEWPARTS {
            get { return ResourceManager.GetString("IDS_TXT_LAYOUTVIEWPARTS", resourceCulture); }
        }

        internal static string IDS_TXT_LEFT {
            get { return ResourceManager.GetString("IDS_TXT_LEFT", resourceCulture); }
        }

        internal static string IDS_TXT_LOG {
            get { return ResourceManager.GetString("IDS_TXT_LOG", resourceCulture); }
        }

        internal static string IDS_TXT_NEWLINE {
            get { return ResourceManager.GetString("IDS_TXT_NEWLINE", resourceCulture); }
        }

        internal static string IDS_TXT_NOTUPDATE {
            get { return ResourceManager.GetString("IDS_TXT_NOTUPDATE", resourceCulture); }
        }

        internal static string IDS_TXT_OK {
            get { return ResourceManager.GetString("IDS_TXT_OK", resourceCulture); }
        }

        internal static string IDS_TXT_PARAMETER {
            get { return ResourceManager.GetString("IDS_TXT_PARAMETER", resourceCulture); }
        }

        internal static string IDS_TXT_PLACEMENTSOLIDPICTURE {
            get { return ResourceManager.GetString("IDS_TXT_PLACEMENTSOLIDPICTURE", resourceCulture); }
        }

        internal static string IDS_TXT_RIGHT {
            get { return ResourceManager.GetString("IDS_TXT_RIGHT", resourceCulture); }
        }

        internal static string IDS_TXT_SAVELOG {
            get { return ResourceManager.GetString("IDS_TXT_SAVELOG", resourceCulture); }
        }

        internal static string IDS_TXT_SCALE {
            get { return ResourceManager.GetString("IDS_TXT_SCALE", resourceCulture); }
        }

        internal static string IDS_TXT_SETVIEWPORT {
            get { return ResourceManager.GetString("IDS_TXT_SETVIEWPORT", resourceCulture); }
        }

        internal static string IDS_TXT_SIGNDEL {
            get { return ResourceManager.GetString("IDS_TXT_SIGNDEL", resourceCulture); }
        }

        internal static string IDS_TXT_SIGNDN {
            get { return ResourceManager.GetString("IDS_TXT_SIGNDN", resourceCulture); }
        }

        internal static string IDS_TXT_SIGNMOVE {
            get { return ResourceManager.GetString("IDS_TXT_SIGNMOVE", resourceCulture); }
        }

        internal static string IDS_TXT_SIGNUP {
            get { return ResourceManager.GetString("IDS_TXT_SIGNUP", resourceCulture); }
        }

        internal static string IDS_TXT_SOLIDPICTURE {
            get { return ResourceManager.GetString("IDS_TXT_SOLIDPICTURE", resourceCulture); }
        }

        internal static string IDS_TXT_TOP {
            get { return ResourceManager.GetString("IDS_TXT_TOP", resourceCulture); }
        }

        internal static string IDS_TXT_WINDOW {
            get { return ResourceManager.GetString("IDS_TXT_WINDOW", resourceCulture); }
        }

        internal static string IDS_TXT_WINDOWTAG {
            get { return ResourceManager.GetString("IDS_TXT_WINDOWTAG", resourceCulture); }
        }
    }
}
