//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MepDuctPipeTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MepDuctPipeTool.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配管/ダクトツール.
        /// </summary>
        internal static string ADDIN_NAME {
            get {
                return ResourceManager.GetString("ADDIN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ファミリを選択 --.
        /// </summary>
        internal static string COMBOBOX_TXT_PROMPT_SELECT_FAMILY {
            get {
                return ResourceManager.GetString("COMBOBOX_TXT_PROMPT_SELECT_FAMILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- タイプを選択 --.
        /// </summary>
        internal static string COMBOBOX_TXT_PROMPT_SELECT_TYPE {
            get {
                return ResourceManager.GetString("COMBOBOX_TXT_PROMPT_SELECT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フランジ挿入.
        /// </summary>
        internal static string COMMAND_NAME_INSERT_FLANGE {
            get {
                return ResourceManager.GetString("COMMAND_NAME_INSERT_FLANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フランジ・付属品配置.
        /// </summary>
        internal static string COMMAND_NAME_INSERT_PIPE_ACCESSORIES_WITH_FLANGE {
            get {
                return ResourceManager.GetString("COMMAND_NAME_INSERT_PIPE_ACCESSORIES_WITH_FLANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {CE3CD782-5A09-4F62-A596-140AB83C3A2F}.
        /// </summary>
        internal static string DOCKABLE_PANE_ID {
            get {
                return ResourceManager.GetString("DOCKABLE_PANE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フランジ配置設定.
        /// </summary>
        internal static string DOCKABLE_PANE_NAME {
            get {
                return ResourceManager.GetString("DOCKABLE_PANE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配管を切断できませんでした。.
        /// </summary>
        internal static string ERR_CANNNOT_SPLIT_PIPE {
            get {
                return ResourceManager.GetString("ERR_CANNNOT_SPLIT_PIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドを実行できませんでした。.
        /// </summary>
        internal static string ERR_CANNOT_EXECUTE_COMMAND {
            get {
                return ResourceManager.GetString("ERR_CANNOT_EXECUTE_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配管と同じ方向、または、分岐方向のコネクタが見つかりませんでした。.
        /// </summary>
        internal static string ERR_CANNOT_IDENTIFY_CONNECTOR_DIRECTIONS {
            get {
                return ResourceManager.GetString("ERR_CANNOT_IDENTIFY_CONNECTOR_DIRECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付属品とフランジで対応するコネクタが見つかりませんでした.
        /// </summary>
        internal static string ERR_COMPATIBLE_CONNECTOR_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_COMPATIBLE_CONNECTOR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コネクタが2or3個ではない配管付属品には未対応です。.
        /// </summary>
        internal static string ERR_CONNECTOR_NUM_IS_UNSUPPORTED {
            get {
                return ResourceManager.GetString("ERR_CONNECTOR_NUM_IS_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続しようとしているコネクタの位置がずれています。マニュアルに従ってファミリを修正することで問題が解決する可能性があります。.
        /// </summary>
        internal static string ERR_CONNECTOR_POS_MISMATCH {
            get {
                return ResourceManager.GetString("ERR_CONNECTOR_POS_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue with AddInCommandBinding. Please contact the REXJ addin developer..
        /// </summary>
        internal static string ERR_IN_COMMAND_CUSTOMIZER {
            get {
                return ResourceManager.GetString("ERR_IN_COMMAND_CUSTOMIZER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配管が選択されていません。.
        /// </summary>
        internal static string ERR_PIPE_IS_NOT_SELECTED {
            get {
                return ResourceManager.GetString("ERR_PIPE_IS_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Help\FlangeTools_Manual.pdf.
        /// </summary>
        internal static string HELP_FILE_NAME {
            get {
                return ResourceManager.GetString("HELP_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配管上に配管付属品とフランジを配置します。.
        /// </summary>
        internal static string RIBBON_BTN_TOOLTIP_INSERT_ACCESSORY_WITH_FLANGE {
            get {
                return ResourceManager.GetString("RIBBON_BTN_TOOLTIP_INSERT_ACCESSORY_WITH_FLANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配管上または配管付属品の端部へフランジを配置します。.
        /// </summary>
        internal static string RIBBON_BTN_TOOLTIP_INSERT_FLANGE {
            get {
                return ResourceManager.GetString("RIBBON_BTN_TOOLTIP_INSERT_FLANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置するフランジ/配管付属品のファミリ/タイプを設定します。.
        /// </summary>
        internal static string RIBBON_BTN_TOOLTIP_SHOW_SETTING {
            get {
                return ResourceManager.GetString("RIBBON_BTN_TOOLTIP_SHOW_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フランジ・
        ///付属品配置.
        /// </summary>
        internal static string RIBBON_BTN_TXT_INSERT_ACCESSORY_WITH_FLANGE {
            get {
                return ResourceManager.GetString("RIBBON_BTN_TXT_INSERT_ACCESSORY_WITH_FLANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フランジ挿入.
        /// </summary>
        internal static string RIBBON_BTN_TXT_INSERT_FLANGE {
            get {
                return ResourceManager.GetString("RIBBON_BTN_TXT_INSERT_FLANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フランジ
        ///配置設定表示.
        /// </summary>
        internal static string RIBBON_BTN_TXT_SHOW_SETTINGS {
            get {
                return ResourceManager.GetString("RIBBON_BTN_TXT_SHOW_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Images/accessory-flange-Small.png.
        /// </summary>
        internal static string RIBBON_IMG_INSERT_ACCESORRY_WITH_FLANGE_16 {
            get {
                return ResourceManager.GetString("RIBBON_IMG_INSERT_ACCESORRY_WITH_FLANGE_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Images/accessory-flange-Large.png.
        /// </summary>
        internal static string RIBBON_IMG_INSERT_ACCESORRY_WITH_FLANGE_32 {
            get {
                return ResourceManager.GetString("RIBBON_IMG_INSERT_ACCESORRY_WITH_FLANGE_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Images/insert-flange-Small.png.
        /// </summary>
        internal static string RIBBON_IMG_INSERT_FLANGE_16 {
            get {
                return ResourceManager.GetString("RIBBON_IMG_INSERT_FLANGE_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Images/insert-flange-Large.png.
        /// </summary>
        internal static string RIBBON_IMG_INSERT_FLANGE_32 {
            get {
                return ResourceManager.GetString("RIBBON_IMG_INSERT_FLANGE_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Images/flange-setting-Small.png.
        /// </summary>
        internal static string RIBBON_IMG_SHOW_SETTINGS_16 {
            get {
                return ResourceManager.GetString("RIBBON_IMG_SHOW_SETTINGS_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Images/flange-setting-Large.png.
        /// </summary>
        internal static string RIBBON_IMG_SHOW_SETTINGS_32 {
            get {
                return ResourceManager.GetString("RIBBON_IMG_SHOW_SETTINGS_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集.
        /// </summary>
        internal static string RIBBON_PANEL_NAME {
            get {
                return ResourceManager.GetString("RIBBON_PANEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REXJ.
        /// </summary>
        internal static string RIBBON_TAB_NAME {
            get {
                return ResourceManager.GetString("RIBBON_TAB_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JP設備.
        /// </summary>
        internal static string RIBBON_TAB_NAME_OLD {
            get {
                return ResourceManager.GetString("RIBBON_TAB_NAME_OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b8385de5-ea05-4157-963d-09d516b0f190.
        /// </summary>
        internal static string RUG_PARAM_GUID_INLET_DIAMETER {
            get {
                return ResourceManager.GetString("RUG_PARAM_GUID_INLET_DIAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a3d8fdf2-1160-4423-9d59-5f0169e970cc.
        /// </summary>
        internal static string RUG_PARAM_GUID_OUTLET_DIAMETER {
            get {
                return ResourceManager.GetString("RUG_PARAM_GUID_OUTLET_DIAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配管/配管付属品を選択してください。.
        /// </summary>
        internal static string STATUS_PROMPT_SELECT_PIPE_OR_ACCESSORY {
            get {
                return ResourceManager.GetString("STATUS_PROMPT_SELECT_PIPE_OR_ACCESSORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配管を選択してください。.
        /// </summary>
        internal static string STATUS_PROMPT_SLECT_PIPE {
            get {
                return ResourceManager.GetString("STATUS_PROMPT_SLECT_PIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フランジ挿入.
        /// </summary>
        internal static string TRANSACTION_NAME_INSERT_FLANGE {
            get {
                return ResourceManager.GetString("TRANSACTION_NAME_INSERT_FLANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フランジ付き配管付属品配置.
        /// </summary>
        internal static string TRANSACTION_NAME_INSERT_PIPE_ACCESSORY_WITH_FLANGE {
            get {
                return ResourceManager.GetString("TRANSACTION_NAME_INSERT_PIPE_ACCESSORY_WITH_FLANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フランジの原点が平座面のコネクタと一致していません。別のフランジファミリを使用してください。.
        /// </summary>
        internal static string WARN_FLANGE_FAMILY_ORIGIN_IS_NOT_ON_CONNECTOR {
            get {
                return ResourceManager.GetString("WARN_FLANGE_FAMILY_ORIGIN_IS_NOT_ON_CONNECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フランジ配置設定で有効なファミリ/タイプを選択してください。.
        /// </summary>
        internal static string WARN_INVALID_FAMILT_TYPE_IS_SELECTED {
            get {
                return ResourceManager.GetString("WARN_INVALID_FAMILT_TYPE_IS_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配管付属品に接続されている配管の勾配がそれぞれ異なるため、フランジを挿入できません。勾配を変更するか、配管付属品を再配置してください。.
        /// </summary>
        internal static string WARN_PIPE_SLOPE_IS_UNMATCH {
            get {
                return ResourceManager.GetString("WARN_PIPE_SLOPE_IS_UNMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配管付属品またはフランジの径パラメータが読み取り専用であるため、径を変更できませんでした。.
        /// </summary>
        internal static string WARN_RADIUS_PARAMETER_IS_READONLY {
            get {
                return ResourceManager.GetString("WARN_RADIUS_PARAMETER_IS_READONLY", resourceCulture);
            }
        }
    }
}
