//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSK.JExtRAC.AreaSchedule.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADSK.JExtRAC.AreaSchedule.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan Standards Extension.
        /// </summary>
        internal static string IDS_BTN_PANELNAME {
            get {
                return ResourceManager.GetString("IDS_BTN_PANELNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REXJ.
        /// </summary>
        internal static string IDS_BTN_TABNAME {
            get {
                return ResourceManager.GetString("IDS_BTN_TABNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JP建築.
        /// </summary>
        internal static string IDS_BTN_TABNAME_OLD {
            get {
                return ResourceManager.GetString("IDS_BTN_TABNAME_OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在の部屋境界は「壁の躯体面」になっています。続行しますか？.
        /// </summary>
        internal static string IDS_ERR_AREAOPTWALLCORELAYE {
            get {
                return ResourceManager.GetString("IDS_ERR_AREAOPTWALLCORELAYE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在の部屋境界は「壁の仕上面」になっています。続行しますか？.
        /// </summary>
        internal static string IDS_ERR_AREAOPTWALLFINISH {
            get {
                return ResourceManager.GetString("IDS_ERR_AREAOPTWALLFINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドが失敗しました.
        /// </summary>
        internal static string IDS_ERR_COMMAND {
            get {
                return ResourceManager.GetString("IDS_ERR_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋境界からエリア境界作成が失敗しました.
        /// </summary>
        internal static string IDS_ERR_CREATEAREABNDBYROOMBND {
            get {
                return ResourceManager.GetString("IDS_ERR_CREATEAREABNDBYROOMBND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋からエリア作成が失敗しました.
        /// </summary>
        internal static string IDS_ERR_CREATEAREABYROOM {
            get {
                return ResourceManager.GetString("IDS_ERR_CREATEAREABYROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エリアタグ作成が失敗しました.
        /// </summary>
        internal static string IDS_ERR_CREATEAREATAG {
            get {
                return ResourceManager.GetString("IDS_ERR_CREATEAREATAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 根拠式作成に失敗しました。エリア形状をご確認ください。.
        /// </summary>
        internal static string IDS_ERR_CREATEBASISEXPRESSION {
            get {
                return ResourceManager.GetString("IDS_ERR_CREATEBASISEXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 面積計算オプションの取得が失敗しました.
        /// </summary>
        internal static string IDS_ERR_GETAREACALCOPT {
            get {
                return ResourceManager.GetString("IDS_ERR_GETAREACALCOPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋が存在しません.
        /// </summary>
        internal static string IDS_ERR_NOTROOM {
            get {
                return ResourceManager.GetString("IDS_ERR_NOTROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エリアパラメータの設定に失敗しました.
        /// </summary>
        internal static string IDS_ERR_PARAMAREA {
            get {
                return ResourceManager.GetString("IDS_ERR_PARAMAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドパラメータの定義に失敗しました.
        /// </summary>
        internal static string IDS_ERR_PARAMCOMMAND {
            get {
                return ResourceManager.GetString("IDS_ERR_PARAMCOMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パラメータの定義に失敗しました.
        /// </summary>
        internal static string IDS_ERR_PARAMDEF {
            get {
                return ResourceManager.GetString("IDS_ERR_PARAMDEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エリアを選択してから起動してください.
        /// </summary>
        internal static string IDS_ERR_SELAREA {
            get {
                return ResourceManager.GetString("IDS_ERR_SELAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋を選択してから起動してください.
        /// </summary>
        internal static string IDS_ERR_SELROOM {
            get {
                return ResourceManager.GetString("IDS_ERR_SELROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 法定面積集計が失敗しました.
        /// </summary>
        internal static string IDS_ERR_SETLEGALAREA {
            get {
                return ResourceManager.GetString("IDS_ERR_SETLEGALAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値が空白です.
        /// </summary>
        internal static string IDS_ERR_VALNULL {
            get {
                return ResourceManager.GetString("IDS_ERR_VALNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値が整数ではありません.
        /// </summary>
        internal static string IDS_ERR_VALNUMBER {
            get {
                return ResourceManager.GetString("IDS_ERR_VALNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値が範囲外です.
        /// </summary>
        internal static string IDS_ERR_VALRANGE {
            get {
                return ResourceManager.GetString("IDS_ERR_VALRANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エリア平面図を開いてから使用してください.
        /// </summary>
        internal static string IDS_ERR_VIEWAREA {
            get {
                return ResourceManager.GetString("IDS_ERR_VIEWAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string IDS_SET_AREAMARGINERROR {
            get {
                return ResourceManager.GetString("IDS_SET_AREAMARGINERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 計算面積.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_AREA_AREACALC {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_AREA_AREACALC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 根拠式.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_AREA_AREAEXPN {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_AREA_AREAEXPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 枝番号.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_AREA_BRANCHNUMBER {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_AREA_BRANCHNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋名.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_AREA_ROOMNAME {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_AREA_ROOMNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋番号.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_AREA_ROOMNO {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_AREA_ROOMNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RexJpn-AreaSchedule-GroundsExpression.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_CMD_GROUNDSEXPRESSION {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_CMD_GROUNDSEXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RexJpn-AreaSchedule-LegalArea.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_CMD_LEGALAREA {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_CMD_LEGALAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RexJpn-AreaSchedule-RoomConvertedToArea.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_CMD_ROOMCONVERTEDTOAREA {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_CMD_ROOMCONVERTEDTOAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 法定面積.
        /// </summary>
        internal static string IDS_SHPARAM_DEF_ROOM_LEGALAREA {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_DEF_ROOM_LEGALAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RexJParam.txt.
        /// </summary>
        internal static string IDS_SHPARAM_FILE {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RexJpn.
        /// </summary>
        internal static string IDS_SHPARAM_GROUP {
            get {
                return ResourceManager.GetString("IDS_SHPARAM_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エリアタグを付ける.
        /// </summary>
        internal static string IDS_TXT_ADDAREATAG {
            get {
                return ResourceManager.GetString("IDS_TXT_ADDAREATAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 面積(法定) ㎡.
        /// </summary>
        internal static string IDS_TXT_AREA_LEGAL {
            get {
                return ResourceManager.GetString("IDS_TXT_AREA_LEGAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 面積(Revit) ㎡.
        /// </summary>
        internal static string IDS_TXT_AREA_RVT {
            get {
                return ResourceManager.GetString("IDS_TXT_AREA_RVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エリア面積の計算.
        /// </summary>
        internal static string IDS_TXT_AREACALC {
            get {
                return ResourceManager.GetString("IDS_TXT_AREACALC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 結果面積の桁処理.
        /// </summary>
        internal static string IDS_TXT_AREADECIMAL {
            get {
                return ResourceManager.GetString("IDS_TXT_AREADECIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 面積の許容誤差を超えています.
        /// </summary>
        internal static string IDS_TXT_AREAMARGINERROR {
            get {
                return ResourceManager.GetString("IDS_TXT_AREAMARGINERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 根拠式.
        /// </summary>
        internal static string IDS_TXT_BASISEXPRESSION {
            get {
                return ResourceManager.GetString("IDS_TXT_BASISEXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 計算面積.
        /// </summary>
        internal static string IDS_TXT_CALCAREA {
            get {
                return ResourceManager.GetString("IDS_TXT_CALCAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリ.
        /// </summary>
        internal static string IDS_TXT_CATEGORY {
            get {
                return ResourceManager.GetString("IDS_TXT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string IDS_TXT_CANCEL {
            get {
                return ResourceManager.GetString("IDS_TXT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業の選択.
        /// </summary>
        internal static string IDS_TXT_CHOICEWORK {
            get {
                return ResourceManager.GetString("IDS_TXT_CHOICEWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切り上げ.
        /// </summary>
        internal static string IDS_TXT_CLOSE {
            get {
                return ResourceManager.GetString("IDS_TXT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋をエリア境界に変換.
        /// </summary>
        internal static string IDS_TXT_CONVERTAREA {
            get {
                return ResourceManager.GetString("IDS_TXT_CONVERTAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋境界をエリア境界に変換する.
        /// </summary>
        internal static string IDS_TXT_CONVERTAREABOUNDARY {
            get {
                return ResourceManager.GetString("IDS_TXT_CONVERTAREABOUNDARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エリア作成.
        /// </summary>
        internal static string IDS_TXT_CREATEAREA {
            get {
                return ResourceManager.GetString("IDS_TXT_CREATEAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エリア境界作成.
        /// </summary>
        internal static string IDS_TXT_CREATEAREABOUNDARY {
            get {
                return ResourceManager.GetString("IDS_TXT_CREATEAREABOUNDARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エリアタグ作成.
        /// </summary>
        internal static string IDS_TXT_CREATEAREATAG {
            get {
                return ResourceManager.GetString("IDS_TXT_CREATEAREATAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 根拠式作成.
        /// </summary>
        internal static string IDS_TXT_CREATEBASISEXPN {
            get {
                return ResourceManager.GetString("IDS_TXT_CREATEBASISEXPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切り捨て.
        /// </summary>
        internal static string IDS_TXT_CUTOFF {
            get {
                return ResourceManager.GetString("IDS_TXT_CUTOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小数点以下第.
        /// </summary>
        internal static string IDS_TXT_DECIMAL {
            get {
                return ResourceManager.GetString("IDS_TXT_DECIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既定.
        /// </summary>
        internal static string IDS_TXT_DEFAULT {
            get {
                return ResourceManager.GetString("IDS_TXT_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 法定面積.
        /// </summary>
        internal static string IDS_TXT_LEGALAREA {
            get {
                return ResourceManager.GetString("IDS_TXT_LEGALAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 長さの桁処理.
        /// </summary>
        internal static string IDS_TXT_LENGTHDECIMAL {
            get {
                return ResourceManager.GetString("IDS_TXT_LENGTHDECIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string IDS_TXT_M {
            get {
                return ResourceManager.GetString("IDS_TXT_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （m）.
        /// </summary>
        internal static string IDS_TXT_M2 {
            get {
                return ResourceManager.GetString("IDS_TXT_M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （㎡）.
        /// </summary>
        internal static string IDS_TXT_M22 {
            get {
                return ResourceManager.GetString("IDS_TXT_M22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string IDS_TXT_MM {
            get {
                return ResourceManager.GetString("IDS_TXT_MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        internal static string IDS_TXT_NAME {
            get {
                return ResourceManager.GetString("IDS_TXT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string IDS_TXT_OK {
            get {
                return ResourceManager.GetString("IDS_TXT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位を.
        /// </summary>
        internal static string IDS_TXT_ORDER {
            get {
                return ResourceManager.GetString("IDS_TXT_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パラメータ.
        /// </summary>
        internal static string IDS_TXT_PARAMETER {
            get {
                return ResourceManager.GetString("IDS_TXT_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 円周率(π).
        /// </summary>
        internal static string IDS_TXT_PI {
            get {
                return ResourceManager.GetString("IDS_TXT_PI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋名.
        /// </summary>
        internal static string IDS_TXT_ROOMNAME {
            get {
                return ResourceManager.GetString("IDS_TXT_ROOMNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋番号.
        /// </summary>
        internal static string IDS_TXT_ROOMNUMBER {
            get {
                return ResourceManager.GetString("IDS_TXT_ROOMNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四捨五入.
        /// </summary>
        internal static string IDS_TXT_ROUNDINGOFF {
            get {
                return ResourceManager.GetString("IDS_TXT_ROUNDINGOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 法定面積集計.
        /// </summary>
        internal static string IDS_TXT_SETLEGALAREA {
            get {
                return ResourceManager.GetString("IDS_TXT_SETLEGALAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タグ.
        /// </summary>
        internal static string IDS_TXT_TAG {
            get {
                return ResourceManager.GetString("IDS_TXT_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単位.
        /// </summary>
        internal static string IDS_TXT_UNIT {
            get {
                return ResourceManager.GetString("IDS_TXT_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋名を使用.
        /// </summary>
        internal static string IDS_TXT_USEROOMNAME {
            get {
                return ResourceManager.GetString("IDS_TXT_USEROOMNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部屋番号を使用.
        /// </summary>
        internal static string IDS_TXT_USEROOMNO {
            get {
                return ResourceManager.GetString("IDS_TXT_USEROOMNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 壁の中心.
        /// </summary>
        internal static string IDS_TXT_WALLCENTER {
            get {
                return ResourceManager.GetString("IDS_TXT_WALLCENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 壁の躯体芯.
        /// </summary>
        internal static string IDS_TXT_WALLCORECENTER {
            get {
                return ResourceManager.GetString("IDS_TXT_WALLCORECENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 壁の躯体面.
        /// </summary>
        internal static string IDS_TXT_WALLCORELAYER {
            get {
                return ResourceManager.GetString("IDS_TXT_WALLCORELAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 壁の仕上面.
        /// </summary>
        internal static string IDS_TXT_WALLFINISH {
            get {
                return ResourceManager.GetString("IDS_TXT_WALLFINISH", resourceCulture);
            }
        }
    }
}
